### ISSUE TITLE
Uploaded media files do not show in list

### ISSUE THREAD

**Issue by TraceOrdin** [AzuraCast/AzuraCast#1073]
**Installation method**

Traditional 

**Host OS (for Docker installations)**

n/a

**Describe the bug**

Upon uploading audio files in Station>Music Files no errors are thrown on file upload but the file doesn't show in the list.

Looks like the files are getting stuck in /tmp/uploads without the period in the last part of the name, eg:

115521570-20170706Filenamemp3

**To Reproduce**

1. Go to Station
2. Click Music Files
3. Upload a file
4. File does not appear in list

**Expected behavior**

Normally the file would appear in the list once it's uploaded.

**Relevant Logs**

Nothing shows up in the logs, but the uploaded files are present in /tmp/uploads without the period at the end of the filename

**Screenshots**

n/a

**Device(s):**
 - Device:  PC
 - OS: Windows 10
 - Browser:  Chrome
 - Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**

May be related to the following two changes together: 

1. this recent commit related to making temp uploads to go the station temp dir: https://github.com/AzuraCast/AzuraCast/commit/128d57236e62eb16daf0c3a7ad3197e19ca6d3a8

2. As well as recent change of final uploaded file to have the period in it in (which I submitted):
https://github.com/AzuraCast/AzuraCast/commit/98370cf74ae3fc0fde6932b1dea3007cde811864

Maybe when the filename is being sanitized it takes the period out and then it can't move it to the final location.

**Comment by alexhorner** [comment]
I can confirm this issue is also occuring for me. It is extremely important this is fixed so we can start our service in January

**Comment by SlvrEagle23** [comment]
@TraceOrdin @alexhorner This issue should be fixed with the latest code push. You'll need to reupload any media that didn't show up before. My apologies for any inconvenience, it was down to a fairly minor PHP identity comparison issue.

**Comment by VTCAKAVSMoACE** [comment]
This did not resolve my issue. Perhaps #1075 is to blame for mine?
