### ISSUE TITLE
Dashboard inaccessible after update!

### ISSUE THREAD

**Issue by mele-uk** [AzuraCast/AzuraCast#1823]
After I updated to the latest version (today update), I am not able to browse the Admin dashboard anymore.

I used to login via https://domain.com/login, but after the update it goes automatically to https://domain.com:80/login and it shows: This site can’t be reached

**Comment by mele-uk** [comment]
Streaming works fine and the URL format is  https://domain.com/radio/8000/radio.mp3

But Dashboard is inaccessible, please check and solve the issue since it's very critical.

**Comment by mele-uk** [comment]
@SlvrEagle23 Help please!

**Comment by SlvrEagle23** [comment]
@mele-uk I will take a look. There's no need to mention me to make me see issues. I will get to issues as I can.

**Comment by mele-uk** [comment]
Thanks.
I think it's about Cloudflare. When I pause cloudflare service, the Dashboard page comes up but I get SSL certificate error.
Maybe the issue relates to Web Proxy.

**Comment by SlvrEagle23** [comment]
@mele-uk It's possible. Cloudflare is known to not like `http://site:80` or `https://site:443`.

I pushed a minor update out that might help with this by filtering the base URL to remove this scenario if it happens.

**Comment by mele-uk** [comment]
I updated but still the problem persists!

I tried to pause cloudflare but I get SSL connection error.
**Safari**
Connection not protected
The security of your connection is reduced. Criminals can attempt to steal your data from the website. You are advised to leave this website.

URL:
domain.com

Reason:
Self-signed certificate View certificate


**Opera**
This site can’t be reached
The webpage at https://domain.com/login might be temporarily down or it may have moved permanently to a new web address.

ERR_FAILED

**Comment by SlvrEagle23** [comment]
@mele-uk Oh, I know what's happening. Try switching your CloudFlare from "Flexible" to "Full" on the CF control panel. I'll push out a fix on the backend. We've seen this before.

**Comment by mele-uk** [comment]
I try to open the Dashboard on the Safari (iPhone) and I get the below errors:
The Connection Is Not Private

This website maybe impersonating "domain.com" to steal your personal or financial information. You should go back to the previous page.

Safari warns you when a website has a certificate that is not valid.
This may happen if the website is misconfigured or an attacker has compromised your connection.

To learn more, you can view the certificate. If you understand the risk involved, you can visit this website.

And when I view the certificate, I see these:
![ssl2](https://user-images.githubusercontent.com/53567566/62649740-a0629d00-b96a-11e9-9096-e2de4bbca553.jpg)

![ssl3](https://user-images.githubusercontent.com/53567566/62649759-a5275100-b96a-11e9-9d0b-b69e7517baa8.jpg)

**Comment by SlvrEagle23** [comment]
@mele-uk Re-enable CloudFlare protection and switch the connection mode from "Flexible" to "Full" in CloudFlare's configuration.

Just do that and report back if it helps. You don't need to send me any further screenshots; I know what your SSL certificate looks like.

**Comment by mele-uk** [comment]
Oh, I switched and the problem solved!

**Comment by SlvrEagle23** [comment]
@mele-uk Good to hear. I've implemented what should be a fix for the original issue, so we can close this issue.

**Comment by mele-uk** [comment]
Thank you for great work :)
