### ISSUE TITLE
LiquidSoap not following playlists.

### ISSUE THREAD

**Issue by NotifiedGaming** [AzuraCast/AzuraCast#1825]
Hey There.

So I first had a playlist 'advertising' playing every 3 seconds and playing one track only, After adding a few more adverts I decided to change it to play each advert after the other after 6 songs. But the, playlist does not follow these rules. 

recently, it's been doing:

song
sweeper
advert 1
sweeper
song

When what it should do is
song
sweeper 
advert 1-3 
song

any advice?

**Comment by NotifiedGaming** [comment]
I'm also getting a second issue where the embed player is 'refusing to connect' because it set 'X-Frame-Options' to 'deny'.

![image](https://user-images.githubusercontent.com/20782042/62652805-1ad3f280-b954-11e9-94ff-b1f3bc68e5ca.png)

**Comment by Vaalyn** [comment]
To ensure that the whole adverts playlist is playing one track ofter the other you should enable the `Merge playlist to play as a single track.` option on the playlist.

**Comment by NotifiedGaming** [comment]
That is enabled. But since then it just doesnt play anything besides the music and the odd sweeper whenever it likes.

Best way to put it: It has a mind of its own.

**Comment by NotifiedGaming** [comment]
Can i get some help with this please? It's been over 48 hours and i still have no paid adverts being played.

**Comment by ErnestPH** [comment]
Have you updated to the latest repo?

**Comment by SlvrEagle23** [comment]
@NotifiedGaming The "X-Frame-Options" error should be fixed as of more recent updates.

As for the playback, it sounds like you may need to take advantage of an "Advanced Playlist" with custom rotation rules, something like this in your custom Liquidsoap configuration:

```
radio = rotate(weights=[2,6], [playlist_ads, radio])
```

That's one of the most effective ways to ensure that _two_ songs from a given playlist play back to back between normal song rotation.

**Comment by NotifiedGaming** [comment]
Is their any documentation I can refer to when using "Advanced Playlist" Configuration? 

There's no point having the options on the panel if they don't do anything. @SlvrEagle23

**Comment by NotifiedGaming** [comment]
Alright so I've taken a look at [this](https://www.azuracast.com/help/advanced_playlists.html#case-study-side-by-side-playlists) page and still don't understand how it really works. - I really would rather to use the web panel as I'm a technical idiot.. How the playlists are configured right now, is how I want to play them, however the panel and liquidsoap isn't following them.

For further information, the adverts all play at first startup, then don't play again. - And sweepers play randomly.

**Comment by SlvrEagle23** [comment]
@NotifiedGaming In order for me to diagnose the issue further, I'd need to see every setting on all of your playlists, either via screenshot or via taking a look at your installation directly (you can join our [Mattermost chat](https://chat.azuracast.com/) to discuss that further if you like).

The Playlist scheduling items that are marked as "Advanced" are really just mirrors for some advanced Liquidsoap functionality, so if they're not working correctly that's usually because either we're mis-generating the resulting Liquidsoap configuration or Liquidsoap isn't following it correctly. It's a rough process of bug-finding, and it's usually easier to just leave those settings off.
