### ISSUE TITLE
Bug : same jingle played twice or more in a row

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#186]
Hi, It is systematic on my webradio that every  jingle, contained in a "play every X track" playlist is repeated twice and more .. up to 4 times in a row before the next track is played. This is really a problem.

I tried to force and end the file with 'end cue points', but the jingle indeed stops before its end, but still 4 times in a row !

This issue should not the caused by the inability of liquidsoap to read the next music track, since the track history shows if it should be played only once !

Wed 4:02pm | 1 | 0 | jingle-49 | Playlists : Jingles
Wed 3:58pm | 1 | 0 | k-hill-a-debonair-p-feat.-omniscence---root-4-me | Playlists : Brand New
Wed 3:57pm | 1 | 0 | jingle-49 | Playlists : Jingles
Wed 3:54pm | 0 | 1 | ghostface-killah---the-dogs-of-war | Playlists : Brand New

I very much think this could be caused by the rather slow HDD of my VPS, not to be quick enough to copy the next file to its tmp folder of liquidsoap.
Could be fixed by using a _length_ parameter in _request.dynamic_ function.

[length parameter](http://liquidsoap.fm/doc-1.3.0/request_sources.html)

**Comment by griffon56** [comment]
It looks like the issue is fixed, or very much reduced, when the crossover time is set to '0'. previous value was '1'.

**Comment by shaundewberry** [comment]
I am experiencing exactly the same problem with jingles in a "Once per X minutes" playlist playing twice in a row.

**Comment by derkalle4** [comment]
I also got the same problem. A shorter Jingle (a simple woosh) ~ 2 seconds is player 5 or 6 times before the next song loads. A ~10 sec jingle is played twice at worst case... but not everytime.

**Comment by ckeurk** [comment]
Hi I have the same problem...

**Comment by SlvrEagle23** [comment]
Hello all! I'm aware of this issue and will be pushing up a fix shortly to resolve it. Currently, I'm dealing with some underlying issues and infrastructural changes relating to cache files bloating in size, occasionally causing installations to show as "out of space" rather quickly.

**Comment by ckeurk** [comment]
Thank you again for the work you have done SlvrEagle23. You realize a really huge project, that's why I say thank you !!

**Comment by SlvrEagle23** [comment]
The latest commits should help significantly with this issue, ensuring that the same song only gets sent over to the AutoDJ once, while still allowing it to be cached for the now-playing API response. Try it out and let me know the results.

**Comment by griffon56** [comment]
Thanks for working on a fix.
Unfortunately since I updated the docker packages yesterday and today, I get the following errors

When trying to access http://IP/station/3 adress

![image](https://user-images.githubusercontent.com/25333002/28406590-7f56296a-6d31-11e7-9678-173e7ae1a86a.png)

The output of the station is now blank audio

When trying to access http://IP/station/3/util/restart

![image](https://user-images.githubusercontent.com/25333002/28406678-c9cfdb62-6d31-11e7-8c0f-8575529139ee.png)

**Comment by SlvrEagle23** [comment]
@griffon56 Did the update fail somewhere? The database errors should only occur if the database migration update didn't happen or the cache didn't flush properly.

As for the proxy errors, in your `app/env.ini` file, does it say your environment is "development"? If so, you can switch that to "production" and that should fix that.

**Comment by griffon56** [comment]
It didn't fail on the docker_update.sh script, only I get a HTTP timeout when it closes the azuracast_stations container (but can still update it). Also the clear cache always failes (cf [previous post](https://github.com/AzuraCast/AzuraCast/issues/183) on this )

I can still access http://IP/station/3/playlists and change the parameters. Strange behaviour is that it show '(Development) playlist ' on the tab title on Chrome. How to switch to production on docker installation ?

**Comment by shaundewberry** [comment]
When running update.sh I am receiving a similar permissions error. My app/env/ini is set to production.

`TASK [azuracast-update : Restart Radio Stations] *******************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/util/cli.php azuracast:radio:restart", "delta": "0:00:00.726477", "end": "2017-07-20 08:10:46.900596", "failed": true, "rc": 1, "start": "2017-07-20 08:10:46.174119", "stderr": "\n                                                                               \n  [Doctrine\\Common\\Proxy\\Exception\\UnexpectedValueException]                   \n  Your proxy directory \"/var/azuracast/www/app/models/Proxy\" must be writable  \n                                                                               \n\nazuracast:radio:restart", "stdout": "Restarting all radio stations...\n---------------------------------------------\nRestarting station #1: Metalwebsradio.com", "stdout_lines": ["Restarting all radio stations...", "---------------------------------------------", "Restarting station #1: Metalwebsradio.com"], "warnings": []}

RUNNING HANDLER [azuracast-cron : restart cron] ********************************
        to retry, use: --limit @/var/azuracast/www/util/ansible/update.retry

PLAY RECAP *********************************************************************
localhost                  : ok=63   changed=22   unreachable=0    failed=1`

**Comment by SlvrEagle23** [comment]
Latest update should resolve the proxy issue.

**Comment by shaundewberry** [comment]
Looks good now thanks.
Also, I can confirm the original Bug #186 seems to be resolved/lessened for me for "Once per x" playlists. I have not had any duplicate jingles since the update. NowPlaying still shows the appropriate metadata, so no impact there. Will keep monitoring.

**Comment by griffon56** [comment]
The proxy issue is indeed fixed and the audio is back.
But the SQL errors are still there, as the cache issue is still present. Still 'development' is shown on the chrome tab.

**Comment by derkalle4** [comment]
Same for me after updating some seconds ago @griffon56 .

**Comment by SlvrEagle23** [comment]
If anyone's still having any issues relating to this, please let me know. This thread got a little complicated and off-topic for a bit there, and I want to make sure that the actual issue (double playback of jingles and such) is resolved, as it should be from the latest code pushes.

**Comment by griffon56** [comment]
The update has fixed the multiple jingle playback. Great job @SlvrEagle23

**Comment by s0t0na666** [comment]
I think I was able to fix this: 

1. Edit Jingle Playlist 
2. Advanced tab ~ I assume you have "Only play one track at scheduled time" enabled, DISABLE it and SAVE. 
3. Re-enable the same option and save again. 

Didn't hear double jngl since, fingers crossed!

**Comment by BenMauriceKeil** [comment]
I have set everything up as usual, recently it doesn't matter if it's the stable or the rolling release version, the jingle always plays several times, once normally and then straight after that again at a quiet volume, or it plays it normally and then plays it another 10 times, or the second time it only plays half of the jingle, which is about 4 seconds, and then straight after that it plays the jingle again but only the last 3 seconds, really strange error, I have tried absolutely everything and don't know what to do anymore, I have already reset the server several times and reinstalled it several times, I urgently need help so that it works properly again and I can listen to the station normally again without interference.

https://github.com/AzuraCast/AzuraCast/issues/7371

**Comment by t0mtaylor** [comment]
@BenMauriceKeil see my fix here - you need to delete some volumes so they are re-created from the db data

https://github.com/AzuraCast/AzuraCast/issues/7162#issuecomment-2143803893
