### ISSUE TITLE
Docker install on Ubuntu Bionic gives cURL error

### ISSUE THREAD

**Issue by HannoSpreeuw** [AzuraCast/AzuraCast#2070]
**Using Docker installation method**

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
```[2019-10-16T16:12:04.333142+00:00] AzuraCast.NOTICE: HTTP client GET call to https://central.azuracast.com/ip produced response NULL [] []
In CurlFactory.php line 185:                                                                                                        
  cURL error 28: Resolving timed out after 3512 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)                                                                                                                      
azuracast:setup [--update] [--load-fixtures] [--release]
2019/10/16 16:12:04 Command exited with error: exit status 1
azuracast_stations is up-to-date
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_web_1 is up-to-date
```

**To Reproduce**
1. ./docker.sh install
2. See error

**Expected behavior**
No error

**Relevant Logs**
`docker-compose logs -f` does seem to show a running Azuracast:
```..........
web_1       | [2019-10-16T16:02:02.091731+00:00] AzuraCast.INFO: Running 1-minute sync task [] []
web_1       | [2019-10-16T16:02:02.092287+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
web_1       | [2019-10-16T16:02:17.078234+00:00] AzuraCast.INFO: Running Now Playing sync task [] []
```

**Device(s):**
Desktop
Version: unknown, not sure how to retrieve the version. It says: 
```
Installing azuracast/azuracast (dev-master d19e50a4956e49c941c4b8fd21b4bc47e9b60298)
```

**Comment by SlvrEagle23** [comment]
@HannoSpreeuw I'm not sure what it's trying to connect to, but this is usually an issue with DNS resolution on the server itself. You may need to look into it to make sure it has a properly configured outbound DNS resolver set up.

**Comment by HannoSpreeuw** [comment]
Thanks. But `lynx cnn.com` just gives the CNN website, so I have no clue what's wrong.
Are there any other tests I can do?

**Comment by SlvrEagle23** [comment]
@HannoSpreeuw The issue could be with connecting to `packagist.org` or with `github.com` on that machine. It could've also been temporary and resolved by now, so you may want to try it again in either case.

**Comment by HannoSpreeuw** [comment]
Hmmmm. `lynx packagist.org` and `lynx github.com` work, showing the websites.
The error persists.

**Comment by SlvrEagle23** [comment]
@HannoSpreeuw I'm almost certain that this is a DNS resolution issue isolated to your machine, as our normal demo instance and several other maintained installations aren't demonstrating the same error. You may want to check that those same domains work within a Docker container, as Docker may not be propagating the host's DNS resolution.

**Comment by HannoSpreeuw** [comment]
`lynx github.com` and `lynx packagist.org` from within a shell in the azuracast_redis_1 container work.

Same for the azuracast_mariadb_1 container.

Both, of course, after installing lynx on those containers.

**Comment by SlvrEagle23** [comment]
@HannoSpreeuw I don't have any further insight into what's causing your issue, then.

**Comment by HannoSpreeuw** [comment]
The Azuracast containers do not appear to have `dnsutils` installed, so you cannot even run `nslookup` from any container.

Could that be the issue?

**Comment by SlvrEagle23** [comment]
@HannoSpreeuw DNS resolution happens inside Docker containers regardless of whether the DNS utilities are installed. If you want to test things out, you can always install `dnsutils` into the container briefly by running the `web` container as root.

**Comment by HannoSpreeuw** [comment]
Thanks. After installing dnsutils in the container commands like `nslookup google.com` work well.
So that cannot explain the cURL error.

**Comment by HannoSpreeuw** [comment]
Solved. The /etc/resolv.conf of the host contained a local 192.168.xxx.yyy ip address that was not a nameserver.
That must have been inserted there during Ubuntu installation.
We removed that entry in /etc/resolv.conf although it says
```DO NOT EDIT THIS FILE BY HAND```

Somehow there was no fallback to the 8.8.8.8. Google name server.
