### ISSUE TITLE
Error in Latest Update

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#2188]
**Using Docker installation method**

NO
**Host Operating System**

Ubuntu 16.04
**Describe the bug**

After I update my Ansible AzuraCast installation with the latest update the login page not working anymore and i tried to update with update --full but i got this error. Anyone knows How to solve the issue?

**Relevant Logs**

TASK [services : Enable and restart all core services] *****************************************************************************************************************
changed: [localhost] => (item=influxdb)
changed: [localhost] => (item=mysql)
failed: [localhost] (item=php7.2-fpm) => {"ansible_loop_var": "item", "changed": false, "item": "php7.2-fpm", "msg": "Unable to start service php7.2-fpm: Failed to start php7.2-fpm.service: Unit php7.2-fpm.service is masked.\n"}
changed: [localhost] => (item=nginx)
changed: [localhost] => (item=redis)

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=66   changed=19   unreachable=0    failed=1    skipped=11   rescued=0    ignored=0

**Comment by SlvrEagle23** [comment]
@reans This should be fixed in the latest version. Thank you for the report!

**Comment by reans** [comment]
@SlvrEagle23 thank you but is still got this error and not fixed my problem.

TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] *************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/azuracast.php azuracast:setup --update", "delta": "0:00:00.321295", "end": "2019-12-02 07:27:55.958446", "msg": "non-zero return code", "rc": 1, "start": "2019-12-02 07:27:55.637151", "stderr": "\nIn Database.php line 103:\n                                       \n  Failed to created database stations  \n                                       \n\nIn Client.php line 196:\n                                                                               \n  Query has failed: cURL error 7: Failed to connect to localhost port 8086: C  \n  onnection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)   \n                                                                               \n\nIn CurlFactory.php line 200:\n                                                                               \n  cURL error 7: Failed to connect to localhost port 8086: Connection refused   \n  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)                     \n                                                                               \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["", "In Database.php line 103:", "                                       ", "  Failed to created database stations  ", "                                       ", "", "In Client.php line 196:", "                                                                               ", "  Query has failed: cURL error 7: Failed to connect to localhost port 8086: C  ", "  onnection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)   ", "                                                                               ", "", "In CurlFactory.php line 200:", "                                                                               ", "  cURL error 7: Failed to connect to localhost port 8086: Connection refused   ", "  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)                     ", "                                                                               ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n * Environment: Production\n * Installation Method: Ansible\n\n ! [NOTE] Running in update mode.                                               \n\nMigrating Legacy Configuration\n------------------------------\n\nConfiguration already set up.\n\nSetting Up InfluxDB\n-------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", " * Environment: Production", " * Installation Method: Ansible", "", " ! [NOTE] Running in update mode.                                               ", "", "Migrating Legacy Configuration", "------------------------------", "", "Configuration already set up.", "", "Setting Up InfluxDB", "-------------------"]}

RUNNING HANDLER [azuracast-cron : restart cron] ************************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=72   changed=24   unreachable=0    failed=1    skipped=12   rescued=0    ignored=0

**Comment by SlvrEagle23** [comment]
@reans That's a different error, one related to InfluxDB. You may want to try `service influxdb start`, then update again.

For your information, not only is our Ansible installation not officially supported, but running it on Ubuntu 16.04 is advised against, as it uses somewhat older base software than 18.04 and will be running out of support relatively soon (compared to 18.04, which will be supported for several more years).
