### ISSUE TITLE
Error when rescan songs "A new entity was found through the relationship "

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2207]
**Using Docker installation method**
 Yes

**Host Operating System**
 Ubuntu 18.04

**Describe the bug**

After upload bulk mp3 files to multiple stations, i tried to run 
the command "./docker.sh cli azuracast:media:reprocess" 
But after a few songs that were successfully scanned
i got many many lines of this:

> * A new entity was found through the relationship 'App\Entity\StationMedia#custom_fields' that was not configured
>    to cascade persist operations for entity: App\Entity\StationMediaCustomField@000000004f977cc900000000440ba1c0. To
>    solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade pers
>   ist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which e
>   ntity causes the problem implement 'App\Entity\StationMediaCustomField#__toString()' to get a clue.
>    * A new entity was found through the relationship 'App\Entity\StationMedia#custom_fields' that was not configured
>    to cascade persist operations for entity: App\Entity\StationMediaCustomField@000000004f977cca00000000440ba1c0. To
>    solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade pers
>   ist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which e
>   ntity causes the problem implement 'App\Entity\StationMediaCustomField#__toString()' to get a clue.
>    * A new entity was found through the relationship 'App\Entity\StationMedia#custom_fields' that was not configured
>    to cascade persist operations for entity: App\Entity\StationMediaCustomField@000000004f977ccb00000000440ba1c0. To
>    solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade pers
>   ist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which e
>   ntity causes the problem implement 'App\Entity\StationMediaCustomField#__toString()' to get a clue.

azuracast:media:reprocess

2019/12/09 20:07:07 Command exited with error: exit status 1

**Comment by SlvrEagle23** [comment]
@eranwo I've identified the possible cause of this problem...it should be fixed as of the latest update made just a few moments ago. Please update your installation and let me know if it helps with the issue.

**Comment by eranwo** [comment]
@SlvrEagle23 Seems that it did not solve the problem
Still getting errors when rescan `./docker.sh cli azuracast: media: reprocess`

   * A new entity was found through the relationship 'App\Entity\StationMedia
  #custom_fields' that was not configured to cascade persist operations for e
  ntity: App\Entity\StationMediaCustomField@000000006db7960b000000004246eb6c.
   To solve this issue: Either explicitly call EntityManager#persist() on thi
  s unknown entity or configure cascade persist this association in the mappi
  ng for example @ManyToOne(..,cascade={"persist"}). If you cannot find out w
  hich entity causes the problem implement 'App\Entity\StationMediaCustomFiel
  d#__toString()' to get a clue.
   * A new entity was found through the relationship 'App\Entity\StationMedia
  #custom_fields' that was not configured to cascade persist operations for e
  ntity: App\Entity\StationMediaCustomField@000000006db79608000000004246eb6c.
   To solve this issue: Either explicitly call EntityManager#persist() on thi
  s unknown entity or configure cascade persist this association in the mappi
  ng for example @ManyToOne(..,cascade={"persist"}). If you cannot find out w
  hich entity causes the problem implement 'App\Entity\StationMediaCustomFiel
  d#__toString()' to get a clue.
   * A new entity was found through the relationship 'App\Entity\StationMedia
  #custom_fields' that was not configured to cascade persist operations for e
  ntity: App\Entity\StationMediaCustomField@000000006db79600000000004246eb6c.
   To solve this issue: Either explicitly call EntityManager#persist() on thi
  s unknown entity or configure cascade persist this association in the mappi
  ng for example @ManyToOne(..,cascade={"persist"}). If you cannot find out w
  hich entity causes the problem implement 'App\Entity\StationMediaCustomFiel
  d#__toString()' to get a clue.
   * A new entity was found through the relationship 'App\Entity\StationMedia
  #custom_fields' that was not configured to cascade persist operations for e
  ntity: App\Entity\StationMediaCustomField@000000006db7960d000000004246eb6c.
   To solve this issue: Either explicitly call EntityManager#persist() on thi
  s unknown entity or configure cascade persist this association in the mappi
  ng for example @ManyToOne(..,cascade={"persist"}). If you cannot find out w
  hich entity causes the problem implement 'App\Entity\StationMediaCustomFiel
  d#__toString()' to get a clue.
   * A new entity was found through the relationship 'App\Entity\StationMedia
  #custom_fields' that was not configured to cascade persist operations for e
  ntity: App\Entity\StationMediaCustomField@000000006db79602000000004246eb6c.
   To solve this issue: Either explicitly call EntityManager#persist() on thi
  s unknown entity or configure cascade persist this association in the mappi
  ng for example @ManyToOne(..,cascade={"persist"}). If you cannot find out w
  hich entity causes the problem implement 'App\Entity\StationMediaCustomFiel
  d#__toString()' to get a clue.

**Comment by SlvrEagle23** [comment]
@eranwo Let's try again with the latest update. I think I've found another solution.

**Comment by eranwo** [comment]
@SlvrEagle23 Yes! the latest update works good .
**Question**: Is there a way to scan only a selected channel with this command?
Thank you!

**Comment by SlvrEagle23** [comment]
@eranwo Well, there wasn't, but it's such a simple addition and I see no reason not to add it, so it's added as of the latest version tonight. You can specify a station short-name as an optional argument.

Glad the latest updates fixed the issue.
