### ISSUE TITLE
Error cloning stations in latest release with switch to SFTP

### ISSUE THREAD

**Issue by AshleyinSpain** [AzuraCast/AzuraCast#2276]
**Using Docker installation method**

Yes, Docker method, latest build
**Host Operating System**

Ubuntu 18.04
**Describe the bug**

Error cloning station in latest release
500
A new entity was found through the relationship 'App\Entity\Station#SFTPUsers' that was not configured to cascade persist operations for entity: App\Entity\SFTPUser@0000000033f7acb6000000000a608275. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\SFTPUser#__toString()' to get a clue.
ORMInvalidArgumentException.php : 102
**To Reproduce**

1. Go to Administration > Manage Stations
2. From Actions select 'Clone' 
3. set any options dpesn't matter makes no difference
4. Click 'Create New Station'

Error received - see above

Could be to do with indididual or separate users per station do to with switch to SFTP

**Expected behavior**

Cloned station to be created
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

Hi Buster
Tried cloning new stations and it seems the switch to SFTP is causing problems do to with now needing separate users for each station
Could be wrong
Regards
Ashley

**Comment by SlvrEagle23** [comment]
@AshleyinSpain Thank you for the report. This should be fixed as of the latest update.

**Comment by AshleyinSpain** [comment]
@SlvrEagle23 After v0.9.8.1 update error still occurs
https://jmp.sh/RkmrNqg
Still cannot clone stations
Regards
Ashley

**Comment by SlvrEagle23** [comment]
@AshleyinSpain Should be fixed now. Only fixed one side of the arrangement before, didn't fix the other.

**Comment by AshleyinSpain** [comment]
@SlvrEagle23 OK, tested, super, I can clone stations now - But, when I create a new SFTP user it only allows 8 characters for the username can you increase that

On another point if I try to create a SFTP user with same username as an existing one for another station it doesn't allow duplicates - would it not be possible to add an existing user to another station - well I realise anything is possible in programming but you know what I mean, either relatively easily as part of the current switch to SFTP or a larger job that say should be added as a feature request - I'm likely to have c. 100 stations all for the same client

I know that a number of AC users were reselling and had a problem with clients seeing each other's stations with the old ftp method
But I am not reselling, I only have one 'client' for my AC install and I now have a problem with not seeing all the stations at the same time while using the new SFTP - going to have to keep track of many usernames and passwords one for each station or music channel as they are for me
You can never please all the people all the time haha

**Comment by SlvrEagle23** [comment]
@AshleyinSpain You make a valid point about the 8-character limit...this is a very old *nix limitation that really doesn't apply these days. Nowadays, the limit is more often 32 characters, which I consider a reasonable amount of space to allow you to create suitably unique usernames. I've updated the codebase to support 32 characters instead.
