### ISSUE TITLE
SHOUTcast error: Directory returned error code: 0

### ISSUE THREAD

**Issue by FLAME878** [AzuraCast/AzuraCast#2400]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04 LTS

**Describe the bug**
On the Shoutcast Server Administration page, it shows Status: Directory returned error code: 0. Also on the SHOUTcast logs it says Error: Malformed UTF-8 characters, possibly incorrectly encoded.

**To Reproduce**
(logs)
1. Go to SHOUTcast logs
2. It shows Error: Malformed UTF-8 characters, possibly incorrectly encoded

(server admin)
1. Go to admin page and it shows Directory returned error code: 0

**Expected behavior**

It's supposed to show that the station is listed and has a station ID.

**Relevant Logs**

`[0m2020-02-09 10:06:01	INFO	[ADMINCGI sid=1] Title updated [Y2K & bbno$ - Lalala]
[0;32m2020-02-09 10:06:04	DEBUG	[METRICS sid=1] push to YP requested "KYLE - F You I Love You (feat. Teyana Taylor)"
[0m2020-02-09 10:06:04	INFO	[ADMINCGI sid=1] Title updated [KYLE - F You I Love You (feat. Teyana Taylor)]
[01;33m2020-02-09 10:06:07	WARN	[YP sid=1] response returned 500, NOK
[0m[0;32m2020-02-09 10:09:58	DEBUG	[METRICS sid=1] push to YP requested "Camila Cabello - My Oh My (feat. DaBaby)"
[0m2020-02-09 10:09:58	INFO	[ADMINCGI sid=1] Title updated [Camila Cabello - My Oh My (feat. DaBaby)]
[01;33m2020-02-09 10:10:01	WARN	[YP sid=1] response returned 500, NOK
[0m`
[shoutcast.log](https://github.com/AzuraCast/AzuraCast/files/4177806/shoutcast.log)

**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/52174090/74112815-d6245080-4b5c-11ea-863f-c4531e0ee536.png)
![Screenshot_2](https://user-images.githubusercontent.com/52174090/74112825-ec321100-4b5c-11ea-91db-4c1ad07b0526.png)

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: ?

**Additional context**

This only happens a few times for some reason it lists after a few restarts but then goes back to this error and isn't listed. I looked up this error and found a similar article but I'm not really experienced with Linux so I don't know very much about the CMD line.

**Comment by SC2Mitch** [comment]
The UTF thing was fixed in https://github.com/AzuraCast/AzuraCast/commit/762e0a7c8497753afde5e4cd2fa9c71c62e4d458 but do the songs in question the` 0;32m2020-02-09 10:09:58 DEBUG [METRICS sid=1] push to YP requested "Camila Cabello - My Oh My (feat. DaBaby)" �` have any emojis in them?

**Comment by FLAME878** [comment]
@SC2Mitch The song doesn't have any emojis, looking at the log file with Notepad ++ it shows ESC in black

**Comment by FLAME878** [comment]
Just updated my AzuraCast installation, I don't see the UTF issue but it still shows the WARN	[YP sid=1] response returned 500, NOK
![Screenshot_3](https://user-images.githubusercontent.com/52174090/74112933-00c2d900-4b5e-11ea-9f68-b15872710a6c.png)

**Comment by FLAME878** [comment]
Quick update, it is now showing that it is listed but when searching on the SHOUTcast directory it isn't there.

**Comment by FLAME878** [comment]
Started doing the same thing again with the directory returned error code: 0, it seems to be very random if it does it list it and if it doesn't. Anybody else experiencing this issue?
![Screenshot_2](https://user-images.githubusercontent.com/52174090/74210584-79529400-4c49-11ea-9d9a-40f929e37b52.png)
