### ISSUE TITLE
Azuracast Panel media-Error

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#290]
Hi,

A few weeks ago i installed AzuraCast on my server everything was working very well, but yesterday i installed the newest azuracast version on a server but now the media-page buggs.

Usually the text on this page is: No-media files.
![image](https://user-images.githubusercontent.com/29834979/33090150-4b10a314-cef3-11e7-8c01-768f1004533b.png)

But sometimes after a couple of times reloading the page works...

If the page doesn't work correct the Google-DevTools Console displays the following: 
![image](https://user-images.githubusercontent.com/29834979/33090232-865ae524-cef3-11e7-8ea5-8d02884194ba.png)

**Comment by SlvrEagle23** [comment]
@RemBdev If you go to the network inspector tab of the DevTools console, does that call actually return a detailed error message in its response? The full exception details should be included in the "Response" of that 500 error.

**Comment by RemBdev** [comment]
![image](https://user-images.githubusercontent.com/29834979/33117421-b6ecc2dc-cf68-11e7-894f-5ef32d9b2cce.png)

![image](https://user-images.githubusercontent.com/29834979/33117476-e2d59392-cf68-11e7-9aa8-7ccb1201c404.png)

**Comment by StreamDude** [comment]
Hi,

This morning i've uploaded about 300 files to the MediaManager and after that i have the same isseu as @RemBdev My whole Media Library is empty?! The station plays as normal but i can't manage my files in the mediamanager because there is nothing there. I'm not familiar with the DevTools console so i can't place the errors here, sorry for that.

**Comment by SlvrEagle23** [comment]
@RemBdev @StreamDude If you're using docker, can you run, in the command line from the main AzuraCast root:
```
docker-compose logs -f web
```

Then try to access the media page? If an error pops up, I need to know what the text of that error is to be able to debug it further, since I'm not seeing this error on my end.

**Comment by StreamDude** [comment]
@SlvrEagle23 I'm running AzuraCast on Ubuntu Server 16.04.3 LTS
If you can tell me what I can do check the errors on Ubuntu, I'll let you know the output.

**Comment by SlvrEagle23** [comment]
You should be able to do the same with:
```
tail -f /var/azuracast/www_tmp/php_errors.log
```
then access the page in question.

**Comment by RemBdev** [comment]
![image](https://user-images.githubusercontent.com/29834979/33186544-9639280a-d08a-11e7-8b4a-86b8a9fb5f43.png)
(Ubuntu)

**Comment by StreamDude** [comment]
Here's my output

[23-Nov-2017 15:40:16 Europe/Amsterdam] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 442368 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105
[23-Nov-2017 15:45:03 Europe/Berlin] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 421888 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 122
[23-Nov-2017 15:45:16 Europe/Berlin] PHP Fatal error:  Uncaught App\Exception\Bootstrap: Redis server went away in /var/azuracast/www/app/bootstrap/services.php:123
Stack trace:
#0 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Slim\Container))
#1 /var/azuracast/www/util/cli.php(11): Pimple\Container->offsetGet('em')
#2 {main}
  thrown in /var/azuracast/www/app/bootstrap/services.php on line 123
[23-Nov-2017 23:25:05 Europe/Berlin] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 421888 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 122
[23-Nov-2017 23:25:12 Europe/Amsterdam] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 184320 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105
[23-Nov-2017 23:26:35 Europe/Amsterdam] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 184320 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105
[23-Nov-2017 23:26:41 Europe/Amsterdam] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 249856 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105

When I load the media page, there's no error.

**Comment by SlvrEagle23** [comment]
@StreamDude @RemBdev I have pushed out a fix for this issue that should dramatically improve the memory usage when using the media manager page, which should resolve these issues. Try out the updated code and let me know if you encounter any further issues.

**Comment by RemBdev** [comment]
After only replacing /var/azuracast/www/app/modules/stations/controllers/FileController.php with the new one from github (So not a complete update) it works!

You are the best, thanks for the very nice Azuracast and the amazing good support! :)

**Comment by StreamDude** [comment]
After running the update my libs are back :-) Thank you very much for the good support !

**Comment by StreamDude** [comment]
@SlvrEagle23  
Sorry to bother you, I thought all was running smooth after the update but I still encounter some problems :( The problem with my libs is fixed, but when I want to make changes to the station in the profile settings page and restart, then I get white screens and nothing happens, not even if I refresh the page a few times. I also tried another browser but that doesn't help either.

Here is some of the output:
[24-Nov-2017 13:38:01 Europe/Amsterdam] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 491520 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105
[24-Nov-2017 13:46:40 Europe/Amsterdam] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 151552 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 122
[24-Nov-2017 13:50:04 Europe/Berlin] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 278528 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/BlobType.php on line 50

**Comment by SlvrEagle23** [comment]
@StreamDude I have pushed up a database update that should significantly resolve the memory consumption issues on the system. Run the update script normally and these memory allocation errors should be resolved.

**Comment by StreamDude** [comment]
@SlvrEagle23 
I've done the update but still have the same error...I can't restart the station after a profile change.

Under **Utilities**, "**Restart broadcasting**" gives me a white screen and under **Reports** "**Song listener impact**" gives me a white screen as well. You mentioned in another post that it could be the amount of files and the Artis Covers that might cause the problems. I have 700 tracks in the database and they do all have Artist Covers included.

[24-Nov-2017 20:45:06 Europe/Berlin] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 491520 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105
[24-Nov-2017 20:47:54 Europe/Amsterdam] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 274432 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105

Thank you for the quick updates and responses, it's weekend now so take your time.

**Comment by StreamDude** [comment]
@SlvrEagle23 @RemBdev 
Yesterday I made a fresh new install on Ubuntu server but AzuraCast keeps giving me errors.

#0 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Slim\Container))
#1 /var/azuracast/www/util/cli.php(11): Pimple\Container->offsetGet('em')
#2 {main}
  thrown in /var/azuracast/www/app/bootstrap/services.php on line 123
[26-Nov-2017 21:00:47 Europe/Berlin] PHP Fatal error:  Uncaught App\Exception\Bootstrap: Redis server went away in /var/azuracast/www/app/bootstrap/services.php:123
Stack trace:
#0 /var/azuracast/www/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Slim\Container))
#1 /var/azuracast/www/util/cli.php(11): Pimple\Container->offsetGet('em')
#2 {main}
  thrown in /var/azuracast/www/app/bootstrap/services.php on line 123

At the moment when I want to import music to the media folder I have the problem that many files are not being processed.
