### ISSUE TITLE
now playing error on 2 of the 3 stations

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#3042]
Unbuntu 18.04
Ansible installation
VPS only runs azuracast: Dual core cpu with 4gb of ram

Ive updated to the latest version and now I have a problem with 2 stations, I cannot longer see current song or next song, the music is playing fine, and in Winamp I see the song artist and title fine, but on the public page is says stream offline.

Error when I do now playing run task

NowPlaying adapter error: Invalid response: {"icestats":{"admin":"icemaster@localhost","banned_IPs":0,"build":20200514004959,"host":"85.214.246.7","location":"AzuraCast","outgoing_kbitrate":447,"server_id":"Icecast 2.4.0-kh13","server_start":"18/Jul/2020:13:49:03 +0200","stream_kbytes_read":11698,"stream_kbytes_sent":19019}}

Liquidsoap log no problems there.
Icecast log I see:
[2020-07-18  13:49:07] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/server.crt (system lib)
[2020-07-18  13:49:07] WARN slave/slave_startup process has 4096 max file descriptor limit

Greets
Roy

**Comment by suricloud** [comment]
I also do get the same with the latest update:

2020-07-20  13:41:58] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-20  13:42:38] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-20  13:56:02] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-20  14:00:04] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-20  14:00:19] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-20  21:45:31] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-21  08:34:44] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-21  11:55:24] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-21  22:19:19] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-21  22:22:23] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-21  22:22:42] WARN slave/slave_startup process has 65536 max file descriptor limit
[2020-07-21  23:11:23] WARN slave/slave_startup process has 65536 max file descriptor limit

**Comment by Thijmen** [comment]
Same problem here:
2020-07-22  12:54:36] WARN slave/slave_startup process has 65536 max file descriptor limit

**Comment by AmsterdamFM** [comment]
same here

```
[2020-07-06  11:37:07] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/ssl.crt (system lib)
.....
[2020-08-18  11:11:14] WARN slave/slave_startup process has 65536 max file descriptor limit
```
And

```
Info
Running Now Playing sync task
Debug
AutoDJ queue is already at current max length (25).
Debug
Timer "BuildQueue" completed in 0.036 second(s).
Debug
HTTP client GET call to https://website/status-json.xsl produced response 200
Error
NowPlaying adapter error: Syntax error


```

**Comment by SlvrEagle23** [comment]
@AmsterdamFM I'd be curious to see what the actual return of `/status-json.xsl` is on that stream. It's possible there's a parse error happening.

**Comment by SlvrEagle23** [comment]
@AmsterdamFM These lines:

```
,"title": - ,"yp_currently_playing": - }
```

...definitely aren't valid JSON. It definitely shouldn't be returning that, but if it is, we may need to implement some sort of JSON "cleanup" function.

**Comment by AmsterdamFM** [comment]
@SlvrEagle23 

Good you have found out why stream shows off-line!

Could this be a bug in Icecast 2.4.4? Or is this a wrong setting with our stream provider?

**Comment by stemvantwente** [comment]
@SlvrEagle23 Did you find out why this happens?

**Comment by SlvrEagle23** [comment]
@AmsterdamFM This definitely seems like a bug in Icecast, because we don't have this same issue in our KH branch that we ship with AzuraCast.

**Comment by AmsterdamFM** [comment]
Found an easy fix! Others have found this bug too:

https://stackoverflow.com/questions/30269678/icecast-json-status-xls-not-valid-json-answer-with-blank-song-title

`$json = str_replace( '"title": -', '"title": null', $json );`

to replace "title": - to "title": null before you use json_decode()

**Comment by SlvrEagle23** [comment]
@AmsterdamFM Should be fixed as of the latest update.

**Comment by AmsterdamFM** [comment]
@SlvrEagle23 Unfortunately exactly the same problem. So station now playing shows off line. Public player does not work. But the stream itself just plays fine.

I am on: AzuraCast • v0.10.3, #e60c2bc (2020-09-09 4:06) Rolling • Docker • PHP 7.4

But two days ago something strange happened: On updating when downloading the images gave an error. Only one succeeded i think. web?  the rest of the update proceeded normally. And then for the next few times there was no error downloading or updating but the dashboard showed there are updates despite just having done the update. This problem now has gone. But the some of the docker images might still be old?

I think the update script should stop after not being able to download the docker images. This prevents problems.

**Comment by stemvantwente** [comment]
Hi @SlvrEagle23 

Tryed update to newest version today but if I do that I still get stream offline.

![stillstream offline](https://user-images.githubusercontent.com/44572433/93030109-de77c900-f620-11ea-964f-1207e9482610.png)

**Comment by SlvrEagle23** [comment]
@AmsterdamFM @stemvantwente In both of your cases, I would need the debug output from running the "Now Playing" sync task; you can do so via the System Administration page at the lowest part of the screen. It is very possible that we're simply processing the output we're getting from Icecast/SHOUTcast correctly, but the response itself is incorrect (or isn't loading for whatever reason, which the debug process will show).

**Comment by stemvantwente** [comment]
@SlvrEagle23 

When I do the Now Playing task I get

NowPlaying adapter error: Invalid response: {"icestats":{"admin":"icemaster@localhost","banned_IPs":0,"build":20200514004959,"host":"85.214.246.7","location":"AzuraCast","outgoing_kbitrate":447,"server_id":"Icecast 2.4.0-kh13","server_start":"14/sep/2020:13:49:03 +0200","stream_kbytes_read":11698,"stream_kbytes_sent":19019}}

**Comment by AmsterdamFM** [comment]
@SlvrEagle23 

I did a bit of research and **yp_currently_playing** found in my /status-json.xsl looks like a Shoutcast variable.

I am still getting the exact same (syntax) error running the Now Playing task.  

```
Info
Running sync task: Now Playing Data
Debug
Got currently playing song. Using start time and duration for initial value of now.
song
"divas corrybrokken 2"
started
"2020-09-13 14:57:03"
duration
3428
station
{
    "id": 1,
    "name": "AmsterdamFM"
}
Debug
AutoDJ queue is already at current max length (25).
Debug
Timer "BuildQueue" completed in 0.025 second(s).
Debug
HTTP client GET call to https://mcp-2.example.nl:8093/status-json.xsl produced response 200
Error
NowPlaying adapter error: Syntax error
```

**Comment by SlvrEagle23** [comment]
> @SlvrEagle23
> 
> When I do the Now Playing task I get
> 
> NowPlaying adapter error: Invalid response: {"icestats":{"admin":"icemaster@localhost","banned_IPs":0,"build":20200514004959,"host":"85.214.246.7","location":"AzuraCast","outgoing_kbitrate":447,"server_id":"Icecast 2.4.0-kh13","server_start":"14/sep/2020:11:25:03 +0200","stream_kbytes_read":11698,"stream_kbytes_sent":19019}}

The response here suggests that Icecast has no metadata for the specific stream. What is the name of your mount point on your station? There may be an issue with the mount point name mismatching the one it's trying to pull for its data feed.

**Comment by stemvantwente** [comment]
@SlvrEagle23 I found the problem, when I use <hidden>1</hidden> in my config I get that error, but I like tho hide the icecast streams, any suggrestion how to fix this?

Greets

**Comment by SlvrEagle23** [comment]
@stemvantwente Ahhh yes, well the problem there is that it is hidden even from the AzuraCast library.

This is an improvement we should be making to how we handle Icecast statistics via our NowPlaying library; if an administrator password is provided (as it is with all internal AzuraCast connections) we should be able to pull a "now playing" feed regardless.

**Comment by SlvrEagle23** [comment]
@stemvantwente I've investigated, and it turns out we _do_ already do this...we try to check the administrator stats panel first before looking at the public JSON feed, which would be hidden in your station's case.

There are some logging improvements we can make in this regard to help track down issues, and I'll be working on that.

**Comment by SlvrEagle23** [comment]
@stemvantwente After further investigation, I discovered that the Nowplaying library would _never_ use the preferred administrator-sourced XML feed due to a bug in the code. This bug is now fixed as of the latest update, and that should also resolve the issues reported here.

**Comment by stemvantwente** [comment]
@SlvrEagle23 I will update tonight and see if it works, thank you for the fast response!

**Comment by stemvantwente** [comment]
@SlvrEagle23 
< hidden >1< /hidden > works again! thank you! all seems fine now

**Comment by AmsterdamFM** [comment]
Here it's solved too! Thank you!
