### ISSUE TITLE
Medium Sync doesn't run if 'file not found at path' 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3221]
**Using Docker installation method**

**AzuraCast version**
ac0dc6e (2020-09-29 - 16:59) 
**Host Operating System**
Ubuntu 20.04 

**Describe the bug**
Added in the https://github.com/AzuraCast/AzuraCast/commit/ac0dc6e41c33d26036355bee3490adc38a2c0f6c update, from my understanding this should 'clean up' missing file paths, but it does not, resulting in sync errors. 

**To Reproduce**
Upload some music, delete the said music and consult the 5 minute (Medium Sync) for logs, Docker Logs are also helpful in this case. 

**Expected behavior**
It should clean up the missing file and or discard it completely, finishing the sync test. 
**Relevant Logs**
```
web_1                      | In Filesystem.php line 389:
web_1                      |
web_1                      |   File not found at path: 5db1f3cd22c4fda43947f267.jpg
web_1                      |
web_1                      |
web_1                      | sync:run [<task>]
```

Unsure if related:
```
web_1                      | In Connection.php line 305:
web_1                      |
web_1                      |   NOGROUP No such key 'messages_media' or consumer group 'symfony' in XREADGR
web_1                      |   OUP with GROUP option
web_1                      |
web_1                      |
web_1                      | queue:process [<runtime>]
```
**Screenshots**
https://i.imgur.com/uuITflz.png 

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Both issues should be fixed as of latest update.

**Comment by SC2Mitch** [comment]
Issue still happens with a completely new file name now. 
![image](https://user-images.githubusercontent.com/29955942/94689241-89c59500-0326-11eb-8e88-e382b3c34063.png)

**Comment by SC2Mitch** [comment]
I believe I found the issue actually, when deleting a file from a directory, Azuracast returns a this: 
```
The request could not be processed.
Array: File not found at path: 5db1f3cd22c4fda43947f267.jpg
```
This might be helpful for locating the root issue.

**Comment by SlvrEagle23** [comment]
@SC2Mitch Fixed in another location, that should knock it out.

**Comment by SC2Mitch** [comment]
All fixed, thank you for the rapid fixes!
