### ISSUE TITLE
WEBHOOK Trigger does'nt work anymore

### ISSUE THREAD

**Issue by TheRealMakkus** [AzuraCast/AzuraCast#3314]
**Using Docker installation method**
YES

**AzuraCast version**
Rolling Release #bc307d2 (2020-10-21 12:52) 

**Host Operating System**
Debian 9.13

**Describe the bug**
Since update to this version, webhook isnt working anymore. Using the TEST-Button works.

**To Reproduce**
Webhooks > Generic Webhook > configure > trigger: new song > let it run > nothing happens
Using TEST-Button > works.

**Comment by SlvrEagle23** [comment]
@TheRealMakkus This should be fixed as of the latest PR from @Vaalyn.

**Comment by pierluigi** [comment]
`AzuraCast • v0.11.1, #854dd51 (2020-06-01 10:03) • Ansible • PHP 7.4`

I am still having this issue (webhooks not being triggered, but clicking on Test works fine)

**Comment by Vaalyn** [comment]
> `AzuraCast • v0.11.1, #854dd51 (2020-06-01 10:03) • Ansible • PHP 7.4`
> 
> I am still having this issue (webhooks not being triggered, but clicking on Test works fine)

You can't be on v0.11.1 with the commit hash `#854dd51` from `2020-06-01` since `v0.11.1` was released on `2020-12-07`.
Please update to the current stable version.

**Comment by pierluigi** [comment]
Hi @Vaalyn  – this is indeed what the footer says:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/1078545/101726650-ea730a00-3aed-11eb-8383-aedf57f50d82.png">


I tried running `update.sh` again, rebooting my raspi,  however that didn't seem to change the reported version. Here's the output

```

sudo ./update.sh
Checking for Ansible: install ok installed
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:2 http://ppa.launchpad.net/chris-needham/ppa/ubuntu focal InRelease
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
Get:4 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease [23.9 kB]
Ign:5 https://apt.fury.io/caddy  InRelease
Get:6 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [101 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [109 kB]
Ign:8 https://apt.fury.io/caddy  Release
Ign:9 https://apt.fury.io/caddy  Packages
Ign:10 https://apt.fury.io/caddy  Translation-en
Get:9 https://apt.fury.io/caddy  Packages
Get:11 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main arm64 Packages [73.3 kB]
Ign:10 https://apt.fury.io/caddy  Translation-en
Get:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 Packages [571 kB]
Ign:10 https://apt.fury.io/caddy  Translation-en
Get:13 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 Packages [653 kB]
Ign:10 https://apt.fury.io/caddy  Translation-en
Ign:10 https://apt.fury.io/caddy  Translation-en
Ign:10 https://apt.fury.io/caddy  Translation-en
Ign:10 https://apt.fury.io/caddy  Translation-en
Fetched 1648 kB in 5s (337 kB/s)
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
Package python-mysqldb is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-mysqldb' has no installation candidate
Updating AzuraCast (Environment: production, Update revision: 53)
Updating to the latest rolling-release version...
Tip: use the '--release' flag to update to tagged releases only.
HEAD is now at 854dd513c #2912 -- Don't remove web volume in latest update.
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 118 (delta 51), reused 95 (delta 28), pack-reused 0
Receiving objects: 100% (118/118), 164.24 KiB | 490.00 KiB/s, done.
Resolving deltas: 100% (51/51), done.
From https://github.com/AzuraCast/AzuraCast
   d5bab2390..5e62a1bcb  master     -> origin/master
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>


PLAY [all] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [init : debug] ************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "Running Ansible on localhost with OS Ubuntu focal 20.04 aarch64 (production)"
}

TASK [init : fail] *************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [init : fail] *************************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [init : Add multiverse repository] ****************************************************************************************************************************************************************************
skipping: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu focal multiverse)
skipping: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  focal multiverse)
skipping: [localhost] => (item=deb http://archive.ubuntu.com/ubuntu focal-updates multiverse)
skipping: [localhost] => (item=deb-src http://archive.ubuntu.com/ubuntu/  focal-updates multiverse)

TASK [init : Update apt] *******************************************************************************************************************************************************************************************
changed: [localhost]

TASK [init : Install system packages] ******************************************************************************************************************************************************************************
changed: [localhost]

TASK [init : Install Focal Packages (20.04)] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [init : Install Bionic Packages (18.04 only)] *****************************************************************************************************************************************************************
skipping: [localhost]

TASK [init : Install Xenial Packages (16.04 only)] *****************************************************************************************************************************************************************
skipping: [localhost]

TASK [init : Update pip components] ********************************************************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Write environment configuration file] *****************************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Set up environment file] ******************************************************************************************************************************************************************
ok: [localhost]

TASK [azuracast-config : Set Permissions on Base App Folder] *******************************************************************************************************************************************************
ok: [localhost] => (item=/var/azuracast)

TASK [azuracast-config : Clear temp directory] *********************************************************************************************************************************************************************
changed: [localhost]

TASK [azuracast-config : Create System Folders] ********************************************************************************************************************************************************************
changed: [localhost] => (item=/var/azuracast/www_tmp)
changed: [localhost] => (item=/var/azuracast/www_tmp/proxies)
ok: [localhost] => (item=/var/azuracast/stations)
ok: [localhost] => (item=/var/azuracast/geoip)
ok: [localhost] => (item=/var/azuracast/dbip)
ok: [localhost] => (item=/var/azuracast/backups)
ok: [localhost] => (item=/var/azuracast/servers)
ok: [localhost] => (item=/var/azuracast/servers/shoutcast2)
ok: [localhost] => (item=/var/azuracast/servers/icecast2)

TASK [azuracast-radio : Install IceCast-KH-AC Dependencies] ********************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Download IceCast-KH-AC Source] *************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Extract IceCast-KH-AC Source] **************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Build IceCast-KH-AC] ***********************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Clear OPAM directory] **********************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Add OPAM/OCaml Repository] *****************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Install Liquidsoap Dependencies] ***********************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Initialize OPAM - This takes a while...] ***************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Initialize OPAM (Focal)] *******************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Build and Install Liquidsoap] **************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Link Liquidsoap binary (Xenial/Bionic)] ****************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Link Liquidsoap binary (Focal)] ************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Add Audiowaveform PPA] *********************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-radio : Install Audiowaveform] *********************************************************************************************************************************************************************
skipping: [localhost]

TASK [supervisord : Install supervisord from repo] *****************************************************************************************************************************************************************
skipping: [localhost]

TASK [supervisord : Change supervisord configuration] **************************************************************************************************************************************************************
skipping: [localhost]

TASK [supervisord : Remove old core supervisord configuration] *****************************************************************************************************************************************************
skipping: [localhost]

TASK [supervisord : Kill legacy radio processes (if upgrading from older version)] *********************************************************************************************************************************
skipping: [localhost]

TASK [supervisord : Trigger manual restart of supervisord (if not already running)] ********************************************************************************************************************************
skipping: [localhost]

TASK [mariadb : Add MariaDB Repository (Xenial/Bionic)] ************************************************************************************************************************************************************
skipping: [localhost]

TASK [mariadb : Add repo key (Xenial)] *****************************************************************************************************************************************************************************
skipping: [localhost]

TASK [mariadb : Add repo key (Bionic)] *****************************************************************************************************************************************************************************
skipping: [localhost]

TASK [mariadb : Update apt cache] **********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [mariadb : Unattended package installation] *******************************************************************************************************************************************************************
skipping: [localhost]

TASK [mariadb : Install MariaDB] ***********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [mariadb : Start and enable service] **************************************************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Uninstall web server packages that may conflict with nginx] ******************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Unhold nginx-related packages for updates] ***********************************************************************************************************************************************************
skipping: [localhost] => (item=nginx)
skipping: [localhost] => (item=nginx-common)
skipping: [localhost] => (item=nginx-extras)

TASK [nginx : Remove any older nginx] ******************************************************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Install nginx] ***************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Create nginx ssl directory] **************************************************************************************************************************************************************************
skipping: [localhost] => (item=/etc/nginx/ssl)

TASK [nginx : Create self-signed SSL cert] *************************************************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Remove default nginx site symlink] *******************************************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Add nginx global config] *****************************************************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Add app-specific nginx site] *************************************************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Link app-specific nginx site] ************************************************************************************************************************************************************************
skipping: [localhost]

TASK [nginx : Turn sendfile off on nginx for local development] ****************************************************************************************************************************************************
skipping: [localhost]

TASK [redis : Install Redis] ***************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [redis : Restart Redis service] *******************************************************************************************************************************************************************************
skipping: [localhost]

TASK [php : Add PHP PPA repository] ********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [php : Remove Old PHP Libraries] ******************************************************************************************************************************************************************************
skipping: [localhost]

TASK [php : Install PHP 7.4] ***************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [php : Configure PHP FPM Pool] ********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [php : Configure php-fpm php.ini] *****************************************************************************************************************************************************************************
skipping: [localhost] => (item={'option': 'post_max_size', 'value': '50M'})
skipping: [localhost] => (item={'option': 'short_open_tag', 'value': 'On'})
skipping: [localhost] => (item={'option': 'upload_max_filesize', 'value': '50M'})

TASK [php : Configure php-cli php.ini] *****************************************************************************************************************************************************************************
skipping: [localhost] => (item={'option': 'short_open_tag', 'value': 'On'})

TASK [composer : Install Composer] *********************************************************************************************************************************************************************************
ok: [localhost]

TASK [composer : Ensure vendor folder exists] **********************************************************************************************************************************************************************
ok: [localhost] => (item=/var/azuracast/www/vendor)

TASK [composer : Install Composer Dependencies (Development)] ******************************************************************************************************************************************************
skipping: [localhost]

TASK [composer : Install Composer Dependencies (Production)] *******************************************************************************************************************************************************
changed: [localhost]

TASK [influxdb : Add InfluxDB repo file] ***************************************************************************************************************************************************************************
skipping: [localhost]

TASK [influxdb : Add InfluxDB repo key] ****************************************************************************************************************************************************************************
skipping: [localhost]

TASK [influxdb : Update apt cache] *********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [influxdb : Install InfluxDB] *********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [influxdb : Fix permissions on InfluxDB data folder] **********************************************************************************************************************************************************
skipping: [localhost]

TASK [influxdb : Lock down InfluxDB to localhost requests] *********************************************************************************************************************************************************
skipping: [localhost]

TASK [influxdb : Start the InfluxDB service] ***********************************************************************************************************************************************************************
skipping: [localhost]

TASK [influxdb : Pause to allow InfluxDB to spin up] ***************************************************************************************************************************************************************
skipping: [localhost]

TASK [ufw : Install UFW Firewall] **********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [ufw : UFW - Disable all other incoming by default] ***********************************************************************************************************************************************************
skipping: [localhost]

TASK [ufw : UFW - Allow all other outgoing by default] *************************************************************************************************************************************************************
skipping: [localhost]

TASK [ufw : UFW - Enable AzuraCast TCP Ports] **********************************************************************************************************************************************************************
skipping: [localhost] => (item=80)
skipping: [localhost] => (item=443)
skipping: [localhost] => (item=8000:8999)

TASK [ufw : UFW - Enable SSH] **************************************************************************************************************************************************************************************
skipping: [localhost]

TASK [ufw : UFW - Turn on Firewall] ********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [dbip : Download DBIP Database] *******************************************************************************************************************************************************************************
skipping: [localhost]

TASK [dbip : Extract DBIP Database] ********************************************************************************************************************************************************************************
skipping: [localhost]

TASK [dbip : Set DBIP Database Permissions] ************************************************************************************************************************************************************************
skipping: [localhost]

TASK [services : Enable and restart all core services] *************************************************************************************************************************************************************
skipping: [localhost] => (item=influxdb)
skipping: [localhost] => (item=mysql)
skipping: [localhost] => (item=php7.4-fpm)
skipping: [localhost] => (item=nginx)
skipping: [localhost] => (item=redis)

TASK [services : Pause to allow InfluxDB to spin up] ***************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-cron : Install cron-related packages] **************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-cron : Generate Cron Template] *********************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-cron : Install Cron file] **************************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-cron : Clean up temp Cron file] ********************************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-setup : Ensure update script continues to be executable] *******************************************************************************************************************************************
changed: [localhost] => (item=/var/azuracast/www/update.sh)
changed: [localhost] => (item=/var/azuracast/www/bin/console)

TASK [azuracast-setup : Run AzuraCast Setup (Install Mode)] ********************************************************************************************************************************************************
skipping: [localhost]

TASK [azuracast-setup : Run AzuraCast Setup (Update Mode)] *********************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=16   changed=7    unreachable=0    failed=0    skipped=75   rescued=0    ignored=0

```

**Comment by pierluigi** [comment]
Looks like the master branch was `dirty`(something changed `bin/console`). Stashing changes and re-running the update again seems to have done it! Thanks

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1078545/101727705-f65fcb80-3aef-11eb-8f8d-477d673118bd.png">
