### ISSUE TITLE
Cloning a station ends up in 500 (ORM: recording_storage_location)

### ISSUE THREAD

**Issue by xewl** [AzuraCast/AzuraCast#3501]
**Using Docker installation method**
Yes

**AzuraCast version**
0.11 Stable

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
When cloning an existing station, the action fails into a 500 error. (see "relevant logs")

**To Reproduce**
- Create a station
- Clone a station

**Expected behavior**
Station getting cloned
(I am using "custom" media folders)

**Relevant Logs**
- Cloning station 1:
```
500
A new entity was found through the relationship 'App\Entity\Station#recordings_storage_location' that was not configured to cascade persist operations for entity: Local: /var/azuracast/recordings. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
ORMInvalidArgumentException.php : 102
```

Cloning station 2:
```
500
Multiple non-persisted new entities were found through the given association graph: * A new entity was found through the relationship 'App\Entity\Station#media_storage_location' that was not configured to cascade persist operations for entity: Local: /var/azuracast/media. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). * A new entity was found through the relationship 'App\Entity\Station#recordings_storage_location' that was not configured to cascade persist operations for entity: Local: /var/azuracast/recordings. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
ORMInvalidArgumentException.php : 105
```

**Screenshots**
![image](https://user-images.githubusercontent.com/245041/101111451-7b704f80-35db-11eb-9814-77ce2052df17.png)
![image](https://user-images.githubusercontent.com/245041/101111855-5d571f00-35dc-11eb-89af-6f09ab7d657e.png)

**Device(s):**
N/A

**Additional context**
`ORMInvalidArgumentException`
Seems like it did copy/create playlists though (even though I selected not to copy those), they appeared when created #2 manually. At copy the station itself didn't get created. [No DB Transactions?]

**Comment by TrevorRoberts** [comment]
I have just tried to clone a station too and got the same error.

**Comment by JackCoder21** [comment]
Same configuration and same error

**Comment by SlvrEagle23** [comment]
@xewl @TrevorRoberts @JackCoder21 This should be fixed as of the latest update in the rolling-release version.

**Comment by xewl** [comment]
Sadly I'm still having this at current release #5e62a1b, as the second screenshot still seems to occur.

```
Multiple non-persisted new entities were found through the given association graph: * A new entity was found through the relationship 'App\Entity\Station#media_storage_location' that was not configured to cascade persist operations for entity: Local: /var/azuracast/stations/born_to_run_-_copy/media. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). * A new entity was found through the relationship 'App\Entity\Station#recordings_storage_location' that was not configured to cascade persist operations for entity: Local: /var/azuracast/stations/born_to_run_-_copy/recordings. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
ORMInvalidArgumentException.php : 105
```

**Comment by SlvrEagle23** [comment]
@xewl Found the issue and fixed it; can confirm locally cloning now works as expected again.
