### ISSUE TITLE
Listener Data Export

### ISSUE THREAD

**Issue by HuckinB** [AzuraCast/AzuraCast#3769]
Hi there, 

We have noticed over the past few updates, that after the update we cannot backtrack listener data of which is needed for PPL and PPR licenses. We can select up to the date of the update, but anything after that does not load.

We would also like to ask, where is this data stored? Is it via the database? 
As we would like to find a way to export this data in an easier format.

And help is greatly appreciated.

Regards,

Brandon

[CC @KylePython]

**Comment by Vaalyn** [comment]
In general AzuraCast keeps analytical data in a database table called `analytics` which has the following format:
```
+---------------+---------------+------+-----+---------+----------------+
| Field         | Type          | Null | Key | Default | Extra          |
+---------------+---------------+------+-----+---------+----------------+
| id            | int(11)       | NO   | PRI | NULL    | auto_increment |
| station_id    | int(11)       | YES  | MUL | NULL    |                |
| type          | varchar(15)   | NO   | MUL | NULL    |                |
| number_min    | int(11)       | NO   |     | NULL    |                |
| number_max    | int(11)       | NO   |     | NULL    |                |
| number_avg    | decimal(10,2) | NO   |     | NULL    |                |
| moment        | datetime      | NO   |     | NULL    |                |
| number_unique | int(11)       | YES  |     | NULL    |                |
+---------------+---------------+------+-----+---------+----------------+
```

Make sure to set this setting to how long your local laws need you to keep the data so that it isn't automatically cleaned up:

![image](https://user-images.githubusercontent.com/13745863/106938057-c82cef80-671e-11eb-9599-ba8580364973.png)

If you have set your installation to retain the data for a long time range you should be able to export it as CSV from the `Listeners` page of your station.

**Comment by HuckinB** [comment]
Much appreciated thank you!

**Comment by HuckinB** [comment]
Turns out, when changing the date range for the data. The API returns a 500 error. I have gone into the docker-compose logs and returned with this error
`"PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/matomo/device-detector/Parser/AbstractParser.php on line 254" while reading response header from upstream, client: 192.168.16.4, server: localhost, request: "GET /api/station/1/listeners?start=2021-02-07&end=2021-02-07 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000"`

Any ideas?

**Comment by SlvrEagle23** [comment]
@HuckinB You can fix this by opening `azuracast.env` on your host computer, adding or modifying the line that looks like this:

```
# PHP_MAX_EXECUTION_TIME=30
```

to look like this:

```
PHP_MAX_EXECUTION_TIME=300
```

(or higher than 300 if you want), then running:

```
docker-compose down
docker-compose up -d
```

**Comment by HuckinB** [comment]
Attempting now, as I'm sure you're aware. Having the Broadcast Hours / Listener Data is essential for PRS so we were very confused as to why this wasn't working.

**Comment by HuckinB** [comment]
By the way, on docker up.

You given an alert about "Now Playing Data" Not synchronised. 
When you click run task, it actually errors
`| [2021-02-08T17:14:02.843820+00:00] AzuraCast.WARNING: Failed to store the "{resource}" lock. Abort after {retry} retry. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_nowplaying_station_4"},"retry":30} []
web_1                      | [2021-02-08T17:14:02.845069+00:00] AzuraCast.ERROR: Symfony\Component\Lock\Exception\LockConflictedException:  (uncaught exception) at /var/azuracast/www/vendor/symfony/lock/Store/RetryTillSaveStore.php line 81 while running console command `sync:run` {"exception":"[object] (Symfony\\Component\\Lock\\Exception\\LockConflictedException(code: 0):  at /var/azuracast/www/vendor/symfony/lock/Store/RetryTillSaveStore.php:81)"} []
web_1                      | [2021-02-08T17:14:02.845397+00:00] AzuraCast.WARNING: Console command `sync:run` exited with error code 1. [] []
web_1                      |
web_1                      | In RetryTillSaveStore.php line 81:
web_1                      |
web_1                      |   [Symfony\Component\Lock\Exception\LockConflictedException]
web_1                      |
web_1                      |
web_1                      | sync:run [--force] [--] [<task>]
`

**Comment by HuckinB** [comment]
Updating to 300 ms now returns E502

**Comment by KylePython** [comment]
Is there a way to access the DB via HeidiSQL or some other Software?

**Comment by SlvrEagle23** [comment]
> By the way, on docker up.
> 
> You given an alert about "Now Playing Data" Not synchronised.
> When you click run task, it actually errors
> `| [2021-02-08T17:14:02.843820+00:00] AzuraCast.WARNING: Failed to store the "{resource}" lock. Abort after {retry} retry. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_nowplaying_station_4"},"retry":30} [] web_1 | [2021-02-08T17:14:02.845069+00:00] AzuraCast.ERROR: Symfony\Component\Lock\Exception\LockConflictedException: (uncaught exception) at /var/azuracast/www/vendor/symfony/lock/Store/RetryTillSaveStore.php line 81 while running console command `sync:run`{"exception":"[object] (Symfony\\Component\\Lock\\Exception\\LockConflictedException(code: 0): at /var/azuracast/www/vendor/symfony/lock/Store/RetryTillSaveStore.php:81)"} [] web_1 | [2021-02-08T17:14:02.845397+00:00] AzuraCast.WARNING: Console command`sync:run`exited with error code 1. [] [] web_1 | web_1 | In RetryTillSaveStore.php line 81: web_1 | web_1 | [Symfony\Component\Lock\Exception\LockConflictedException] web_1 | web_1 | web_1 | sync:run [--force] [--] [<task>]`

You should be able to add `--force` to the end of the `sync:run` command to get it to override any existing locks.

**Comment by KylePython** [comment]
We still can not retrieve listener report data.

Is there any way we can resolve this?

**Comment by balmasedano** [comment]
We have the same problem. We can display data for a single day but we get no data when we select a range of dates.

I've tried to change mentioned values at AzuraCast.env, but I get a 502 error.

I have also tried to backup my installation and restore in another server (clean installation) but listeners API displays the same error.

I have AzuraCast 0.12.1 stable. I'm using a VPS with 8 GB RAM and 8 vCores.

Thanks!

**Comment by KylePython** [comment]
> We have the same problem. We can display data for a single day but we get no data when we select a range of dates.
> 
> I've tried to change mentioned values at AzuraCast.env, but I get a 502 error.
> 
> I have also tried to backup my installation and restore in another server (clean installation) but listeners API displays the same error.
> 
> I have AzuraCast 0.12.1 stable. I'm using a VPS with 8 GB RAM and 8 vCores.
> 
> Thanks!

Do you still have this issue?

**Comment by balmasedano** [comment]
Yes, it keeps happening. It only happens with the stations with the most listeners.

The problem appeared when updating to the last stable version. One week ago reports worked fine for me.

**Comment by KylePython** [comment]
> Yes, it keeps happening. It only happens with the stations with the most listeners.
> 
> The problem appeared when updating to the last stable version. One week ago reports worked fine for me.

Ah okay, just best hope it's fixed in the next release 🤞🏻

**Comment by redcastle-de** [comment]
+1 

We also have problems exporting the listener stats to a CSV file.
Same error (502 bad gateway), nothing special that I have found in the logs.

I have tried to increase PHP memory limit and PHP execution time - still no success.

Any help is appreciated.

**Comment by SlvrEagle23** [comment]
We're still missing any necessary diagnostic information that would help us resolve this issue.

Since it appears to particularly affect larger streams with more listeners, it's possible that it is still a question of execution time or memory limit, which the recent optimizations were meant to help with.

In our latest rolling-release version, we've improved fatal error logging so it will still write fatal errors (i.e. out of memory or execution time exceeded) to the log, which may improve the ability to document this error if you update to the latest rolling release.

**Comment by balmasedano** [comment]
Thanks for your help @SlvrEagle23.

Now, when I try to see current listeners or to select a range of dates, I get this error code in listeners.php

```
{
    "code": 500,
    "message": "TypeError at /var/azuracast/www/src/Service/IpGeolocation.php L57: Argument 2 passed to App\\Service\\IpGeolocation::getLocationInfo() must be of the type string, object given, called in /var/azuracast/www/src/Controller/Api/Stations/ListenersAction.php on line 182",
    "formatted_message": "<b>TypeError at /var/azuracast/www/src/Service/IpGeolocation.php L57:</b> Argument 2 passed to App\\Service\\IpGeolocation::getLocationInfo() must be of the type string, object given, called in /var/azuracast/www/src/Controller/Api/Stations/ListenersAction.php on line 182",
    "extra_data": [],
    "success": false
}
```

**Comment by KylePython** [comment]
> We're still missing any necessary diagnostic information that would help us resolve this issue.
> 
> Since it appears to particularly affect larger streams with more listeners, it's possible that it is still a question of execution time or memory limit, which the recent optimizations were meant to help with.
> 
> In our latest rolling-release version, we've improved fatal error logging so it will still write fatal errors (i.e. out of memory or execution time exceeded) to the log, which may improve the ability to document this error if you update to the latest rolling release.

Our station averages 100-200 listeners per day.
It usually took up-to 30 seconds to retrieve data.
I have noticed that it does not want to retrieve data if I was to choose yesterday's date or before.

We have changed our execution time and memory limit but still seems to be no difference.

**Comment by balmasedano** [comment]
It this could help, with the 0.11 stable version we hadn't this problem. The bug appeared when updating to 0.12 and continued at 0.12.1, and now with the latest rolling releases.

Thanks!

**Comment by redcastle-de** [comment]
Same here after updating to the rolling release:

![grafik](https://user-images.githubusercontent.com/79607441/109433308-019c0680-7a10-11eb-976a-30de7db80970.png)

But I am not sure, if this reflects the original error, because
1. This error message appears immediately, whiel the original error occured after several seconds
2. This error message also occurs when downloading small amounts of data (e.g. less than 1 day) which used to work until I upgraded to the rolling release.

I hope this helps a bit to catch the error.

**Comment by balmasedano** [comment]
I've installed AzuraCast in a local VM. This is the error log

```
nginx_proxy                | nginx.1    | 192.168.64.4 192.168.64.1 - - [28/Feb/2021:21:11:39 +0000] "GET /api/station/1/listeners HTTP/2.0" 500 617 "https://192.168.64.4/station/1/reports/listeners" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
nginx_proxy                | nginx.1    | 192.168.64.4 192.168.64.1 - - [28/Feb/2021:21:11:44 +0000] "GET /api/station/1/listeners?start=2021-03-15&end=2021-03-21 HTTP/2.0" 500 617 "https://192.168.64.4/station/1/reports/listeners" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
```

**Comment by SlvrEagle23** [comment]
I've made some changes to how this report is generated to make better use of caches and memory-optimized functionality in the system; it's not necessarily perfect but it should be significantly improved in its ability to generate large reports.

Please test the latest rolling-release version and let me know if it helps with things.

**Comment by balmasedano** [comment]
Thank you for your time, @SlvrEagle23.

Now it works perfectly and fastly than other old versions for the most of our stations, but It still fails when I try to get data from our most listened products using the default PHP config.

<img width="1831" alt="Captura de pantalla 2021-03-02 a las 13 52 51" src="https://user-images.githubusercontent.com/2371754/109651425-ceb45880-7b5e-11eb-8618-0eff8b7a2bb4.png">

This is the error log:

`2021/03/02 12:56:21 [error] 44#44: *990 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/matomo/device-detector/Parser/AbstractParser.php on line 254" while reading response header from upstream, client: 172.21.0.4, server: localhost, request: "GET /api/station/2/listeners?start=2021-02-15&end=2021-02-21 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.64.4", referrer: "https://192.168.64.4/station/2/reports/listeners"
`

Then, I tried to set the max execution time to 300, as explained upper in this thread and got a 502 error.

<img width="1744" alt="Captura de pantalla 2021-03-02 a las 14 03 51" src="https://user-images.githubusercontent.com/2371754/109652573-4040d680-7b60-11eb-8e92-1d36f4f0c40f.png">

This happens after a minute of waiting. Is there any way to improve the nginx configuration?

<img width="1601" alt="Captura de pantalla 2021-03-02 a las 14 05 29" src="https://user-images.githubusercontent.com/2371754/109652682-62d2ef80-7b60-11eb-8c9c-318a35251b53.png">

I have tested at a clean installation using multipass

`azuracast                   
    description: Computer
    width: 64 bits
    capabilities: smp vsyscall32
  *-core
       description: Motherboard
       physical id: 0
     *-memory
          description: System memory
          physical id: 0
          size: 4GiB
     *-cpu:0
          product: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          width: 64 bits
`

Now at least I have the possibility to collect data day by day and to sum in a spreadsheet to make my audience reports again.

Thanks again!

**Comment by HuckinB** [comment]
@SlvrEagle23 
We updated to the latest rolling release but the issue still persists.

If you have any spare time do you think a Discord Call or other meeting type would be helpful to both of us?

**Comment by HuckinB** [comment]
Loading of data works on our Test Station, but as above this does not have a large number of listener data to load.

**Comment by balmasedano** [comment]
@Vaalyn After the last rolling update, now I can get data of a few days.

<img width="1459" alt="Captura de pantalla 2021-03-03 a las 13 51 54" src="https://user-images.githubusercontent.com/2371754/109808846-e1df2b00-7c27-11eb-85c2-a820c5a85db1.png">

The problem persists when I try to select an entire week.

<img width="1071" alt="Captura de pantalla 2021-03-03 a las 14 11 10" src="https://user-images.githubusercontent.com/2371754/109810819-4ef3c000-7c2a-11eb-94f8-b638ba15cd08.png">

**Comment by Vaalyn** [comment]
@balmasedano That is currently to be expected.

The timeout that you are running into here is from the NGINX proxy server that is currently using the default proxy timeout of 60s. So even if the php timeout is set to for example 5 minutes it would still time out after 1 minute due to the nginx server.

We need to improve that in our nginx config / make that configurable.

**Comment by balmasedano** [comment]
Thanks, @Vaalyn. If I could help or if you explain me how to change that config to test possible solutions, tell me.

**Comment by HuckinB** [comment]
@balmasedano, I believe @Vaalyn is saying that nginx config is set to 60 seconds and that is not something that we are able to currently change. "We need to improve that in our nginx config / make that configurable."

I had a brief look into the code and couldn't find the location of the config file so this might be something you guys would want to put into the azuracast.env

**Comment by SlvrEagle23** [comment]
Good news! In a bit of serendipitous timing, the maintainer of the Ubuntu PHP PPAs, which we use for our build processes on both Docker and Ansible, just added support this week for the much faster native-C-extension Maxmind GeoIP database reader.

We've swapped out our existing PHP implementation with this native extension, which promises to offer significantly improved speeds in reading data, which is a huge determining factor in the length of time these reports take.

Our update to incorporate this functionality is rolling out as we speak; if you've been experiencing trouble with your listener reports not generating in a timely fashion, try updating to the latest rolling-release channel and it may help.

**Comment by KylePython** [comment]
We've done an update (RR: 82ed6f6) and still encountering errors.
![image](https://user-images.githubusercontent.com/41867471/110187629-e61a6c80-7e10-11eb-84c4-46c5209c4317.png)

Is there anything you can advise us changing?

**Comment by SlvrEagle23** [comment]
@KylePython We've looked into the nginx side of things, and determined that there's a timeout that we didn't set a value for on the nginx proxy; we've increased all of the timeouts across the board by default to 1800 seconds which should allow for extremely long runtimes out of the box.

Updating to the latest Rolling Release (while also making sure to update your `docker-compose.yml` file when prompted) will get you the longer timeouts.

In the event you need to extend that timeout even further, you can set a value in `.env` like so:

```
NGINX_TIMEOUT=12345
```

and then restart your services (`docker-compose down` and `docker-compose up -d`) to apply the changes.

**Comment by KylePython** [comment]
This is now working!! You're a diamond, thanks for your help @SlvrEagle23.

**Comment by redcastle-de** [comment]
Same here, many many thanks!😃

**Comment by balmasedano** [comment]
Working for me. It takes some minutes, but now I can export data for a entire week: more than 30.000 listeners in a single report. Thanks a lot!

**Comment by KylePython** [comment]
![image](https://user-images.githubusercontent.com/41867471/119060565-5bd2b500-b9ca-11eb-9946-e1f94dbc41fb.png)

I appear to have this issue again - I've increased the NGINX_TIMEOUT to 14400

**Comment by Vaalyn** [comment]
> ![image](https://user-images.githubusercontent.com/41867471/119060565-5bd2b500-b9ca-11eb-9946-e1f94dbc41fb.png)
> 
> I appear to have this issue again - I've increased the NGINX_TIMEOUT to 14400

I don't think that we ever return a `524` status code which leads me to think that this timeout on your screenshot is actually from CloudFlare cutting your connection.
