### ISSUE TITLE
After the last update just now, something is wrong

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#3808]
**Using Docker installation method**

Yes

**AzuraCast version**

Latest Rolling Releases

**Host Operating System**

Ubuntu Linux 19.04

**Describe the bug**

**To Reproduce**

After the last update just now, something is wrong.
This is also in the demo version of azuracast.
https://demo.azuracast.com
The login screen looks different and you cannot login.
Library InlinePlayer not found!
Assets.php: 193

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by stardevelop** [comment]
Same critical issue:

As soon as I login to the Dashboard, I get this error message:

500
Library InlinePlayer not found!
Assets.php : 193

**Comment by buddhatunes** [comment]
same problem

![upgrade-error](https://user-images.githubusercontent.com/2067407/107752820-3fe5b600-6ced-11eb-9cba-9b4c44ee707f.png)

**Comment by SC2Mitch** [comment]
This is indeed an issue, I recommend rolling back to a different version through a Snapshot or backup until this issue is resolved.

**Comment by SlvrEagle23** [comment]
@rolradio @stardevelop @buddhatunes This has been fixed as of the latest rolling-release Docker image. We had an issue after migrating to the newer version of the Docker build GitHub action that wasn't picked up by our test suite (because it happened in the later image build process, rather than the test process), so we've reverted to the previous version for now until we can research things further.

Sorry for any inconvenience and thank you for your patience.

**Comment by stardevelop** [comment]
@SlvrEagle23 
I just updated to the latest rolling-release Docker image but still the problem persists.

**Comment by SlvrEagle23** [comment]
@stardevelop I can confirm through our demo instance that the latest version of the Docker Rolling Release image does _not_ have the asset problem. Please try updating again.

**Comment by rolradio** [comment]
@SlvrEagle23 Thank you, problem solved for now.
