### ISSUE TITLE
Some stations are not counting listeners on profile page

### ISSUE THREAD

**Issue by lramilo** [AzuraCast/AzuraCast#4341]
**Using Docker installation method?**
Yes

**AzuraCast version:**
0.12.2 stable

**Host Operating System:**
Ubuntu 18.x

**Describe the bug:**
Some stations are not showing the listener count on profile page.

**Steps to reproduce:**
I have multiple customer's stations from my hosting service running on AzuraCast as beta testers. 

I managed to add external relays to handle listeners as I plan to offer this service for customers with high audience levels. These relays are Icecast 2.4.0-kh15 in order to have better compatibility with AzuraCast, specifically with audience monitoring.

Once I added all the relays, using API, I was able to see the correct audience levels. But after a while, I could not get the number on many of the station's profile pages; but could get the number on the listeners page.

I've restarted the stations, and also deleted the external relays, but nothing changed.

I don't know if there's something I cloud search in order to find the problem.

Help will be appreciated !

**Additional info:**

_**This is an example of one of the stations with the problem:**_
_It shows 0 listeners even when there are 3 connections (2 on AzuraCast's Icecast instances and 1 on an external Icecast relay)_

![image](https://user-images.githubusercontent.com/74368492/123448734-860f2800-d5b1-11eb-8f59-2d552c5f6873.png)

![image](https://user-images.githubusercontent.com/74368492/123449411-06358d80-d5b2-11eb-910e-3363520ba7fe.png)

_This is how the external relays looks like:_

![image](https://user-images.githubusercontent.com/74368492/123449904-7cd28b00-d5b2-11eb-934b-516e034e752a.png)

_This is the same station without the external relays, same behavior:_

![image](https://user-images.githubusercontent.com/74368492/123450510-316cac80-d5b3-11eb-949a-f50e3dd53b92.png)

_**This is an example of one of the stations that work well:**_
This is showing 24 listeners, that's correct as it could be seen on the details.

![image](https://user-images.githubusercontent.com/74368492/123449255-de462a00-d5b1-11eb-9425-43dbc8c8c7b4.png)

![image](https://user-images.githubusercontent.com/74368492/123449295-e736fb80-d5b1-11eb-9002-8f3378c7c90c.png)

**Comment by lramilo** [comment]
The same problem is reflected on dashboard page.

![image](https://user-images.githubusercontent.com/74368492/123476106-a8fe0400-d5d2-11eb-8725-593d5f344b49.png)

**Comment by Vaalyn** [comment]
You might want to try updating to `0.13.0` since there have been some updates for listener data handling and relays.
It could have been fixed already.

**Comment by lramilo** [comment]
Thank you @Vaalyn I've updated to `0.13.0` but the problem persists.

**Comment by lramilo** [comment]
On the other hand, some stations on the same server are counting listeners many times, as follows:

![image](https://user-images.githubusercontent.com/74368492/124310195-38ab3180-db42-11eb-87b0-22e36f1f7250.png)

**Comment by Vaalyn** [comment]
Could you manually run the `Now Playing Sync` via the admin page and look for the 3 lines (and any errors directly related to them) for the remote relays that are not showing listeners?

The lines should begin like this:
```
AzuraCast.DEBUG: Sending GET request to http://stations:8000/admin/stats ...
AzuraCast.DEBUG: HTTP client GET call to http://stations:8000/admin/stats produced response 200 ...
AzuraCast.DEBUG: Raw body from response.  ...
```

Somewhere the data gets lost but we'll need to figure out where.
These logs should help seeing if the response from the relays statistics page is correctly returning the data to AzuraCast.

**Comment by lramilo** [comment]
@Vaalyn I share a Google Docs with this info:

Station 8000 (works OK) screenshot 
Station 8020 (shows 0 listeners) screenshot
Station 8030 (duplicates listeners) screenshot

And the complete log obtained after running the task

You could access the file using this link: 

[Google Docs: Azuracast/Some stations are not counting listeners on profile page #4341](https://docs.google.com/document/d/18Q4NUeqtfzBKsnKftUP-bohCMhVMvhAI5efMP0c7Xu4/edit?usp=sharing)

I'm doing further testing and checking these logs too. Notice that I remove my external relays (as explained above on this same issue) I get the same result.

Please let me know if you need more details.

Thank you very much for your time !

Regards,

**Comment by Vaalyn** [comment]
I think the logs in your shared doc are incomplete.

Can you upload upload the complete logs as a `.txt` here?

**Comment by lramilo** [comment]
Sure @Vaalyn ! 

Please find complete [logs.txt](https://github.com/AzuraCast/AzuraCast/files/6757629/logs.txt) attached here. Also, I suspect having non-public streams could be affecting as this start happening once I changed this. I will try and back here with my results.

Again, thank you for your time.

Regards,
