### ISSUE TITLE
Error while trying to create Streamer account schedule [Bug]: 

### ISSUE THREAD

**Issue by martchyke** [AzuraCast/AzuraCast#4469]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### What happened?

1. The Azuracast seem not to be able to connect to DSP plugins both BUTT and SHOUTcast
2. Unable to create streamer account schedule  

### Relevant log output

```shell
TypeError at /var/azuracast/www/src/Entity/StationSchedule.php L178: App\Entity\StationSchedule::setLoopOnce(): Argument #1 ($loop_once) must be of type bool, null given, called in /var/azuracast/www/src/Entity/Repository/StationScheduleRepository.php on line 62
```

**Comment by SlvrEagle23** [comment]
@martchyke Thank you for the report! This should be fixed in the latest version of the Rolling Release channel that's deploying currently.

**Comment by martchyke** [comment]
I have done the upgrade but we still can't connect to the server through DSP plugins
