### ISSUE TITLE
Orphan containers after update to azuracast 14.0

### ISSUE THREAD

**Issue by Robdewild** [AzuraCast/AzuraCast#4470]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Ecb54b9

### What happened?

During installation found orphan containers.
Tried with —remove-orphans, but doesn‘t work.
Ubuntu 18.04 shows 1 zombie process.
When rebooting zombie is gone for a while.
Sometimes 2 times a day.
Sometimes 2 times in one hour.
Witch log output should i post?
I have several screenshots of the commandshell from ubuntu.
And the errors during installation.
Help is appreciated.

thanks i.a
Rob

**Comment by SlvrEagle23** [comment]
@Robdewild The orphan container issue should only happen if you've updated from a very old installation that wasn't installed into `/var/azuracast` initially. It should only require spinning down the Docker containers once.

Basically, you can spin down all unneeded Docker containers by running:

```bash
docker rm $(docker ps -a -q)
docker-compose up -d
```

in the AzuraCast directory. This should resolve the issue and resume normal operations.

**Comment by Robdewild** [comment]
Hi Silver Eagle,


Tried the command, but got an error that the containers still running..
A bit tricky😬
I think that is also the reason that there is a zombie process in ubuntu.
Don‘t know what happend.
Very strange.


2b006623d77ed9ebc583d4651cc6315. Stop the container before attempting removal or force remove                           Error response from daemon: You cannot remove a running container 60385ea18245645de07b7a57909dca84c1fd0ad199bdba33210db86f403689e8. Stop the container before attempting removal or force remove                           Error response from daemon: You cannot remove a running container 2dd11cd73eb72de922de201ef3f49f5e5fdf41d0bffaeda48e62deea31eb4e29. Stop the container before attempting removal or force remove                           Error response from daemon: You cannot remove a running container 2d7c7f96fd86b8bcd73e48f377d1298d0c9ac4d9122e8c32adf0eba949d6c78d. Stop the container before attempting removal or force remove                           Error response from daemon: You cannot remove a running container 5e1965a29f705ba1037cb6dae928b6ea041d80f87bbffed30ae13a2971e86c8b. Stop the container before attempting removal or force remove                           root@gnoenet:/var/azuracast#

**Comment by Robdewild** [comment]
ubuntu output during update

Pulling installer ... done               Creating network "azuracast_default" with the default driver                      WARNING: Found orphan containers (azuracast_stations, nginx_proxy_letsencrypt, nginx_proxy, azuracast_redis, azuracast_mariadb, azuracast_web) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.                                   Creating azuracast_installer_run ... done                                         AzuraCast Updater                        =================

**Comment by SlvrEagle23** [comment]
@Robdewild Try this first, then:

```
docker kill $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker-compose up -d
```

**Comment by Robdewild** [comment]
Hi Slvr Eagle,

Sorry, but doesn‘t work.
Removed the containers, but next reboot they are back.

incl zombieprocess.
Tried several times..
It seems that there are 2 installations active in my system…
Any other ideas?

via 
Mobiel 

> Op 11 aug. 2021 om 04:23 heeft SlvrEagle23 ***@***.***> het volgende geschreven:
> 
> docker rm $(docker ps -a -q)

**Comment by Robdewild** [comment]
Discovered following:
I have 5 playlist sceduled for the day
Liquidsoap only select tracks from 3 playlists.
Now playing updates only work when in debugging rebuild playlist is selected.
Then it will work for a few hours.
Tried with stable, and rolling release version.


via 
Mobiel

**Comment by Robdewild** [comment]
Playlist problem is gone.
Was my own mistake.
Rolled back to stable version, and runned without problems for 1  day.
Then the orphaned containers are there again.
With the zombie process.
Really need help here..

**Comment by SlvrEagle23** [comment]
@Robdewild This is something specific with Docker that you may have to be a little resourceful to resolve. If you run `docker ps` on the computer, you should see a full list of all the running containers.

**Comment by Robdewild** [comment]
Output docker ps:

***@***.***:~# cd /var/azuracast        ***@***.***:/var/azuracast# docker ps   CONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              NAMES     54913dc07cc2        ghcr.io/azuracast/nginx_proxy_letsencrypt:latest   "/bin/bash /app/entr…"   24 minutes ago      Up About a minute                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nginx_proxy_letsencrypt                            5ebf66e2abb5        ghcr.io/azuracast/nginx_proxy:latest               "/app/docker-entrypo…"   24 minutes ago      Up About a minute   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           nginx_proxy                                        3bc75a057fc7        ghcr.io/azuracast/web:latest                       "/usr/local/bin/upti…"   24 minutes ago      Up About a minute   80/tcp, 0.0.0.0:2022->2022/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     azuracast_web                                      3b7b1c6c5bfc        ghcr.io/azuracast/radio:latest                     "/usr/local/bin/my_i…"   24 minutes ago      Up 51 seconds       0.0.0.0:8000->8000/tcp, 8001-8004/tcp, 0.0.0.0:8005-8006->8005-8006/tcp, 8007-8009/tcp, 0.0.0.0:8010->8010/tcp, 8011-8014/tcp, 0.0.0.0:8015-8016->8015-8016/tcp, 8017-8019/tcp, 0.0.0.0:8020->8020/tcp, 8021-8024/tcp, 0.0.0.0:8025-8026->8025-8026/tcp, 8027-8029/tcp, 0.0.0.0:8030->8030/tcp, 8031-8034/tcp, 0.0.0.0:8035-8036->8035-8036/tcp, 8037-8039/tcp, 0.0.0.0:8040->8040/tcp, 8041-8044/tcp, 0.0.0.0:8045-8046->8045-8046/tcp, 8047-8049/tcp, 0.0.0.0:8050->8050/tcp, 8051-8054/tcp, 0.0.0.0:8055-8056->8055-8056/tcp, 8057-8059/tcp, 0.0.0.0:8060->8060/tcp, 8061-8064/tcp, 0.0.0.0:8065-8066->8065-8066/tcp, 8067-8069/tcp, 0.0.0.0:8070->8070/tcp, 8071-8074/tcp, 0.0.0.0:8075-8076->8075-8076/tcp, 8077-8089/tcp, 0.0.0.0:8090->8090/tcp, 8091-8094/tcp, 0.0.0.0:8095-8096->8095-8096/tcp, 8097-8099/tcp, 0.0.0.0:8100->8100/tcp, 8101-8104/tcp, 0.0.0.0:8105-8106->8105-8106/tcp, 8107-8109/tcp, 0.0.0.0:8110->8110/tcp, 8111-8114/tcp, 0.0.0.0:8115-8116->8115-8116/tcp, 8117-8119/tcp, 0.0.0.0:8120->8120/tcp, 8121-8124/tcp, 0.0.0.0:8125-8126->8125-8126/tcp, 8127-8129/tcp, 0.0.0.0:8130->8130/tcp, 8131-8134/tcp, 0.0.0.0:8135-8136->8135-8136/tcp, 8137-8139/tcp, 0.0.0.0:8140->8140/tcp, 8141-8144/tcp, 0.0.0.0:8145-8146->8145-8146/tcp, 8147-8149/tcp, 0.0.0.0:8150->8150/tcp, 8151-8154/tcp, 0.0.0.0:8155-8156->8155-8156/tcp, 8157-8159/tcp, 0.0.0.0:8160->8160/tcp, 8161-8164/tcp, 0.0.0.0:8165-8166->8165-8166/tcp, 8167-8169/tcp, 0.0.0.0:8170->8170/tcp, 8171-8174/tcp, 0.0.0.0:8175-8176->8175-8176/tcp, 8177-8179/tcp, 0.0.0.0:8180->8180/tcp, 8181-8184/tcp, 0.0.0.0:8185-8186->8185-8186/tcp, 8187-8189/tcp, 0.0.0.0:8190->8190/tcp, 8191-8194/tcp, 0.0.0.0:8195-8196->8195-8196/tcp, 8197-8199/tcp, 0.0.0.0:8200->8200/tcp, 8201-8204/tcp, 0.0.0.0:8205-8206->8205-8206/tcp, 8207-8209/tcp, 0.0.0.0:8210->8210/tcp, 8211-8214/tcp, 0.0.0.0:8215-8216->8215-8216/tcp, 8217-8219/tcp, 0.0.0.0:8220->8220/tcp, 8221-8224/tcp, 0.0.0.0:8225-8226->8225-8226/tcp, 8227-8229/tcp, 0.0.0.0:8230->8230/tcp, 8231-8234/tcp, 0.0.0.0:8235-8236->8235-8236/tcp, 8237-8239/tcp, 0.0.0.0:8240->8240/tcp, 8241-8244/tcp, 0.0.0.0:8245-8246->8245-8246/tcp, 8247-8249/tcp, 0.0.0.0:8250->8250/tcp, 8251-8254/tcp, 0.0.0.0:8255-8256->8255-8256/tcp, 8257-8259/tcp, 0.0.0.0:8260->8260/tcp, 8261-8264/tcp, 0.0.0.0:8265-8266->8265-8266/tcp, 8267-8269/tcp, 0.0.0.0:8270->8270/tcp, 8271-8274/tcp, 0.0.0.0:8275-8276->8275-8276/tcp, 8277-8279/tcp, 0.0.0.0:8280->8280/tcp, 8281-8284/tcp, 0.0.0.0:8285-8286->8285-8286/tcp, 8287-8289/tcp, 0.0.0.0:8290->8290/tcp, 8291-8294/tcp, 0.0.0.0:8295-8296->8295-8296/tcp, 8297-8299/tcp, 0.0.0.0:8300->8300/tcp, 8301-8304/tcp, 0.0.0.0:8305-8306->8305-8306/tcp, 8307-8309/tcp, 0.0.0.0:8310->8310/tcp, 8311-8314/tcp, 0.0.0.0:8315-8316->8315-8316/tcp, 8317-8319/tcp, 0.0.0.0:8320->8320/tcp, 8321-8324/tcp, 0.0.0.0:8325-8326->8325-8326/tcp, 8327-8329/tcp, 0.0.0.0:8330->8330/tcp, 8331-8334/tcp, 0.0.0.0:8335-8336->8335-8336/tcp, 8337-8339/tcp, 0.0.0.0:8340->8340/tcp, 8341-8344/tcp, 0.0.0.0:8345-8346->8345-8346/tcp, 8347-8349/tcp, 0.0.0.0:8350->8350/tcp, 8351-8354/tcp, 0.0.0.0:8355-8356->8355-8356/tcp, 8357-8359/tcp, 0.0.0.0:8360->8360/tcp, 8361-8364/tcp, 0.0.0.0:8365-8366->8365-8366/tcp, 8367-8369/tcp, 0.0.0.0:8370->8370/tcp, 8371-8374/tcp, 0.0.0.0:8375-8376->8375-8376/tcp, 8377-8379/tcp, 0.0.0.0:8380->8380/tcp, 8381-8384/tcp, 0.0.0.0:8385-8386->8385-8386/tcp, 8387-8389/tcp, 0.0.0.0:8390->8390/tcp, 8391-8394/tcp, 0.0.0.0:8395-8396->8395-8396/tcp, 8397-8399/tcp, 0.0.0.0:8400->8400/tcp, 8401-8404/tcp, 0.0.0.0:8405-8406->8405-8406/tcp, 8407-8409/tcp, 0.0.0.0:8410->8410/tcp, 8411-8414/tcp, 0.0.0.0:8415-8416->8415-8416/tcp, 8417-8419/tcp, 0.0.0.0:8420->8420/tcp, 8421-8424/tcp, 0.0.0.0:8425-8426->8425-8426/tcp, 8427-8429/tcp, 0.0.0.0:8430->8430/tcp, 8431-8434/tcp, 0.0.0.0:8435-8436->8435-8436/tcp, 8437-8439/tcp, 0.0.0.0:8440->8440/tcp, 8441-8444/tcp, 0.0.0.0:8445-8446->8445-8446/tcp, 8447-8449/tcp, 0.0.0.0:8450->8450/tcp, 8451-8454/tcp, 0.0.0.0:8455-8456->8455-8456/tcp, 8457-8459/tcp, 0.0.0.0:8460->8460/tcp, 8461-8464/tcp, 0.0.0.0:8465-8466->8465-8466/tcp, 8467-8469/tcp, 0.0.0.0:8470->8470/tcp, 8471-8474/tcp, 0.0.0.0:8475-8476->8475-8476/tcp, 8477-8479/tcp, 0.0.0.0:8480->8480/tcp, 8481-8484/tcp, 0.0.0.0:8485-8486->8485-8486/tcp, 8487-8489/tcp, 0.0.0.0:8490->8490/tcp, 8491-8494/tcp, 8497-8999/tcp, 0.0.0.0:8495-8496->8495-8496/tcp, 9001/tcp   azuracast_stations                                 118588b98ed8        ghcr.io/azuracast/db:latest                        "dockerize -template…"   24 minutes ago      Up 58 seconds       3306/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           azuracast_mariadb                                  ca4f6c53b75f        ghcr.io/azuracast/redis:latest                     "docker-entrypoint.s…"   24 minutes ago      Up 59 seconds       6379/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           azuracast_redis                                    ***@***.***:/var/azuracast



via 
Mobiel 

> Op 13 aug. 2021 om 16:17 heeft SlvrEagle23 ***@***.***> het volgende geschreven:
> 
> docker ps

**Comment by Robdewild** [comment]
Hello, Slvr Eagle,

Did a bit of homework, but didn‘t come any further.

docker ps -a

Should give output of unused containers.
I have a whole bunch of them:

                                                                      => There is 1 zombie process.                                                    * Super-optimized for small spaces - read how we shrank the memory                  footprint of MicroK8s to make it the smallest full K8s around.                                                             https://ubuntu.com/blog/microk8s-memory-optimisation                                                                    0 updates can be applied immediately.                                             New release '20.04.2 LTS' available.     Run 'do-release-upgrade' to upgrade to it.                                                                                                                          *** /dev/sda2 should be checked for errors ***                                                                             No mail.                                 Last login: Mon Aug 16 19:59:12 2021 from 192.168.0.112                           ***@***.***:~$ sudo -s                   [sudo] password for rob:                 ***@***.***:~# cd /var/azuracast        ***@***.***:/var/azuracast# docker ps -aCONTAINER ID        IMAGE                                              COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              NAMES     a03c22144336        ghcr.io/azuracast/nginx_proxy_letsencrypt:stable   "/bin/bash /app/entr…"   14 minutes ago      Up 14 minutes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          nginx_proxy_letsencrypt                            bdac71dd9a4c        ghcr.io/azuracast/nginx_proxy:stable               "/app/docker-entrypo…"   14 minutes ago      Up 14 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           nginx_proxy                                        6635c49c05eb        ghcr.io/azuracast/web:stable                       "/usr/local/bin/upti…"   14 minutes ago      Up 14 minutes       80/tcp, 0.0.0.0:2022->2022/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     azuracast_web                                      7368a7e37866        ghcr.io/azuracast/radio:stable                     "/usr/local/bin/my_i…"   14 minutes ago      Up 14 minutes       0.0.0.0:8000->8000/tcp, 8001-8004/tcp, 0.0.0.0:8005-8006->8005-8006/tcp, 8007-8009/tcp, 0.0.0.0:8010->8010/tcp, 8011-8014/tcp, 0.0.0.0:8015-8016->8015-8016/tcp, 8017-8019/tcp, 0.0.0.0:8020->8020/tcp, 8021-8024/tcp, 0.0.0.0:8025-8026->8025-8026/tcp, 8027-8029/tcp, 0.0.0.0:8030->8030/tcp, 8031-8034/tcp, 0.0.0.0:8035-8036->8035-8036/tcp, 8037-8039/tcp, 0.0.0.0:8040->8040/tcp, 8041-8044/tcp, 0.0.0.0:8045-8046->8045-8046/tcp, 8047-8049/tcp, 0.0.0.0:8050->8050/tcp, 8051-8054/tcp, 0.0.0.0:8055-8056->8055-8056/tcp, 8057-8059/tcp, 0.0.0.0:8060->8060/tcp, 8061-8064/tcp, 0.0.0.0:8065-8066->8065-8066/tcp, 8067-8069/tcp, 0.0.0.0:8070->8070/tcp, 8071-8074/tcp, 0.0.0.0:8075-8076->8075-8076/tcp, 8077-8089/tcp, 0.0.0.0:8090->8090/tcp, 8091-8094/tcp, 0.0.0.0:8095-8096->8095-8096/tcp, 8097-8099/tcp, 0.0.0.0:8100->8100/tcp, 8101-8104/tcp, 0.0.0.0:8105-8106->8105-8106/tcp, 8107-8109/tcp, 0.0.0.0:8110->8110/tcp, 8111-8114/tcp, 0.0.0.0:8115-8116->8115-8116/tcp, 8117-8119/tcp, 0.0.0.0:8120->8120/tcp, 8121-8124/tcp, 0.0.0.0:8125-8126->8125-8126/tcp, 8127-8129/tcp, 0.0.0.0:8130->8130/tcp, 8131-8134/tcp, 0.0.0.0:8135-8136->8135-8136/tcp, 8137-8139/tcp, 0.0.0.0:8140->8140/tcp, 8141-8144/tcp, 0.0.0.0:8145-8146->8145-8146/tcp, 8147-8149/tcp, 0.0.0.0:8150->8150/tcp, 8151-8154/tcp, 0.0.0.0:8155-8156->8155-8156/tcp, 8157-8159/tcp, 0.0.0.0:8160->8160/tcp, 8161-8164/tcp, 0.0.0.0:8165-8166->8165-8166/tcp, 8167-8169/tcp, 0.0.0.0:8170->8170/tcp, 8171-8174/tcp, 0.0.0.0:8175-8176->8175-8176/tcp, 8177-8179/tcp, 0.0.0.0:8180->8180/tcp, 8181-8184/tcp, 0.0.0.0:8185-8186->8185-8186/tcp, 8187-8189/tcp, 0.0.0.0:8190->8190/tcp, 8191-8194/tcp, 0.0.0.0:8195-8196->8195-8196/tcp, 8197-8199/tcp, 0.0.0.0:8200->8200/tcp, 8201-8204/tcp, 0.0.0.0:8205-8206->8205-8206/tcp, 8207-8209/tcp, 0.0.0.0:8210->8210/tcp, 8211-8214/tcp, 0.0.0.0:8215-8216->8215-8216/tcp, 8217-8219/tcp, 0.0.0.0:8220->8220/tcp, 8221-8224/tcp, 0.0.0.0:8225-8226->8225-8226/tcp, 8227-8229/tcp, 0.0.0.0:8230->8230/tcp, 8231-8234/tcp, 0.0.0.0:8235-8236->8235-8236/tcp, 8237-8239/tcp, 0.0.0.0:8240->8240/tcp, 8241-8244/tcp, 0.0.0.0:8245-8246->8245-8246/tcp, 8247-8249/tcp, 0.0.0.0:8250->8250/tcp, 8251-8254/tcp, 0.0.0.0:8255-8256->8255-8256/tcp, 8257-8259/tcp, 0.0.0.0:8260->8260/tcp, 8261-8264/tcp, 0.0.0.0:8265-8266->8265-8266/tcp, 8267-8269/tcp, 0.0.0.0:8270->8270/tcp, 8271-8274/tcp, 0.0.0.0:8275-8276->8275-8276/tcp, 8277-8279/tcp, 0.0.0.0:8280->8280/tcp, 8281-8284/tcp, 0.0.0.0:8285-8286->8285-8286/tcp, 8287-8289/tcp, 0.0.0.0:8290->8290/tcp, 8291-8294/tcp, 0.0.0.0:8295-8296->8295-8296/tcp, 8297-8299/tcp, 0.0.0.0:8300->8300/tcp, 8301-8304/tcp, 0.0.0.0:8305-8306->8305-8306/tcp, 8307-8309/tcp, 0.0.0.0:8310->8310/tcp, 8311-8314/tcp, 0.0.0.0:8315-8316->8315-8316/tcp, 8317-8319/tcp, 0.0.0.0:8320->8320/tcp, 8321-8324/tcp, 0.0.0.0:8325-8326->8325-8326/tcp, 8327-8329/tcp, 0.0.0.0:8330->8330/tcp, 8331-8334/tcp, 0.0.0.0:8335-8336->8335-8336/tcp, 8337-8339/tcp, 0.0.0.0:8340->8340/tcp, 8341-8344/tcp, 0.0.0.0:8345-8346->8345-8346/tcp, 8347-8349/tcp, 0.0.0.0:8350->8350/tcp, 8351-8354/tcp, 0.0.0.0:8355-8356->8355-8356/tcp, 8357-8359/tcp, 0.0.0.0:8360->8360/tcp, 8361-8364/tcp, 0.0.0.0:8365-8366->8365-8366/tcp, 8367-8369/tcp, 0.0.0.0:8370->8370/tcp, 8371-8374/tcp, 0.0.0.0:8375-8376->8375-8376/tcp, 8377-8379/tcp, 0.0.0.0:8380->8380/tcp, 8381-8384/tcp, 0.0.0.0:8385-8386->8385-8386/tcp, 8387-8389/tcp, 0.0.0.0:8390->8390/tcp, 8391-8394/tcp, 0.0.0.0:8395-8396->8395-8396/tcp, 8397-8399/tcp, 0.0.0.0:8400->8400/tcp, 8401-8404/tcp, 0.0.0.0:8405-8406->8405-8406/tcp, 8407-8409/tcp, 0.0.0.0:8410->8410/tcp, 8411-8414/tcp, 0.0.0.0:8415-8416->8415-8416/tcp, 8417-8419/tcp, 0.0.0.0:8420->8420/tcp, 8421-8424/tcp, 0.0.0.0:8425-8426->8425-8426/tcp, 8427-8429/tcp, 0.0.0.0:8430->8430/tcp, 8431-8434/tcp, 0.0.0.0:8435-8436->8435-8436/tcp, 8437-8439/tcp, 0.0.0.0:8440->8440/tcp, 8441-8444/tcp, 0.0.0.0:8445-8446->8445-8446/tcp, 8447-8449/tcp, 0.0.0.0:8450->8450/tcp, 8451-8454/tcp, 0.0.0.0:8455-8456->8455-8456/tcp, 8457-8459/tcp, 0.0.0.0:8460->8460/tcp, 8461-8464/tcp, 0.0.0.0:8465-8466->8465-8466/tcp, 8467-8469/tcp, 0.0.0.0:8470->8470/tcp, 8471-8474/tcp, 0.0.0.0:8475-8476->8475-8476/tcp, 8477-8479/tcp, 0.0.0.0:8480->8480/tcp, 8481-8484/tcp, 0.0.0.0:8485-8486->8485-8486/tcp, 8487-8489/tcp, 0.0.0.0:8490->8490/tcp, 8491-8494/tcp, 8497-8999/tcp, 0.0.0.0:8495-8496->8495-8496/tcp, 9001/tcp   azuracast_stations                                 4a2e2c197968        ghcr.io/azuracast/db:stable                        "dockerize -template…"   14 minutes ago      Up 14 minutes       3306/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           azuracast_mariadb                                  d634d1b94e73        ghcr.io/azuracast/redis:stable                     "docker-entrypoint.s…"   14 minutes ago      Up 14 minutes       6379/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           azuracast_redis                                    ***@***.***:/var/azuracast#  

Should an upgrade to 20.04 ubuntu do the trick?
Thanks for the help so far.
I apreciate it👍

via 
Mobiel 

> Op 13 aug. 2021 om 16:17 heeft SlvrEagle23 ***@***.***> het volgende geschreven:
> 
> ﻿
> @Robdewild This is something specific with Docker that you may have to be a little resourceful to resolve. If you run docker ps on the computer, you should see a full list of all the running containers.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Robdewild** [comment]
Hello Slvr Eagle,

Did a ubuntu upgrade.
Sadly orphaned containers are still there.
And azuracast services won’t start anymore.
Tried a “update-self, and this is the output:

Creating volume "azuracast_www_vendor" with default driver                        Creating volume "azuracast_tmp_data" with default driver                          Creating volume "azuracast_redis_data" with default driver                        Creating azuracast_redis    ... done     Creating azuracast_mariadb  ... done     Creating azuracast_stations ... done     Creating azuracast_web_run  ... done     Starting up AzuraCast services...        🖥️🎶－🎵－📻 Waiting...                                                                             

And the waiting goes on…

What have i bricked?
During update there are no further errors, but the orphaned containers.
Thanks for the help.
(If you still wants to help)


via 
Mobiel

**Comment by SlvrEagle23** [comment]
@Robdewild I am currently busy with other projects, but I will take a look at this further when I get a chance. Since this is an issue with Docker, it may be easier to look up information on that in your own time rather than having us help, since our time and resources are quite limited compared to the relatively large Docker community.

**Comment by Robdewild** [comment]
Ok, i get that.
Orphaned containers is a docker problem.
But the problem that i have right now is that azuracast services won’t start.
Believe me, i already did alot of searching, but after the ubuntu upgrade to 20.04, azuracast won’t start anymore.
I can start again from zero with a clean system, but is there a way to hold my media volume?
Ftp also doesn’t work at this moment.
Ps: i know your time is limited, and there are other things that are more important, but it would be great if yoy could send me in the right direction.
Thanks!

via 
Mobiel

**Comment by SlvrEagle23** [comment]
@Robdewild If you want to send me an e-mail at buster@busterneece.com with your server login information, I'll see if I can take a look. I wouldn't normally do this free of charge, but since it might be related to something caused by an AzuraCast update I want to make sure it gets fixed.

**Comment by Robdewild** [comment]
Thanks Buster,
Thanks for the offer👍
But i have decided to start from scratch.
Updated Ubuntu to 20.04 and deleted the whole installation of azuracast.
This weekend i will try to reinstall the package.
My media is saved.
I did backup my configfiles to.
As you already said, the problem was docker related.
And first i want to try to fix this myself.
But perhaps i will need some help at some time.
I’ll keep you posted.
Azuracast is a great piece of software!


via 
Mobiel

**Comment by Robdewild** [comment]
Hello Buster,

I give up…
Got the orphaned containers back again.
Got an error on the azuracast homepage.😬
I will give you the serverdetails.
SSH
Adress: gnoenet.nl:22
LOGIN: rob
Pass:309079i
Sudo pass: 309079i

Let me know what the cost are.
It’s worth for me something to get this work again…

Grtz, Rob

via 
Mobiel

**Comment by Abqehebter** [comment]
@Robdewild I don't think it's the best idea to publish your SSH data here.

**Comment by SlvrEagle23** [comment]
@Robdewild Please don't include your SSH details here. You probably should either change your credentials or spin up a new VPS entirely. You can contact me via e-mail with those credentials if you still have issues.

**Comment by Robdewild** [comment]
That certainly wasn’t a good idea.
I thought i just send this mail to buster….
Changed codes as we speak….
Sorry for this stupid action…

via 
Mobiel

**Comment by Robdewild** [comment]
Hello all,
Got another issue after a rolling release update.
Station is running, but got errors when i try to edit playlists, or add music to playlists.
Latest update: Mogelijk gemaakt door AzuraCast • Rolling Release #52e70fe (2021-11-05 10:29) • Docker • PHP 8.0 

![EDF33E19-01DD-4D9D-8E7C-5D49D37A6079](https://user-images.githubusercontent.com/88682313/140562160-733ba349-f64d-4b0b-80ec-737672d98bb2.png)

**Comment by Robdewild** [comment]
PS: The orphaned containers, and zombie process also are still there.
Somewhere there is something bricked.
Thanks for the reply.
Grtz,
Rob

**Comment by SlvrEagle23** [comment]
@Robdewild The malformed URL error should be fixed as of the latest Rolling update from last night.

I don't have any new insight into what's causing the orphan/zombie process situation.

**Comment by Robdewild** [comment]
Sorry guys,

Mogelijk gemaakt door AzuraCast • Rolling Release #cbe106d (2021-11-06 2:05) • Docker • PHP 8.0  

Latest update, but problem still there.




via 
Mobiel

**Comment by Robdewild** [comment]
Hello Buster,

Perhaps i found something.
All the mountpoints are directing to https stream.
I didn‘t set this up on https.
There is also no way to revert this to http..



via 
Mobiel

**Comment by Robdewild** [comment]
Dear azuracast users,

Don’t know if i am the only one that still has a malformed url problem.
Bug should have been repaired, but problem is still there
Version:
Mogelijk gemaakt door AzuraCast • Rolling Release #ab44e41 (2021-11-12 1:30) • Docker • PHP 8.0






via 
Mobiel
