### ISSUE TITLE
Next song not showing in dashboard after skipping song

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4759]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4cbb9dd (2021-11-08 10:29)

### What happened?

It seems that after 2-3 songs or after a certain time the "Next song" does not appear in the display. In the logs, however, I see unfortunately also nothing conspicuous. After a Liquidsoap restart, it works briefly again:
![image](https://user-images.githubusercontent.com/42640247/140741030-dc4da6b9-1baf-4e62-81c9-4a3e931a148f.png)

### Relevant log output

```shell
2021/11/08 13:15:20 [cue_next_song:3] Cueing in...
2021/11/08 13:15:20 [crossfade_0:3] Analysis: -56.648650dB / -25.733379dB (3.68s / 3.68s)
2021/11/08 13:15:20 [crossfade_0:3] new >= old + margin, old <= medium and new <= high.
2021/11/08 13:15:20 [crossfade_0:3] Do not fade if its already very low.
2021/11/08 13:15:20 [crossfade_0:3] Transition: crossed, no fade.
2021/11/08 13:15:20 [lang:3] AzuraCast Feedback Response: OK
2021/11/08 13:15:20 [lang:3] AzuraCast Raw Response: annotate:title="Chain My Heart",artist="Topic & Bebe Rexha",duration="146.00",song_id="32069f82c074743c870d02f93b224836",media_id="5",liq_amplify="0.00dB",playlist_id="1":/var/azuracast/stations/test/media/test/01_-_chain_my_heart.mp3
2021/11/08 13:17:28 [playlist_default:3] Reloading playlist with URI /var/azuracast/stations/test/playlists/playlist_default.m3u.
[mp3float @ 0x7fc5ac391cc0] Could not update timestamps for discarded samples.
2021/11/08 13:18:36 [decoder:2] Decoding "/var/azuracast/stations/test/media/test/01_-_footprints.mp3" ended: Ffmpeg_decoder.End_of_file.
2021/11/08 13:18:37 [next_song:3] Prepared "/var/azuracast/stations/test/media/test/01_-_chain_my_heart.mp3" (RID 6).
[mp3float @ 0x7fc5ada4aa80] Could not update timestamps for skipped samples.
2021/11/08 13:18:37 [cue_next_song:3] Cueing in...
2021/11/08 13:18:37 [crossfade_0:3] Analysis: -40.658332dB / -13.779560dB (3.72s / 3.72s)
2021/11/08 13:18:37 [crossfade_0:3] No transition: using default.
2021/11/08 13:18:37 [lang:3] AzuraCast Raw Response: annotate:title="Break The Silence [Explicit]",artist="Robert Grace",duration="176.00",song_id="9bf4d770e4a5a3052b3961dae9ee4b0a",media_id="4",liq_amplify="0.00dB",playlist_id="1":/var/azuracast/stations/test/media/test/01_-_break_the_silence_[explicit].mp3
2021/11/08 13:18:37 [lang:3] AzuraCast Feedback Response: OK
2021/11/08 13:18:40 [lang:3] AzuraCast Feedback Response: OK
[mp3float @ 0x7fc5ada4aa80] Could not update timestamps for discarded samples.
2021/11/08 13:21:03 [decoder:2] Decoding "/var/azuracast/stations/test/media/test/01_-_chain_my_heart.mp3" ended: Ffmpeg_decoder.End_of_file.
2021/11/08 13:21:03 [next_song:3] Prepared "/var/azuracast/stations/test/media/test/01_-_break_the_silence_[explicit].mp3" (RID 8).
[mp3float @ 0x7fc5ac729300] Could not update timestamps for skipped samples.
2021/11/08 13:21:03 [cue_next_song:3] Cueing in...
2021/11/08 13:21:03 [crossfade_0:3] Analysis: -17.579084dB / -14.007031dB (3.68s / 3.68s)
2021/11/08 13:21:04 [crossfade_0:3] No transition: using default.
2021/11/08 13:21:04 [lang:3] AzuraCast Feedback Response: OK
```

**Comment by Abqehebter** [comment]
Maybe too fast: after the "next song" indicator was gone, 2-5 songs later/some time later it came back. A bit funny.

**Comment by Vaalyn** [comment]
Hey, this is a known issue from my testing in while working on the LS 2 support in AzuraCast.

This is as far as I was able to see an issue with LS itself (see https://github.com/savonet/liquidsoap/issues/1993#issuecomment-960417855) that is caused by the new prefetching of songs. This prefetching fixes the old issue we had with the skipping where LS would just jump off the AutoDJ provided queue and randomly pick something from the available playlists.

Here is a small description of the issue I posted over on their repo:

The song `A - A` ist currently playing, LS has prefetched `B - B` as the next song.
In the AzuraCast upcoming song queue there are `C - C`, `D - D` and `E - E`.

I send a skip command to LS, it calls the next song API / script, gets `C - C` and instead of playing the already prefetched `B - B` it is playing the `C - C` that was returned by the request to the next song API / script. When it then finished playing the `C - C` it switches to the previously fetched `B - B`.

This causes the AzuraCast next song display to get confused until `C - C` and `B - B` are played, so it's not showing a next song until that point is reached.

We felt that this "new" buggy behaviour was better than the old bug since it at least stays on the AutoDJ queue. So we opted to get the LS 2 update out to the users in the rolling-release channel to get further feedback.

I am working on getting this problem fixed together with the LS team though so that the skipping works as expected.

**Comment by zloysystem** [comment]
Yes, I have the same empty next song

**Comment by Vaalyn** [comment]
We figured the source of this issue out and fixed it in an update this night.

When you update your AzuraCast installations this problem should be fixed.

**Comment by Abqehebter** [comment]
Seems to be fixed. For me it works now as before.
Thank you very much for the fix and good luck with the other issues! :)

**Comment by Abqehebter** [comment]
Urgh. Maybe it was too fast from me:
![image](https://user-images.githubusercontent.com/42640247/141464420-0ccdc84d-9ca9-49e0-8bd9-4d1a8ab85d71.png)

**Comment by zloysystem** [comment]
@Vaalyn the problem did not go away on the last update (
![Screenshot_2021-11-12-15-45-49-572_com android chrome](https://user-images.githubusercontent.com/26243386/141470163-1283be9e-0266-43ab-9be0-0e782d2826e5.png)
![Screenshot_2021-11-12-15-46-12-334_com android chrome](https://user-images.githubusercontent.com/26243386/141470168-d129983f-f41f-4cc7-b49e-cb953f1eb4da.png)

**Comment by Vaalyn** [comment]
Taking a look at it again.

The update from last night has fixed the issue where LS was using the song after the next song first (the one I mentioned earlier). In my tests this has also fixed the display issue although it might be that my setup is missing something (maybe some kind of playlist combination, etc) which causes this.

Some questions I'd like to ask to help me figure this out:

- Are you skipping multiple songs quickly after another, for example hitting the skip button x times without waiting for the next song to be shown on the display?
- What does the Upcoming Song Queue show before you hit skip?
- Is the next one a Jingle Mode playlist track?

**Comment by Abqehebter** [comment]
1. I do not skip any song during the error. It's just that the "Next Song" indicator sometimes just disappears during normal rotation without having pressed anything.

2. the Next Song really shows the song that Liquidsoap grabs next from the queue.

3. no. are normal songs. But yes: "Songs" from Jingle Mode are also displayed.

**Comment by Vaalyn** [comment]
Thank you for the quick response 👍 

I think then there might be some kind of timing related issue that I was "lucky" enough to not hit in my tests...
I'll try running a lot of stations at the same time to provoke at least some of them to hit that.

**Comment by zloysystem** [comment]
@Vaalyn managed to catch and fix the example)
![2_5222425381461561896-_online-video-cutter com_](https://user-images.githubusercontent.com/26243386/141477421-f96509b7-0766-4cb7-9673-72d58b95b10e.gif)

**Comment by Vaalyn** [comment]
I managed to get the next song display to behave in the same way a few times now and I have a clue on why this happens but will need to further investigate to find out the exact way this happens in the code.

I dumped the recently songs from the DB that were sent to the LS process of my test installation:
```
+----------------------------------------------+----------------+----------------+----------------+
| title                                        | artist         | timestamp_cued | sent_to_autodj |
+----------------------------------------------+----------------+----------------+----------------+
| Waltz For The Night (ft. Feather)            | Replacer       |     1636722244 |              1 |
| Transient                                    | Zephysonas     |     1636722243 |              1 |
| The Pillars Of Equestria (w/ Michael Picher) | Naturematthe   |     1636722069 |              1 |
+----------------------------------------------+----------------+----------------+----------------+
```

When the issue happened the currently playing song switched to `Waltz For The Night (ft. Feather)` and the next song display vanished, after this song was done playing it switched to `Transient`. This is the correct order according to the Upcoming Song Queue but as you can see in the dumped data the `timestamp_cued` of `Waltz For The Night (ft. Feather)` is actually 1 second later than the one of the song `Transient`.

This `timestamp_cued` problem is the cause of the vanishing next song display.
Now I need to find out why this timestamp is being set in this way.

**Comment by Robdewild** [comment]
Perhaps this question doesn’t belong here, but is it possible to only display the title in now playing?
F.i:  settings.encoder.metadata.export.set(["title"])

instead of album, artist, etc…?
just title would do.
Custom liquidsoap entry doesn’t work.
Thanks i.a

Rob

**Comment by Abqehebter** [comment]
@Robdewild Please create a separate issue for this. This really does not belong here.

**Comment by Abqehebter** [comment]
But it seems to be really fixed now, or do I see something wrong @zloysystem?

**Comment by zloysystem** [comment]
@Abqehebter yes, I haven't noticed any problems yet)

**Comment by Robdewild** [comment]
Still have the issue with malformed url’s, and when deleting a song following occurs..



via 
Mobiel

**Comment by Abqehebter** [comment]
```
Upcoming song in dasgboard doesn’t play.
It plays a song that is not in that list.
And after play, it still remains in the cuelist.
```
@Robdewild I cannot reproduce this error with me.
But it would be good if this bug gets a separate issue here on GitHub. It doesn't fit here anymore. The bug here is fixed for me.

**Comment by erwinlagu** [comment]
is this solved?

**Comment by Abqehebter** [comment]
Yes, it is. As soon as I click on "Skip Song", AzuraCast does that too without any problems. And the "Next Song" is also displayed correctly for me.

Tested with the rolling release #8f87fbb (2022-01-09 11:38)
