### ISSUE TITLE
File processing not working

### ISSUE THREAD

**Issue by d-trax** [AzuraCast/AzuraCast#4985]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.0

### What happened?

Hi there, 
installed Azuracast 0.15.0 with Ansible, and now everything seems to be working, except that it doesn't process my music files, which are on my USB HD. I am pretty sure that there aren't any corrupted music files, because with Azuracast 0.14.1 there weren't any problems at all. Tried to upload some songs with drag/drop and they were immediately processed. 
I ran all the debugers with no change to the file processing. Looked all the logs, but there isn't anything pointing to file processing error. 
Tried to manualy process them, but they are added to queue and nothing happens.

**Comment by SC2Mitch** [comment]
Are all the files broken? Or just specific ones. We do have some debug tools at `admin/debug`. Can you check this area and see if any files are still 'processing'?

**Comment by d-trax** [comment]
As I mentioned, tried all the debugers with nothing happening. I doubt that there are corupted files, because all of them were working fine 3 days ago with Azuracast 0.14.1. One thing that I saw was a weird error on the PHP log about Redis that stopped working, but after reboot my logs are no longer there. This issue happened to me with the stable and with the rolling release... It's a PI 4 (4gb) running Ubuntu 20.4.3 LTS with everything up to date.

**Comment by SlvrEagle23** [comment]
@d-trax On the System Debugger page, do you see any outstanding message queue items that are going unprocessed?

On that same page, it may be worth looking at the individual sync tasks to see if one isn't running, and if there is a reason for that.

**Comment by d-trax** [comment]
All the debuggers seems to be working. 
<img width="1114" alt="Screen Shot 2022-01-15 at 10 13 13 AM" src="https://user-images.githubusercontent.com/31935215/149614817-3dda0c66-eca8-4329-ba1c-f176093f008f.png">
Here are the messages queues. How can I see what are theese messages about? Here are my logs after the last reboot. 
<img width="836" alt="Screen Shot 2022-01-15 at 10 15 44 AM" src="https://user-images.githubusercontent.com/31935215/149614875-fe3bf82a-6f17-4163-a596-c3b1c17901fa.png">
<img width="861" alt="Screen Shot 2022-01-15 at 10 15 55 AM" src="https://user-images.githubusercontent.com/31935215/149614877-6c1cbe1b-3e89-493d-92d5-d3f0f982627c.png">
<img width="846" alt="Screen Shot 2022-01-15 at 10 16 05 AM" src="https://user-images.githubusercontent.com/31935215/149614878-c1739a59-ad25-4904-b075-e050c2c7c17d.png">
<img width="838" alt="Screen Shot 2022-01-15 at 10 17 27 AM" src="https://user-images.githubusercontent.com/31935215/149614910-60f25834-a646-4b40-b8ab-265d30709412.png">

**Comment by SlvrEagle23** [comment]
@d-trax I don't think that indicates a "running state" like you might be thinking...it looks like there are several hundred thousand records pending processing on the "Media" queue. That indicates how many records have _yet_ to be processed by the system.

I think in your case, the message queue processor simply isn't processing things. It could be that the queue is actually too large for it to even handle, though I don't think that's what's happening.

Can you confirm that the queue is at least going down at all over time?

**Comment by d-trax** [comment]
Oh, forgot that. My media files are around 2000. I believe the system adds them to the processing queue when the '**App\Sync\Task\CheckMediaTask**'  task is run. They are now 39k and the task was ran 2 minutes ago.

**Comment by d-trax** [comment]
<img width="499" alt="Screen Shot 2022-01-15 at 10 45 40 AM" src="https://user-images.githubusercontent.com/31935215/149615749-2bde1ac3-8481-407d-bdbe-c276e426053b.png">

This is what I get from the messages.

**Comment by SlvrEagle23** [comment]
@d-trax The weird thing is it seems to be queueing up the same tracks over and over...not sure why it's doing that. The system should be looking through the queue and not re-queueing anything that's already in the queue.

By chance, do you have more than one Storage Location pointing to the same actual path?

**Comment by d-trax** [comment]
No, it's only one location /data/Music. Never had any issues regarding location with older Azuracast versions, thus I got to experimenting several months ago with Liquidsoap, which made me reinstall Ubuntu like 20 times and every time I point out the music folder it processes all the music within 2 hours tops.

**Comment by SlvrEagle23** [comment]
@d-trax I've made some changes to that overlap handling...you may want to update, then make sure your media queue is fully cleared, and then let the media sync task run again; this time it shouldn't pile up like that.

**Comment by d-trax** [comment]
Doing it right away. I will also install Ubuntu on my AMD machine and will install Azuracast just to be sure if this is an issue with ARM architecture. Will get back with the results later.

**Comment by d-trax** [comment]
Got stuck again on while updating
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package(s) matching 'php5-*' available"}`

**Comment by SC2Mitch** [comment]
I believe that issue was fixed in the rolling release.

**Comment by d-trax** [comment]
I updated finaly after some struggle again.. Problem persists. Media files are not processing and they keep adding to media queue.

**Comment by SlvrEagle23** [comment]
@d-trax Found a possible cause of this issue; try updating again and it should start processing again.

**Comment by d-trax** [comment]
Hi again, sorry for the late reply, but again I was having issues. I just can't seem to update, neither with `./update.sh` or `update.sh --full`. It allways breaks, so I install a fresh copy of Ubuntu 20.4.3 LTS and start over. Last couple of days that way doesn't work for me anymore, as it installs, but I get the `Slim Application Error`. Installer finishes everything except that it ignores some errors. Here are the errors themselves:

```
TASK [azuracast-db-install : MariaDB Cleanup] ************************************************************************************************************
ok: [localhost] => (item=DELETE FROM mysql.user WHERE User='')
ok: [localhost] => (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1'))
failed: [localhost] (item=DROP DATABASE test) => {"ansible_loop_var": "azure_db_install_sql_cleanup_query", "azure_db_install_sql_cleanup_query": "DROP DATABASE test", "changed": false, "cmd": ["mysql", "--defaults-extra-file=/root/.my.cnf", "-ne", "DROP DATABASE test"], "delta": "0:00:00.021424", "end": "2022-01-18 14:32:22.178715", "msg": "non-zero return code", "rc": 1, "start": "2022-01-18 14:32:22.157291", "stderr": "ERROR 1008 (HY000) at line 1: Can't drop database 'test'; database doesn't exist", "stderr_lines": ["ERROR 1008 (HY000) at line 1: Can't drop database 'test'; database doesn't exist"], "stdout": "", "stdout_lines": []}
ok: [localhost] => (item=DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%')
...ignoring




TASK [redis : Enable and restart all core services] ******************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'item' is undefined\n\nThe error appears to be in '/var/azuracast/www/util/ansible/roles/redis/tasks/main.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Enable and restart all core services\n  ^ here\n"}
...ignoring
```

**Comment by SlvrEagle23** [comment]
I think our enthusiastic pull-requester who wanted to fix our Ansible setup may have wound up breaking it. I'm going to revert the earlier commit to the Ansible code and re-review it line by line.

**Comment by d-trax** [comment]
@SlvrEagle23 is there a way to install version 0.14.1 just to have something for my listeners? I can continue testing on my other Raspberry Pi with the new version of Azuracast. No disrespect, I love your work!

**Comment by SlvrEagle23** [comment]
@d-trax I was able to fix some Ansible bugs, you may be able to just try updating again.

Long story short, it's not straightforward to run a non-current version of AzuraCast on Ansible. Possible on Docker, but not really on Ansible. It also doesn't help us even a little when users panic because there are issues, and instead of helping us work through them, they revert to an older version. It's impossible for us to move forward when that happens, and trust me, it's apparently the first instinct of literally all of our users.

**Comment by d-trax** [comment]
@SlvrEagle23 I can confirm that both update methods work now. Also the File processing issue is now gone. Everything seems to be working except the Scheduled Playlists.
If I schedule a playlist to play and stop on specific time, all that is streamed is the welcome message of Azuracast. I added a test playlist with no schedule and it started streaming right away. On the Liquidsoap log I see some errors regarding the playlists.
I ran all the debuggers, but they made no change.
p.s. my time zone is set correctly on the Ubuntu system and the radio station.

```
2022/01/19 13:25:08 [playlist_4__thursday:3] Couldn't read playlist: request resolution failed.
2022/01/19 13:25:08 [playlist_3__wednesday:3] Reloading playlist with URI /var/azuracast/stations/d-traxs_streaming_service/playlists/playlist_3._wednesday.m3u.
2022/01/19 13:25:08 [request:3] Nonexistent file or ill-formed URI "/var/azuracast/stations/d-traxs_streaming_service/playlists/playlist_3._wednesday.m3u"!
2022/01/19 13:25:08 [playlist_3__wednesday:3] Couldn't read playlist: request resolution failed.
```
here are the playlists permissions on the station's directory
![Screenshot 2022-01-19 133722](https://user-images.githubusercontent.com/31935215/150122559-fac7a315-e954-4a8e-95f7-499f273dc7b8.png)

**Comment by d-trax** [comment]
Sorry for the spam, but I found what's causing the issue. It's not the scheduler, but the `Interrupt other songs to play at scheduled time.` feature :)

**Comment by SC2Mitch** [comment]
OP confirms the issue is fixed, closing. Any other issues, create a new issue thread :)

**Comment by cloudbolwell** [comment]
I believe I am facing the same issue as OP however I am running docker on synology and after updating none of the files process after trying to run the synchronization task App\Sync\Task\CheckMediaTask I hit a 502 Bad Gateway I have uninstalled and reinstalled to no effect I have tried both stable and rolling releases same issue if I change the media directory back to default and delete the docker-compose.override.yml restart everything and upload via SFTP to browser they process again

**Comment by pacija** [comment]
I had the same issue, resolved by `./update.sh --full`. I noticed albumart wasn't displayed in "Music Files". `.albumart` was `700 azuracast:azuracast`, files inside were `664 azuracast:azuracast`, so I concluded problem is due web server being unable to access files because of incorrect folder permissions. Chaniging `.albumart` to `755 azuracast:azuracast` resulted in albumart being correctly displayed in "Music Folders".
