### ISSUE TITLE
WebDJ returns Error × Live stream disconnected when attempting to connect

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#5076]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #fef3932

### What happened?

Replicated on both the demo and local machine, after creating an account, you are unable to connect to the WebDJ, it returns a 

```
Error
×
Live stream disconnected.
```
Nothing in the Liquidsoap logs is even picked up. Video of the issue - https://streamable.com/epojbp

### Relevant log output

```shell
None
```

**Comment by SlvrEagle23** [comment]
@SC2Mitch Can you verify that this was fixed by the latest Liquidsoap push in rolling?

**Comment by SC2Mitch** [comment]
@SlvrEagle23 ![image](https://user-images.githubusercontent.com/29955942/152703581-f6487118-9002-4ef8-951e-f85eb48812dc.png)
On the demo machine, still not working.

**Comment by Vaalyn** [comment]
On my test installation (and local dev installation) on the latest Rolling-Release the WebDJ works without a problem.

On the demo installation this probably doesn't work because there the DJ Streamers feature is disabled by default and when you enable it you have to restart Liquidsoap. Which you can't do with the demo user since that one does not have the required permissions for it. So the input socket on the LS side does not exist there.

Maybe we should revisit the default permissions of the demo user in general to make sure that people can test all the important station related feature on the demo installation.

**Comment by SC2Mitch** [comment]
Very strange, seems to be cleared up on the latest release, unsure why it was throwing the error.

**Comment by Ignacio1972** [comment]
Hi Guys, always surprised for such a great platform. Thank you so much.
I having the same problem with WebDj  "Live Stream Disconnected" Any help would be appreciated.
v0.17.0 Stable • Docker • PHP 8.1
Love

[Radioislanegra](https://radioislanegra.com/)

![Screen Shot 2022-07-02 at 4 18 11 PM](https://user-images.githubusercontent.com/66499077/177015108-885285b6-6f6f-4496-8e41-abd2ac64c180.png)

**Comment by ramindas** [comment]
Hi Guys, try streamer account password without special characters..
