### ISSUE TITLE
No more access to icecast page since 0.15.2

### ISSUE THREAD

**Issue by matthieudraft** [AzuraCast/AzuraCast#5168]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#59e17bf

### What happened?

Hi

Since the 0.15.2update, I can no longer access the icecast page with the list of mount points.
No problem accessing the web interface (port 80 and 443).
But as soon as I want to access the icecast server or simply play the radio (port 9030), nothing helps.
I have no problem streaming to the server either (port 8005).

This configuration worked perfectly on version 0.15.0 and no longer works at all since version 0.15.2

There doesn't seem to be any error on the let's encrypt certificate side
And the ports are open on the side of my VPS

I appreciate any help as I'm starting to pull my hair out...

Regards,
Matthieu Lechevallier

**Comment by gunsar** [comment]
link streaming only  :
https://sub.domain.com/radio/port/moutnpoint

icecast page only :
https://sub.domain.com/radio/port/

==========================

this is no longer valid in the new version
https://sub.domain.com:port/moutnpoint
https://sub.domain.com:port
must be an error

**Comment by matthieudraft** [comment]
Why such a change ?
It worked in update 0.15.0. But not since 0.15.2
This is quite annoying. Because our radios are referenced on many platforms with the address domain_name:port
This change would require us to update the address of our streams on all platforms.

**Comment by SlvrEagle23** [comment]
@matthieudraft We haven't changed anything to disable direct port access to Icecast. That should be functioning exactly as it did before. We've fixed some bugs relating to LetsEncrypt with direct port access, however.

Your port is 9030, which is a nonstandard port...I would be interested to see if you've configured AzuraCast to use that custom port number, because it has to be told about that port range in order to clear it through Docker. You should have the "customize ports" option when running the updater or installer.

**Comment by matthieudraft** [comment]
@SlvrEagle23 
Really strange.
I just did a fresh install from scratch.
I actually use port 9030 which is not a standard port. But that's because for the ten years we've had audio streams, we've always had port 9030.
So when we change server, we don't need to do SEO again.
When installing this Azuracast distribution (I installed the rolling release this time), I customized the ports well.
They are also open in my VPS firewall rules.

In my next test, I go back to port 8000

**Comment by matthieudraft** [comment]
@SlvrEagle23 
the behavior with port 8000 seems quite different to me. But still not satisfactory.
My instance is located here: https://test.ouest-track.com
> I can stream to ports 8000 and 8005 with no problem
> I can read the stream with the address http://test.ouest-track.com:8000/stream but not in https
> I can access the icecast page with the address http://212.227.190.250:8000/ but not with the address http://test.ouest-track.com:8000, neither in https

**Comment by matthieudraft** [comment]
it seems that there is two different problems.
- with the non standard ports
- with the ssl

**Comment by SlvrEagle23** [comment]
@matthieudraft We did fix the SSL issue in a newer rolling release version, so updating may help with that.

**Comment by matthieudraft** [comment]
@SlvrEagle23 
I'm using the latest rolling release : Rolling Release #[59e17bf]

**Comment by matthieudraft** [comment]
is it possible to backup to a 0.15.0 install ?

**Comment by gunsar** [comment]
> @matthieudraft We did fix the SSL issue in a newer rolling release version, so updating may help with that.

how to install the previous version? for example version 15.1, 15.0, 14.x and others

**Comment by matthieudraft** [comment]
Unfortunately, it doesn't seem to be possible...
I've been tearing my hair out for a week because of the update from 0.15.0 to 0.15.2
This made my radio offline for more than 6 hours this Friday.

I also accidentally erased the machine backups by reinstalling a clean system image.

Now I would so love to roll back to 0.15.0 or have this bug acknowledged and fixed.

The answer to not being able to go back can be found here:
https://github.com/AzuraCast/AzuraCast/discussions/3873#discussioncomment-437088

**Comment by SC2Mitch** [comment]
I'll flag this as a possible bug and look into it, have some patience please, it's been 1 day and we have other bug reports or features to work on.

**Comment by walterdevos** [comment]
After updating to the latest stable version ( v0.15.2 Stable ) I also ran into trouble with Icecast custom ports:

First got "Certificate Error" on the custom port.
The I did 
 docker-compose down
 docker-compose up -d
But that made the page not load at all. "This site can't be reached" ERR_CONNECTION_CLOSED  error

It stayed like that, even after full reboot of the server.

**What worked for me ** however was what is said in https://github.com/AzuraCast/AzuraCast/issues/3764

Go to each station via "Manage" , then on the modal Broadcasting Service , click : Restart.

**Comment by Vaalyn** [comment]
This is actually a bug that I already fixed in rolling-release, namely that the Icecast configuration is not automatically re-generated when the SSL certificate is renewed. Before the removal of the dedicated Let's Encrypt containers the cert files were using `default.crt` and `default.key` as file names, now that is `ssl.crt` and `ssl.key`.

**Comment by matthieudraft** [comment]
> Après la mise à jour vers la dernière version stable (v0.15.2 Stable), j'ai également rencontré des problèmes avec les ports personnalisés Icecast :
> 
> J'ai d'abord obtenu "Erreur de certificat" sur le port personnalisé. J'ai donc fait _docker-compose down docker-compose up -d_ Mais cela a empêché la page de se charger du tout. Erreur "Ce site est inaccessible" ERR_CONNECTION_CLOSED
> 
> Il est resté comme ça, même après un redémarrage complet du serveur.
> 
> **Ce qui a fonctionné pour moi ** était cependant qu'est-ce que c'est :
> 
> Rendez-vous sur chaque station via "Gérer", puis sur le service de diffusion modal, cliquez sur : Redémarrer.
> 
> Cela semble ouvrir le port personnalisé au monde extérieur. C'est peut-être un bogue dans le script de mise à jour ou une migration oubliée.

Unfortunatly, it doesn't work for me

**Comment by matthieudraft** [comment]
> Il s'agit en fait d'un bug que j'ai déjà corrigé en rolling-release, à savoir que la configuration d'Icecast n'est pas automatiquement régénérée lors du renouvellement du certificat SSL. Avant la suppression des conteneurs Let's Encrypt dédiés, les fichiers cert utilisaient `default.crt`et `default.key`comme noms de fichiers, maintenant c'est `ssl.crt`et `ssl.key`.

Hi Vaalyn,

I've already install #[59e17bf](https://github.com/AzuraCast/AzuraCast/commit/59e17bf4280ec8876e2ffb91ce41326c277f90d8) Rolling Release.
But it doesn't work. Ports are well opened in my firewall and domain is correctly redirected.
Is there a way to fix this issue ? (in reality, two issues : icecast custom port and SSL certificate
Regards
Matthieu

**Comment by SlvrEagle23** [comment]
Fortunately I can close this issue now, as we've been able to get this installation back up and running again.

Part of the issue was due to issues with AzuraCast's code that are now fixed in the latest rolling-release version.

If you ever find that your custom port mapping isn't taking effect any more, you can reset it by, during the update process, answering "Yes" to the question of whether you want to modify installation settings, then setting the station port range again. This will rewrite the configuration file and should fix things up.
