### ISSUE TITLE
liq_cross_duration="0.00" returns Cannot set crossfade duration to negative value

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#5328]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ed13d78 (2022-04-29 13:54)

### What happened?

Liquidsoap Log running full with crossfade duration error. Seems to be an Liquidsoap related error. https://github.com/savonet/liquidsoap/issues/2349#issuecomment-1111477422

### Relevant log output

```shell
2022/04/30 15:25:58 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:58 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:58 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:58 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:58 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:58 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:58 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:58 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/04/30 15:25:59 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
```

**Comment by SC2Mitch** [comment]
Should be fixed on the latest stable branch.

**Comment by LordHelmchen666** [comment]
Sorry i have to say it is not fixed for me. Updated to 0.16.1 stable error still exists, then to latest rolling release also same error.
`2022/05/06 14:33:02 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 14:33:02 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 14:33:02 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 14:33:02 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 14:33:02 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 14:33:02 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 14:33:02 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 14:33:02 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 14:33:02 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!`

Doing a complete reinstall also didn't help. :-(

**Comment by LordHelmchen666** [comment]
Error is coming back again, but now i know why. It happens only when you have a track with custom setting liq_cross_duration="0.00".

Log track set liq_cross_duration="0.10"
```
2022/05/06 17:35:21 [lang:3] API nextsong - Response (200): annotate:title="Nothilfe Ukraine ",artist="Aktion Deutschland Hilft",duration="30.00",song_id="ff64a1af81f5d291e4f9438cfb32ee49",media_id="6895",liq_amplify="0.00dB",liq_cross_duration="0.10":media:Werbung/radiospot_nothilfe_ukraine_30sek.mp3
[mp3 @ 0x7f403402a1c0] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f4034021c00] Estimating duration from bitrate, this may be inaccurate
2022/05/06 17:35:28 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:9010/api/internal/1/liquidsoap/feedback' with body: {
2022/05/06 17:35:28 [lang:3]   "song_id": "bd4b15e1dbb38638edcd396a4d5fe9f9",
2022/05/06 17:35:28 [lang:3]   "playlist_id": "4",
2022/05/06 17:35:28 [lang:3]   "media_id": "1728"
2022/05/06 17:35:28 [lang:3] }
2022/05/06 17:35:28 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f404459de80] Could not update timestamps for discarded samples.
2022/05/06 17:41:04 [decoder:2] Decoding "/var/azuracast/stations/eisradio/media/Helmut/Rock/10-sick_and_tired.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f4044e53cc0] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f4044e53cc0] Estimating duration from bitrate, this may be inaccurate
2022/05/06 17:41:04 [next_song:3] Prepared "/var/azuracast/stations/eisradio/media/Werbung/radiospot_nothilfe_ukraine_30sek.mp3" (RID 21).
2022/05/06 17:41:04 [cue_next_song:3] Cueing in...
2022/05/06 17:41:04 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:9010/api/internal/1/liquidsoap/nextsong' with body: 
2022/05/06 17:41:04 [cross_0:3] Analysis: -155.361292dB / -14.797379dB (7.48s / 7.48s)
2022/05/06 17:41:04 [crossfade_0:3] No transition: using default.
```
Log same track set liq_cross_duration="0.00"
```
2022/05/06 17:42:45 [lang:3] API nextsong - Response (200): annotate:title="Nothilfe Ukraine ",artist="Aktion Deutschland Hilft",duration="30.00",song_id="ff64a1af81f5d291e4f9438cfb32ee49",media_id="6895",liq_amplify="0.00dB",liq_cross_duration="0.00":media:Werbung/radiospot_nothilfe_ukraine_30sek.mp3
[mp3 @ 0x7f403c079b00] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f403c01a100] Estimating duration from bitrate, this may be inaccurate
2022/05/06 17:42:45 [lang:3] API feedback - Response (200): true
2022/05/06 17:46:28 [decoder:2] Decoding "/var/azuracast/stations/eisradio/media/Helmut/Sampler/Bravo Hits/Bravo Hits Vol. 109/CD2/03. BENEE & Gus Dapperton - Supalonely.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f4045dfaac0] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f4045dfaac0] Estimating duration from bitrate, this may be inaccurate
2022/05/06 17:46:28 [next_song:3] Prepared "/var/azuracast/stations/eisradio/media/Werbung/radiospot_nothilfe_ukraine_30sek.mp3" (RID 26).
2022/05/06 17:46:29 [cue_next_song:3] Cueing in...
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Analysis: -79.245266dB / -69.619624dB (0.04s / 0.04s)
2022/05/06 17:46:29 [crossfade_0:3] new >= old + margin, old <= medium and new <= high.
2022/05/06 17:46:29 [crossfade_0:3] Do not fade if it's already very low.
2022/05/06 17:46:29 [crossfade_0:3] Transition: crossed, no fade.
2022/05/06 17:46:29 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:9010/api/internal/1/liquidsoap/nextsong' with body: 
2022/05/06 17:46:29 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:9010/api/internal/1/liquidsoap/feedback' with body: {
2022/05/06 17:46:29 [lang:3]   "song_id": "ff64a1af81f5d291e4f9438cfb32ee49",
2022/05/06 17:46:29 [lang:3]   "playlist_id": "",
2022/05/06 17:46:29 [lang:3]   "media_id": "6895"
2022/05/06 17:46:29 [lang:3] }
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
2022/05/06 17:46:29 [cross_0:3] Cannot set crossfade duration to negative value 0.000000!
....
```

**Comment by SC2Mitch** [comment]
Thanks, will raise it to Liquidsoap and see if they can have a look.

**Comment by SC2Mitch** [comment]
Fixed upstream, will be fixed in the next stable branch, no ETA on that.
