### ISSUE TITLE
Ansible install/update fails on MariaDB stage, unable to connect to database 

### ISSUE THREAD

**Issue by KoneSV** [AzuraCast/AzuraCast#5470]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

I can not install, from here it does not advance:

### Relevant log output

```shell
TASK [azuracast-db-install : MariaDB Cleanup] **************************************************************************************************************************
failed: [localhost] (item=DELETE FROM mysql.user WHERE User='') => {"ansible_loop_var": "azure_db_install_sql_cleanup_query", "azure_db_install_sql_cleanup_query": "DELETE FROM mysql.user WHERE User=''", "changed": false, "cmd": ["mysql", "--defaults-extra-file=/root/.my.cnf", "-ne", "DELETE FROM mysql.user WHERE User=''"], "delta": "0:00:00.017771", "end": "2022-06-07 20:30:09.647063", "msg": "non-zero return code", "rc": 1, "start": "2022-06-07 20:30:09.629292", "stderr": "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)", "stderr_lines": ["ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)"], "stdout": "", "stdout_lines": []}
failed: [localhost] (item=DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')) => {"ansible_loop_var": "azure_db_install_sql_cleanup_query", "azure_db_install_sql_cleanup_query": "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')", "changed": false, "cmd": ["mysql", "--defaults-extra-file=/root/.my.cnf", "-ne", "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"], "delta": "0:00:00.014620", "end": "2022-06-07 20:30:09.998378", "msg": "non-zero return code", "rc": 1, "start": "2022-06-07 20:30:09.983758", "stderr": "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)", "stderr_lines": ["ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)"], "stdout": "", "stdout_lines": []}
failed: [localhost] (item=DROP DATABASE test) => {"ansible_loop_var": "azure_db_install_sql_cleanup_query", "azure_db_install_sql_cleanup_query": "DROP DATABASE test", "changed": false, "cmd": ["mysql", "--defaults-extra-file=/root/.my.cnf", "-ne", "DROP DATABASE test"], "delta": "0:00:00.015256", "end": "2022-06-07 20:30:10.373803", "msg": "non-zero return code", "rc": 1, "start": "2022-06-07 20:30:10.358547", "stderr": "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)", "stderr_lines": ["ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)"], "stdout": "", "stdout_lines": []}
failed: [localhost] (item=DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%') => {"ansible_loop_var": "azure_db_install_sql_cleanup_query", "azure_db_install_sql_cleanup_query": "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'", "changed": false, "cmd": ["mysql", "--defaults-extra-file=/root/.my.cnf", "-ne", "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"], "delta": "0:00:00.024290", "end": "2022-06-07 20:30:10.759858", "msg": "non-zero return code", "rc": 1, "start": "2022-06-07 20:30:10.735568", "stderr": "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)", "stderr_lines": ["ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [azuracast-db-install : Set up AzuraCast database user] ***********************************************************************************************************
[WARNING]: Module did not set no_log for update_password
fatal: [localhost]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\")"}

RUNNING HANDLER [azuracast-user : send user notification] **************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=81   changed=65   unreachable=0    failed=1    skipped=4    rescued=0    ignored=3
```

**Comment by SC2Mitch** [comment]
Thanks for the report, flagged up to the team, bare with us.

**Comment by KoneSV** [comment]
Install version 0.16.1 and it worked fine, that means that the latest version has the error

**Comment by SlvrEagle23** [comment]
Fixed in the latest Rolling Release. Thank you for the report!

**Comment by potatoru** [comment]
I still have this issue with the latest AzuraCast and clean Ubuntu install.
