### ISSUE TITLE
Latest rolling release killed Letsencrypt

### ISSUE THREAD

**Issue by Countryman98** [AzuraCast/AzuraCast#5482]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Run latest Docker Rolling release update. Letsencrypt no longer working and has disabled complete panel access..
Restored backup which did not resolve issue and somehow unfortunately deleted 21,000 audio files :(
Has previously been running letsencrypt with no issues.

### Relevant log output

```shell
azuracast |
azuracast |  [OK] Local cache flushed.
azuracast |
azuracast | Getting account info
azuracast | Initializing ACME v2 environment: https://acme-v02.api.letsencrypt.org/directory
azuracast | Using cURL
azuracast |   https://acme-v02.api.letsencrypt.org/directory [200] (0.49s)
azuracast | Initialized
azuracast |   https://acme-v02.api.letsencrypt.org/acme/new-nonce [200] (0.16s)
azuracast | 2022-06-10 16:29:29,535 INFO success: php-nowplaying entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
azuracast |   https://acme-v02.api.letsencrypt.org/acme/new-acct [200] (0.17s)
azuracast | AccountID: https://acme-v02.api.letsencrypt.org/acme/acct/582655006
azuracast | Account info retrieved
azuracast | Creating Order
azuracast |   https://acme-v02.api.letsencrypt.org/acme/new-order [201] (0.23s)
azuracast | Order created: https://acme-v02.api.letsencrypt.org/acme/order/582655006/96542584096
azuracast | Fetching authorization 1 of 1
azuracast |   https://acme-v02.api.letsencrypt.org/acme/authz-v3/118202171416 [200] (0.17s)
azuracast | Triggering challenge callback for mydomain.live using http-01
azuracast | Notifying server for validation of mydomain.live
azuracast |   https://acme-v02.api.letsencrypt.org/acme/chall-v3/118202171416/nn_IBQ [200] (0.18s)
azuracast | Waiting for server challenge validation
azuracast | [2022-06-10T16:29:30.437072+00:00] AzuraCast.ERROR: HTTP client GET call to http://127.0.0.1:8000/admin.cgi?sid=1&mode=viewxml&page=7 produced response NULL [] {"station":{"id":1,"name":"My Radio Station"}}
azuracast | [2022-06-10T16:29:30.438376+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to 127.0.0.1 port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:8000/admin.cgi?sid=1&mode=viewxml&page=7 [] {"station":{"id":1,"name":"My Radio Station"}}
azuracast | [2022-06-10T16:29:30.439583+00:00] AzuraCast.ERROR: HTTP client GET call to http://127.0.0.1:8000/admin.cgi?sid=2&mode=viewxml&page=7 produced response NULL [] {"station":{"id":1,"name":"My Radio Station"}}
azuracast | [2022-06-10T16:29:30.440444+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to 127.0.0.1 port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://127.0.0.1:8000/admin.cgi?sid=2&mode=viewxml&page=7 [] {"station":{"id":1,"name":"My Radio Station"}}
azuracast | [2022-06-10T16:29:30.441275+00:00] AzuraCast.ERROR: HTTP client GET call to http://127.0.0.1:8000/admin.cgi?sid=3&mode=viewxml&page=7 produced response NULL [] {"station":{"id":1,"name":"My Radio Station"}}
azuracast | [2022-06-10T16:29:30.442136+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to 127.0.0.1 port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by Vicinis** [comment]
@Countryman98 just installed 0a30648 and it works fine for me

**Comment by SC2Mitch** [comment]
Should be fixed in the latest rolling

**Comment by Countryman98** [comment]
> Should be fixed in the latest rolling

Yeah, nah still not fixed for me, fresh install, reinstall backup.. no ssl
