### ISSUE TITLE
Upgrading to the latest stable version

### ISSUE THREAD

**Issue by iplayradionetworks** [AzuraCast/AzuraCast#5540]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.16

### What happened?

After following instructions to update to the latest version of Azuracast stable, the radio streams were able to start normally but no access to radio control panel which only shows 502 gateway error.

I have attached some logs below and also my current docker-compose.yml file which could be incorrect. 
[docker-compose.zip](https://github.com/AzuraCast/AzuraCast/files/8986468/docker-compose.zip)

Keep in mind that i want to offer ports 8000-9999 to all clients. Not sure how to handle the ports for webdj feature. 
Should i for instance offer normal port range 8000-9000 and then have 9005-9999 for webdj ? 

Best regards
Jim

### Relevant log output

```shell
azuracast  | [2022-06-26T10:36:01.723449+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mariadb failed: Name or service not known (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:sync:run` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mariadb failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mariadb failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mariadb failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo for mariadb failed: Name or service not known at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
azuracast  | [2022-06-26T10:36:01.725548+00:00] AzuraCast.WARNING: Console command `azuracast:sync:run` exited with error code 2002. [] []
azuracast  |
azuracast  | In ExceptionConverter.php line 103:
azuracast  |
azuracast  |   An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_get
azuracast  |   addresses: getaddrinfo for mariadb failed: Name or service not known
azuracast  |
azuracast  |
azuracast  | In Exception.php line 30:
azuracast  |
azuracast  |   SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mariadb fa
azuracast  |   iled: Name or service not known
azuracast  |
azuracast  |
azuracast  | In Driver.php line 28:
azuracast  |
azuracast  |   SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for mariadb fa
azuracast  |   iled: Name or service not known
azuracast  |
azuracast  |
azuracast  | In Driver.php line 28:
azuracast  |
azuracast  |   PDO::__construct(): php_network_getaddresses: getaddrinfo for mariadb faile
azuracast  |   d: Name or service not known
azuracast  |
azuracast  |
azuracast  | azuracast:sync:run
azuracast  |
azuracast  | 2022/06/26 10:36:02 [crit] 109#109: *28224 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/9/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:03 [crit] 109#109: *28226 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/29/liquidsoap/feedback HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:04 [crit] 109#109: *28228 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/24/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:04 [crit] 109#109: *28230 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/25/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:04 [crit] 109#109: *28232 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/1/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:04 [crit] 109#109: *28234 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/21/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:04 [crit] 109#109: *28236 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/31/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:05 [crit] 109#109: *28238 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/2/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:07 [crit] 109#109: *28240 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/29/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:09 [crit] 109#109: *28242 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/17/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:12 [crit] 109#109: *28244 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/9/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast  | 2022/06/26 10:36:14 [crit] 109#109: *28246 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/24/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
```

**Comment by SlvrEagle23** [comment]
@iplayradionetworks Do you have something in `azuracast.env` that customizes your MariaDB installation location? If you change `MYSQL_HOST` in that environment file to be `localhost`, it should fix this.

**Comment by iplayradionetworks** [comment]
> @iplayradionetworks Do you have something in `azuracast.env` that customizes your MariaDB installation location? If you change `MYSQL_HOST` in that environment file to be `localhost`, it should fix this.

Good morning 

Ok I shall so that. Nevertheless I think I managed to fix it. Somehow there was a conflict of ports as docker was active in background and was keeping all ports in use. So AzuraCast couldn't start. 

Best regards
Jim

**Comment by iplayradionetworks** [comment]
> If thats the case I'll close this then, if this is still an issue, let me know. 

You may close it . Thank you for the great support.  

Best regards
Jim

**Comment by ratarasta** [comment]
> > @iplayradionetworks Do you have something in `azuracast.env` that customizes your MariaDB installation location? If you change `MYSQL_HOST` in that environment file to be `localhost`, it should fix this.
> 
> Good morning
> 
> Ok I shall so that. Nevertheless I think I managed to fix it. Somehow there was a conflict of ports as docker was active in background and was keeping all ports in use. So AzuraCast couldn't start.
> 
> Best regards Jim

I have the same problem, how did you stop docker from running in the background... I havent been able to start my stations yet

**Comment by iplayradionetworks** [comment]
> > > @iplayradionetworks Do you have something in `azuracast.env` that customizes your MariaDB installation location? If you change `MYSQL_HOST` in that environment file to be `localhost`, it should fix this.
> > 
> > Good morning
> > 
> > Ok I shall so that. Nevertheless I think I managed to fix it. Somehow there was a conflict of ports as docker was active in background and was keeping all ports in use. So AzuraCast couldn't start.
> > 
> > Best regards Jim
> 
> I have the same problem, how did you stop docker from running in the background... I havent been able to start my stations yet

Well you stop docker at first. And then you start docker again.  After you start docker then you launch azuracast with it's run command. 

Jim

**Comment by ratarasta** [comment]
> > > > @iplayradionetworks Do you have something in `azuracast.env` that customizes your MariaDB installation location? If you change `MYSQL_HOST` in that environment file to be `localhost`, it should fix this.
> > > 
> > > 
> > > Good morning
> > > Ok I shall so that. Nevertheless I think I managed to fix it. Somehow there was a conflict of ports as docker was active in background and was keeping all ports in use. So AzuraCast couldn't start.
> > > Best regards Jim
> > 
> > 
> > I have the same problem, how did you stop docker from running in the background... I havent been able to start my stations yet
> 
> Well you stop docker at first. And then you start docker again. After you start docker then you launch azuracast with it's run command.
> 
> Jim

thanks for the reply Jim, I guess that is my question, how do I know Docker is running in the background and what line do I need to use to stop it? 
Tried installing AzuraCast it a few times with no luck

**Comment by ratarasta** [comment]
In ExceptionConverter.php line 103:
                                                                               
  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or  
   directory                                                                   
                                                                               

In Exception.php line 28:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In Driver.php line 28:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

azuracast:setup [--update] [--load-fixtures] [--release]

[+] Running 1/1
 ⠿ Container azuracast  Started                                            2.2s
Clean up all stopped Docker containers and images to save space? [Y/n] y
Deleted Networks:
azuracast_installer_default

Total reclaimed space: 0B
Update complete!
root@localhost:/var/azuracast#

**Comment by ItsMitchh** [comment]
If your having a issue with AzuraCast, create a new issue please.

**Comment by ratarasta** [comment]
> If your having a issue with AzuraCast, create a new issue please.
Same issue Mitchhh

**Comment by qadirbakhsh** [comment]
> In ExceptionConverter.php line 103:
> 
> An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory
> 
> In Exception.php line 28:
> 
> SQLSTATE[HY000] [2002] No such file or directory
> 
> In Driver.php line 28:
> 
> SQLSTATE[HY000] [2002] No such file or directory
> 
> azuracast:setup [--update] [--load-fixtures] [--release]
> 
> [+] Running 1/1 ⠿ Container azuracast Started 2.2s Clean up all stopped Docker containers and images to save space? [Y/n] y Deleted Networks: azuracast_installer_default
> 
> Total reclaimed space: 0B Update complete! root@localhost:/var/azuracast#

having the same issue.

**Comment by BusterNeece** [comment]
@qadirbakhsh I've made some updates as of the last hour or two to the Rolling Release that should fix it. I'd advise you to try updating again to see if it helps.

**Comment by qadirbakhsh** [comment]
> @qadirbakhsh I've made some updates as of the last hour or two to the Rolling Release that should fix it. I'd advise you to try updating again to see if it helps.

The issue still persists.

here is the complete issue.

Database Migrations
===================

[2022-09-17T11:54:28.010227+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\Conn                                                                                                             ectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] No                                                                                                              such file or directory (uncaught exception) at /var/azuracast/www/vendor/doctrin                                                                                                             e/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 101 while running consol                                                                                                             e command `azuracast:setup` {"exception":"[object] (Doctrine\\DBAL\\Exception\\C                                                                                                             onnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY                                                                                                             000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal                                                                                                             /src/Driver/API/MySQL/ExceptionConverter.php:101)\n[previous exception] [object]                                                                                                              (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No                                                                                                              such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO                                                                                                             /Exception.php:28)\n[previous exception] [object] (PDOException(code: 2002): SQL                                                                                                             STATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctr                                                                                                             ine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-09-17T11:54:28.011346+00:00] AzuraCast.WARNING: Console command `azuracast                                                                                                             :setup` exited with error code 2002. [] []

In ExceptionConverter.php line 101:

  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or
   directory


In Exception.php line 28:

  SQLSTATE[HY000] [2002] No such file or directory


In Driver.php line 28:

  SQLSTATE[HY000] [2002] No such file or directory


azuracast:setup [--update] [--load-fixtures] [--release]

ERROR: 255
Creating azuracast ... done
Clean up all stopped Docker containers and images to save space? [Y/n] [ERROR] I                                                                                                             nnoDB: File ./ib_logfile0 was not found
2022-09-17 11:50:54 0 [ERROR] InnoDB: Plugin initialization aborted with error G                                                                                                             eneric error
Clean up all stopped Docker containers and images to save space? [Y/n] Clean up                                                                                                              all stopped Docker containers and images to save space? [Y/n] y
Deleted Networks:
azuracast_installer_default

Total reclaimed space: 0B
Update complete!

**Comment by qadirbakhsh** [comment]
> @qadirbakhsh I've made some updates as of the last hour or two to the Rolling Release that should fix it. I'd advise you to try updating again to see if it helps.

Switched my azuracast instance to the stable release,  and my instance is up now.  Thank You.!!!!
