### ISSUE TITLE
Ansible installation error (Ubuntu 20.04)

### ISSUE THREAD

**Issue by ogrenci01** [AzuraCast/AzuraCast#5551]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

latest

### What happened?

I know there is no support for Ansible. An error occurs at the last stage while installing Azuracast. I think it has to do with SQL. Can you help with the solution?

### Relevant log output

```
fatal: [localhost]: FAILED! => {
  "changed": true,
  "cmd": "php /var/azuracast/www/bin/console azuracast:setup",
  "delta": "0:00:00.174680",
  "end": "2022-06-30 15:49:44.033739",
  "msg": "non-zero return code",
  "rc": 255,
  "start": "2022-06-30 15:49:43.859059",
  "stderr": "[2022-06-30T12:49:44.026074+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245 Stack trace: #0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect() #1 [internal function]: CompiledContainer::{closure}() #2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\CompiledContainer->resolveFactory() #5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11() #6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\CompiledContainer->get() #7 [internal function]: CompiledContainer::{closure}() #8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\CompiledContainer->resolveFactory() #11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12() #12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\CompiledContainer->get() #13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14() #14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get() #15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters() #16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters() #17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\CompiledContainer->resolveFactory() #19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15() #20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\CompiledContainer->get() #21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\Definition\\Reference->resolve() #22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\Definition\\Resolver\\ResolverDispatcher->resolve() #23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\Definition\\Resolver\\ParameterResolver->resolveParameters() #24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\Definition\\Resolver\\ObjectCreator->createInstance() #25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\Definition\\Resolver\\ObjectCreator->resolve() #26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\Definition\\Resolver\\ResolverDispatcher->resolve() #27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\Container->resolveDefinition() #28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\Container->get() #29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get() #30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters() #31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters() #32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\CompiledContainer->resolveFactory() #34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18() #35 /var/azuracast/www/src/AppFactory.php(42): DI\\CompiledContainer->get() #36 /var/azuracast/www/bin/console(13): App\\AppFactory::createCli() #37 {main}   thrown {\"code\":1,\"message\":\"Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245\nStack trace:\n#0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect()\n#1 [internal function]: CompiledContainer::{closure}()\n#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\n#4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\\\CompiledContainer->resolveFactory()\n#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11()\n#6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\\\CompiledContainer->get()\n#7 [internal function]: CompiledContainer::{closure}()\n#8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\n#10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\\\CompiledContainer->resolveFactory()\n#11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12()\n#12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\\\CompiledContainer->get()\n#13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14()\n#14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\\\CompiledContainer->get()\n#15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\\\Invoker\\\\FactoryParameterResolver->getParameters()\n#16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\\\ParameterResolver\\\\ResolverChain->getParameters()\n#17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\n#18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\\\CompiledContainer->resolveFactory()\n#19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15()\n#20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\\\CompiledContainer->get()\n#21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\\\Definition\\\\Reference->resolve()\n#22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\\\Definition\\\\Resolver\\\\ResolverDispatcher->resolve()\n#23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\\\Definition\\\\Resolver\\\\ParameterResolver->resolveParameters()\n#24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\\\Definition\\\\Resolver\\\\ObjectCreator->createInstance()\n#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\\\Definition\\\\Resolver\\\\ObjectCreator->resolve()\n#26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\\\Definition\\\\Resolver\\\\ResolverDispatcher->resolve()\n#27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\\\Container->resolveDefinition()\n#28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\\\Container->get()\n#29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\\\CompiledContainer->get()\n#30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\\\Invoker\\\\FactoryParameterResolver->getParameters()\n#31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\\\ParameterResolver\\\\ResolverChain->getParameters()\n#32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\n#33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\\\CompiledContainer->resolveFactory()\n#34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18()\n#35 /var/azuracast/www/src/AppFactory.php(42): DI\\\\CompiledContainer->get()\n#36 /var/azuracast/www/bin/console(13): App\\\\AppFactory::createCli()\n#37 {main}\n  thrown\",\"file\":\"/var/azuracast/www_tmp/CompiledContainer.php\",\"line\":245,\"trace\":null} []",
  "stderr_lines": [
    "[2022-06-30T12:49:44.026074+00:00] AzuraCast.ALERT: Fatal Error (E_ERROR): Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245 Stack trace: #0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect() #1 [internal function]: CompiledContainer::{closure}() #2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\CompiledContainer->resolveFactory() #5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11() #6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\CompiledContainer->get() #7 [internal function]: CompiledContainer::{closure}() #8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array() #9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\CompiledContainer->resolveFactory() #11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12() #12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\CompiledContainer->get() #13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14() #14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get() #15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters() #16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters() #17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\CompiledContainer->resolveFactory() #19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15() #20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\CompiledContainer->get() #21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\Definition\\Reference->resolve() #22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\Definition\\Resolver\\ResolverDispatcher->resolve() #23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\Definition\\Resolver\\ParameterResolver->resolveParameters() #24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\Definition\\Resolver\\ObjectCreator->createInstance() #25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\Definition\\Resolver\\ObjectCreator->resolve() #26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\Definition\\Resolver\\ResolverDispatcher->resolve() #27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\Container->resolveDefinition() #28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\Container->get() #29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get() #30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters() #31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters() #32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call() #33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\CompiledContainer->resolveFactory() #34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18() #35 /var/azuracast/www/src/AppFactory.php(42): DI\\CompiledContainer->get() #36 /var/azuracast/www/bin/console(13): App\\AppFactory::createCli() #37 {main}   thrown {\"code\":1,\"message\":\"Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245\nStack trace:\n#0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect()\n#1 [internal function]: CompiledContainer::{closure}()\n#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\n#4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\\\CompiledContainer->resolveFactory()\n#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11()\n#6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\\\CompiledContainer->get()\n#7 [internal function]: CompiledContainer::{closure}()\n#8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\n#10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\\\CompiledContainer->resolveFactory()\n#11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12()\n#12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\\\CompiledContainer->get()\n#13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14()\n#14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\\\CompiledContainer->get()\n#15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\\\Invoker\\\\FactoryParameterResolver->getParameters()\n#16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\\\ParameterResolver\\\\ResolverChain->getParameters()\n#17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\n#18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\\\CompiledContainer->resolveFactory()\n#19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15()\n#20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\\\CompiledContainer->get()\n#21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\\\Definition\\\\Reference->resolve()\n#22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\\\Definition\\\\Resolver\\\\ResolverDispatcher->resolve()\n#23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\\\Definition\\\\Resolver\\\\ParameterResolver->resolveParameters()\n#24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\\\Definition\\\\Resolver\\\\ObjectCreator->createInstance()\n#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\\\Definition\\\\Resolver\\\\ObjectCreator->resolve()\n#26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\\\Definition\\\\Resolver\\\\ResolverDispatcher->resolve()\n#27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\\\Container->resolveDefinition()\n#28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\\\Container->get()\n#29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\\\CompiledContainer->get()\n#30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\\\Invoker\\\\FactoryParameterResolver->getParameters()\n#31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\\\ParameterResolver\\\\ResolverChain->getParameters()\n#32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\\\Invoker->call()\n#33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\\\CompiledContainer->resolveFactory()\n#34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18()\n#35 /var/azuracast/www/src/AppFactory.php(42): DI\\\\CompiledContainer->get()\n#36 /var/azuracast/www/bin/console(13): App\\\\AppFactory::createCli()\n#37 {main}\n  thrown\",\"file\":\"/var/azuracast/www_tmp/CompiledContainer.php\",\"line\":245,\"trace\":null} []"
  ],
  "stdout": "\nFatal error: Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245\nStack trace:\n#0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect()\n#1 [internal function]: CompiledContainer::{closure}()\n#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()\n#4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\CompiledContainer->resolveFactory()\n#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11()\n#6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\CompiledContainer->get()\n#7 [internal function]: CompiledContainer::{closure}()\n#8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()\n#9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()\n#10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\CompiledContainer->resolveFactory()\n#11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12()\n#12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\CompiledContainer->get()\n#13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14()\n#14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get()\n#15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters()\n#16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters()\n#17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()\n#18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\CompiledContainer->resolveFactory()\n#19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15()\n#20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\CompiledContainer->get()\n#21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\Definition\\Reference->resolve()\n#22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\Definition\\Resolver\\ResolverDispatcher->resolve()\n#23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\Definition\\Resolver\\ParameterResolver->resolveParameters()\n#24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\Definition\\Resolver\\ObjectCreator->createInstance()\n#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\Definition\\Resolver\\ObjectCreator->resolve()\n#26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\Definition\\Resolver\\ResolverDispatcher->resolve()\n#27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\Container->resolveDefinition()\n#28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\Container->get()\n#29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get()\n#30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters()\n#31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters()\n#32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()\n#33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\CompiledContainer->resolveFactory()\n#34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18()\n#35 /var/azuracast/www/src/AppFactory.php(42): DI\\CompiledContainer->get()\n#36 /var/azuracast/www/bin/console(13): App\\AppFactory::createCli()\n#37 {main}\n  thrown in /var/azuracast/www_tmp/CompiledContainer.php on line 245",
  "stdout_lines": [
    "",
    "Fatal error: Uncaught RedisException: No such file or directory in /var/azuracast/www_tmp/CompiledContainer.php:245",
    "Stack trace:",
    "#0 /var/azuracast/www_tmp/CompiledContainer.php(245): Redis->connect()",
    "#1 [internal function]: CompiledContainer::{closure}()",
    "#2 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()",
    "#3 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()",
    "#4 /var/azuracast/www_tmp/CompiledContainer.php(252): DI\\CompiledContainer->resolveFactory()",
    "#5 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get11()",
    "#6 /var/azuracast/www_tmp/CompiledContainer.php(273): DI\\CompiledContainer->get()",
    "#7 [internal function]: CompiledContainer::{closure}()",
    "#8 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()",
    "#9 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()",
    "#10 /var/azuracast/www_tmp/CompiledContainer.php(278): DI\\CompiledContainer->resolveFactory()",
    "#11 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get12()",
    "#12 /var/azuracast/www_tmp/CompiledContainer.php(288): DI\\CompiledContainer->get()",
    "#13 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get14()",
    "#14 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get()",
    "#15 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters()",
    "#16 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters()",
    "#17 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()",
    "#18 /var/azuracast/www_tmp/CompiledContainer.php(295): DI\\CompiledContainer->resolveFactory()",
    "#19 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get15()",
    "#20 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\\CompiledContainer->get()",
    "#21 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(56): DI\\Definition\\Reference->resolve()",
    "#22 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\\Definition\\Resolver\\ResolverDispatcher->resolve()",
    "#23 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(124): DI\\Definition\\Resolver\\ParameterResolver->resolveParameters()",
    "#24 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\\Definition\\Resolver\\ObjectCreator->createInstance()",
    "#25 /var/azuracast/www/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(61): DI\\Definition\\Resolver\\ObjectCreator->resolve()",
    "#26 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(356): DI\\Definition\\Resolver\\ResolverDispatcher->resolve()",
    "#27 /var/azuracast/www/vendor/php-di/php-di/src/Container.php(136): DI\\Container->resolveDefinition()",
    "#28 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(68): DI\\Container->get()",
    "#29 /var/azuracast/www/vendor/php-di/php-di/src/Invoker/FactoryParameterResolver.php(63): DI\\CompiledContainer->get()",
    "#30 /var/azuracast/www/vendor/php-di/invoker/src/ParameterResolver/ResolverChain.php(31): DI\\Invoker\\FactoryParameterResolver->getParameters()",
    "#31 /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php(58): Invoker\\ParameterResolver\\ResolverChain->getParameters()",
    "#32 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(121): Invoker\\Invoker->call()",
    "#33 /var/azuracast/www_tmp/CompiledContainer.php(356): DI\\CompiledContainer->resolveFactory()",
    "#34 /var/azuracast/www/vendor/php-di/php-di/src/CompiledContainer.php(57): CompiledContainer->get18()",
    "#35 /var/azuracast/www/src/AppFactory.php(42): DI\\CompiledContainer->get()",
    "#36 /var/azuracast/www/bin/console(13): App\\AppFactory::createCli()",
    "#37 {main}",
    "  thrown in /var/azuracast/www_tmp/CompiledContainer.php on line 245"
  ]
}
```

**Comment by SlvrEagle23** [comment]
Fixed in the latest Rolling Release.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23

I tried installing azuracast on a clean Ubuntu 20.04. This problem still persists.

**Comment by ogrenci01** [comment]
Hi @SlvrEagle23 

Azuracast installs with the latest update without any problems. The problem with SQL persists after installation. Azuracast shows Slim Error.

Error Log:

```
[2022-07-02T09:43:46.590641+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1045): An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-07-02T09:43:46.592452+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1045. [] []
[2022-07-02T09:43:46.947895+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []
[2022-07-02T09:43:47.949431+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1045): An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-07-02T09:43:47.950711+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1045. [] []
[2022-07-02T09:43:51.023477+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1045): An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-07-02T09:43:51.024742+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1045. [] []
[2022-07-02T09:43:52.729725+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1045): An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-07-02T09:43:52.730843+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1045. [] []
[2022-07-02T09:43:54.870157+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1045): An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-07-02T09:43:54.871417+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1045. [] []
[2022-07-02T09:43:57.753542+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1045): An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'azuracast'@'localhost' (using password: YES) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-07-02T09:43:57.754676+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1045. [] []
[2022-07-02T09:43:59.097639+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:43:59.099322+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:01.821245+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:01.822678+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:03.543876+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:03.545579+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:06.415420+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:06.417157+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:09.362956+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:09.371077+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:11.363586+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:11.365802+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:14.459148+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:14.460653+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:17.294404+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:17.295853+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:20.294060+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:20.295783+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:23.412171+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:23.413293+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
[2022-07-02T09:44:25.368917+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 51 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 1146): An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:51)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1146): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\n[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azuracast.settings' doesn't exist at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:72)"} []
[2022-07-02T09:44:25.371677+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1146. [] []
```

At the same time, when I want to update, I still get an error.

Error:

```fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /var/azuracast/www/bin/console azuracast:setup --update", "delta": "0:00:00.561617", "end": "2022-07-02 10:50:49.529552", "msg": "non-zero return code", "rc": 255, "start": "2022-07-02 10:50:48.967935", "stderr": "[2022-07-02T07:50:49.516138+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)\"} []\n[2022-07-02T07:50:49.517412+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 2002. [] []\n\nIn ExceptionConverter.php line 103:\n                                                                               \n  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or  \n   directory                                                                   \n                                                                               \n\nIn Exception.php line 30:\n                                                    \n  SQLSTATE[HY000] [2002] No such file or directory  \n                                                    \n\nIn Driver.php line 28:\n                                                    \n  SQLSTATE[HY000] [2002] No such file or directory  \n                                                    \n\nazuracast:setup [--update] [--load-fixtures] [--release]", "stderr_lines": ["[2022-07-02T07:50:49.516138+00:00] AzuraCast.ERROR: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:setup` {\"exception\":\"[object] (Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\\n[previous exception] [object] (Doctrine\\\\DBAL\\\\Driver\\\\PDO\\\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:30)\\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)\"} []", "[2022-07-02T07:50:49.517412+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 2002. [] []", "", "In ExceptionConverter.php line 103:", "                                                                               ", "  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or  ", "   directory                                                                   ", "                                                                               ", "", "In Exception.php line 30:", "                                                    ", "  SQLSTATE[HY000] [2002] No such file or directory  ", "                                                    ", "", "In Driver.php line 28:", "                                                    ", "  SQLSTATE[HY000] [2002] No such file or directory  ", "                                                    ", "", "azuracast:setup [--update] [--load-fixtures] [--release]"], "stdout": "\nAzuraCast Setup\n===============\n\nWelcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...\n\nInitialize AzuraCast\n====================\n\nInitializing essential settings...\n * Environment: Production\n * Installation Method: Ansible\n\n\nRunning Database Migrations\n---------------------------", "stdout_lines": ["", "AzuraCast Setup", "===============", "", "Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...", "", "Initialize AzuraCast", "====================", "", "Initializing essential settings...", " * Environment: Production", " * Installation Method: Ansible", "", "", "Running Database Migrations", "---------------------------"]}```

**Comment by SlvrEagle23** [comment]
@ogrenci01 This is a different error than the original one.

I'm not going to spend any more time on this. Please try to investigate and see if you can figure it out yourself. I need to stick to the message that Ansible is unsupported, or it will take up 100% of our support time, just like it used to. That's why we replaced it.

**Comment by ogrenci01** [comment]
> @ogrenci01 This is a different error than the original one.
> 
> I'm not going to spend any more time on this. Please try to investigate and see if you can figure it out yourself. I need to stick to the message that Ansible is unsupported, or it will take up 100% of our support time, just like it used to. That's why we replaced it.

I'm so sorry for wasting your time. I love Azuracast and its team. I follow with admiration. I am grateful to you.

I am not a software developer. I spent a lot of time looking through the error logs and solving them but I couldn't. I don't like using Azuracast with Docker. I can say that the reason for this is not being able to configure the Firewall. That's why I want to use it with Ansible so much. I can customize as I wish. I am exposed to intense DDoS/Botnet attacks. I'll review the Docker installation again. I hope I can make it.

Endless thanks to you. You are amazing.
