### ISSUE TITLE
HTTP ERROR 500 

### ISSUE THREAD

**Issue by anmiefan** [AzuraCast/AzuraCast#5557]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

latest

### What happened?

no other error logs but this Can't connect to redis at redis://localhost:6379: Connection refused on  nginx logs  but the service redis is not starting auto and there is no other error logs to look and i cant start the redis it said service was not installed and also when i made the redis dir something took the redis dir out and i am rinning this on a rasberry pi board also something keeps removeing the /run/redis dir becasue it got removed again i started redis by hand i got this and it faild to start its not giving me any error logs i went in to htop it says running but when i started it says it failed something is broken here and there is no other error logs given about it and now i cant kill it its stuck running 

### Relevant log output

```shell
Can't connect to redis at redis://localhost:6379: Connection refused

after i started redis by hand this shows up on web site 

Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

```

**Comment by ItsMitchh** [comment]
As Silver has mentioned, it's down to you as the maintainer of the installation to debug this issue further, we won't be providing technical support for ansible services outside of very rare circumstances, please use docker for better support.

**Comment by anmiefan** [comment]
i already did not is showing up on the logs only to the ones that i have listed and docker run on the amonut of memory on the rasberry pi i already tried

**Comment by SlvrEagle23** [comment]
@anmiefan Try updating again, this should be fixed in the latest revision.

**Comment by fwn0** [comment]
Which build do you mean? I did try to update --full this now - HEAD is now at 5c062a086 Merge commit '964eb479c99c56c80fe533bf5ee3fda0b0018681' into stable - and still not successful. Same Redis, Influx and Mysql errors are noticed.

**Comment by SlvrEagle23** [comment]
@fwn0 Latest Rolling Release update. Not stable branch.

**Comment by Deiiji** [comment]
I have same error and redis server die then Ngix follow

**Comment by anmiefan** [comment]
i just did it happened again and i know what its doing i created the folder in /run/redis that was the error and then i update and it removed the /run/redis folder the thing is i don't know how to fix this this could hardwired in the AzuraCast code or in redis i think but not sure and i am not good at all at programming i know a little bit of linux and some  @SlvrEagle23

**Comment by SlvrEagle23** [comment]
@anmiefan Are you on the latest Rolling Release branch? I made updates to Ansible that should prevent it from even needing that `/run/redis` directory at all.

**Comment by anmiefan** [comment]
yep i am  and its still giveing me  the same error

**Comment by anmiefan** [comment]
any luck in fixing this i tried doing some changes on my end nothing works i even tried a new install

**Comment by anmiefan** [comment]
i got part of it working now its saying this what in the world is a Slim Application @SlvrEagle23 

Slim Application Error
A website error has occurred. Sorry for the temporary inconvenienc
