### ISSUE TITLE
Waiting...Timed out waiting for services to start.

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#5737]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

After upgrading to latest version, the upgrade process stalls on this step and the platform is down (all stations are offline and I even can't access to admin panel:

** Startup script complete.
** Running startup script '/etc/my_init.d/07_sftpgo_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/10_clear_temp.sh'...
** Startup script complete.
** Running Supervisord...
** Supervisord started.
** Running uptime_wait...
Starting up AzuraCast services...
🖥️🎶－🎵－📻 Waiting...Timed out waiting for services to start.
** Services up and ready!
This script must be run as the "azuracast" user. Rerunning...
AzuraCast Setup
(Environment: production)

AzuraCast Setup
===============

Welcome to AzuraCast. Please wait while some key dependencies of AzuraCast are set up...

Initialize AzuraCast
====================

Initializing essential settings...
 * Environment: Production
 * Installation Method: Docker

Running Database Migrations
---------------------------

[2022-09-16T07:32:56.407593+00:00] AzuraCast.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory (uncaught exception) at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 103 while running console command `azuracast:setup` {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 2002): An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:103)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /var/azuracast/www/vendor/doctrine/dbal/src/Driver/PDO/MySQL/Driver.php:28)"} []
[2022-09-16T07:32:56.417092+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 2002. [] []

In ExceptionConverter.php line 103:

  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory

In Exception.php line 28:

  SQLSTATE[HY000] [2002] No such file or directory

In Driver.php line 28:

  SQLSTATE[HY000] [2002] No such file or directory

azuracast:setup [--update] [--load-fixtures] [--release]

ERROR: 255
Creating azuracast ... done

**Comment by stardevelop** [comment]
azuracast | [2022-09-16T07:49:02.442238+00:00] AzuraCast.WARNING: Console command `azuracast:sync:run` exited with error code 2002. [] []
azuracast |
azuracast | In ExceptionConverter.php line 103:
azuracast |
azuracast |   An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or
azuracast |    directory
azuracast |
azuracast |
azuracast | In Exception.php line 28:
azuracast |
azuracast |   SQLSTATE[HY000] [2002] No such file or directory
azuracast |
azuracast |
azuracast | In Driver.php line 28:
azuracast |
azuracast |   SQLSTATE[HY000] [2002] No such file or directory
azuracast |
azuracast |
azuracast | azuracast:sync:run
azuracast |
🖥️🎵－🎶－📻 Waiting...station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body:
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] API nextsong - Response (502): <html>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] <body>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] <hr><center>nginx</center>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] </body>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3] </html>
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [lang:3]
azuracast | station_1_backend stdout | 2022/09/16 12:18:55 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_1_backend stdout |
azuracast | nginx stdout | 2022/09/16 07:48:55 [crit] 133#133: *690 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/3/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast | nginx stdout |
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/3/liquidsoap/nextsong' with body:
azuracast | station_3_backend stdout |
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] API nextsong - Response (502): <html>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] <body>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] <hr><center>nginx</center>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] </body>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3] </html>
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [lang:3]
azuracast | station_3_backend stdout | 2022/09/16 12:18:55 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_3_backend stdout |
azuracast | nginx stdout | 2022/09/16 07:49:05 [crit] 133#133: *692 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/2/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast | nginx stdout | 2022/09/16 07:49:05 [crit] 133#133: *693 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/1/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast | nginx stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body:
azuracast | station_1_backend stdout |
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/2/liquidsoap/nextsong' with body:
azuracast | station_2_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Response (502): <html>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] <body>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] <hr><center>nginx</center>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] </body>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3] </html>
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [lang:3]
azuracast | station_1_backend stdout | 2022/09/16 12:19:05 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_1_backend stdout |
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Response (502): <html>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] <body>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] <hr><center>nginx</center>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] </body>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3] </html>
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [lang:3]
azuracast | station_2_backend stdout |
azuracast | station_2_backend stdout | 2022/09/16 12:19:05 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_2_backend stdout |
azuracast | nginx stdout | 2022/09/16 07:49:05 [crit] 133#133: *696 connect() to unix:/var/run/php-fpm-internal.sock failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/internal/3/liquidsoap/nextsong HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-internal.sock:", host: "127.0.0.1:6010"
azuracast | nginx stdout |
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/3/liquidsoap/nextsong' with body:
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] API nextsong - Response (502): <html>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] <head><title>502 Bad Gateway</title></head>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] <body>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] <center><h1>502 Bad Gateway</h1></center>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] <hr><center>nginx</center>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] </body>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3] </html>
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [lang:3]
azuracast | station_3_backend stdout | 2022/09/16 12:19:05 [request:3] Nonexistent file or ill-formed URI "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r"!
azuracast | station_3_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:12 [decoder:2] Decoding "/var/azuracast/stations/music/media/NoVocal1/balearic_paradox.mp3" ended: Ffmpeg_decoder.End_of_file.
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | [mp3 @ 0x7f12c81e4f40]
azuracast | station_1_backend stdout | Estimating duration from bitrate, this may be inaccurate
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | [mp3 @ 0x7f12c81e4f40]
azuracast | station_1_backend stdout | Estimating duration from bitrate, this may be inaccurate
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:12 [playlist_default:3] Prepared "/var/azuracast/stations/music/media/NoVocal1/wind_down.mp3" (RID 108).
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:12 [cue_playlist_default:3] Cueing in...
azuracast | station_1_backend stdout |
azuracast | station_1_backend stdout | 2022/09/16 12:19:12 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
azuracast | station_1_backend stdout |

**Comment by BusterNeece** [comment]
@stardevelop Some reports we've received suggest that Docker may be out of date and that may be causing trouble for some installations. Try running:
```
./docker.sh install-docker
```

and then re-running the update and see if that helps.

**Comment by stardevelop** [comment]
While running the update, I see this:
Docker server (version 20.10.18) meets minimum version requirements.

**Comment by stardevelop** [comment]
> @stardevelop Some reports we've received suggest that Docker may be out of date and that may be causing trouble for some installations. Try running:
> 
> ```
> ./docker.sh install-docker
> ```
> 
> and then re-running the update and see if that helps.

I ran ./docker.sh install-docker and updated again but the issue persists.

**Comment by BusterNeece** [comment]
@stardevelop There may be something causing MariaDB to fail to boot in the latest version. The log entry we'd need is inside the Docker filesystem here:

```
/var/azuracast/www_tmp/service_mariadb.log
```

You could do `./docker.sh bash` to get into that filesystem, and then `tail -f` the file above, that might be helpful.

**Comment by BusterNeece** [comment]
@stardevelop Mind updating to the latest Rolling Release version? The possible cause of this has been identified and a fix has been pushed up a few minutes ago.

**Comment by stardevelop** [comment]
Thanks. The issue is fixed.

**Comment by aripisprecer** [comment]
I have the same issue with MariaDB:

- tried to upgrade to the latest rolling release -> doesn't fix this issue
- it seems that `LimitMEMLOCK=2M` in /etc/systemd/system/mariadb.service.d/limitcore.conf could be the problem

`2022-09-17 18:06:14 0 [Note] mysqld (server 10.9.2-MariaDB-1:10.9.2+maria~ubu2204) starting as process 93 ...
2022-09-17 18:06:14 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2022-09-17 18:06:14 0 [Note] InnoDB: Number of transaction pools: 1
2022-09-17 18:06:14 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-09-17 18:06:14 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
2022-09-17 18:06:14 0 [Warning] mysqld: io_uring_queue_init() failed with ENOMEM: try larger memory locked limit, ulimit -l, or https://mariadb.com/kb/en/systemd/#configuring-limitmemlock under systemd (262144 bytes required)
2022-09-17 18:06:14 0 [Warning] InnoDB: liburing disabled: falling back to innodb_use_native_aio=OFF
2022-09-17 18:06:14 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2022-09-17 18:06:14 0 [Note] InnoDB: Completed initialization of buffer pool
2022-09-17 18:06:14 0 [ERROR] InnoDB: File ./ib_logfile0 was not found
2022-09-17 18:06:14 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2022-09-17 18:06:14 0 [Note] InnoDB: Starting shutdown...
2022-09-17 18:06:14 0 [ERROR] Plugin 'InnoDB' init function returned error.
2022-09-17 18:06:14 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2022-09-17 18:06:14 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-09-17 18:06:14 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2022-09-17 18:06:14 0 [ERROR] Aborting`
