### ISSUE TITLE
Nowplaying live not working

### ISSUE THREAD

**Issue by asa767** [AzuraCast/AzuraCast#5807]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.4

### What happened?

After updating from 0.17.3 to 0.17.4 It's not possible to connect https://admin.medreseradyo.com/api/live/nowplaying/medrese_radyo for nowplaying info.

mp3 stream and https://admin.medreseradyo.com/api/nowplaying/medrese_radyo is working

**Comment by asa767** [comment]
Changed to the rolling channel and updated but still not working.

**Comment by wavespeed** [comment]
The same is happening here.

**Comment by t0g3pii** [comment]
Rolling Release #[468c4fe](https://github.com/AzuraCast/AzuraCast/commit/468c4fe940d6f94c5f6725b8f77fce10e11ae1ce)
Same on this Version

**Comment by asa767** [comment]
> Rolling Release #[468c4fe](https://github.com/AzuraCast/AzuraCast/commit/468c4fe940d6f94c5f6725b8f77fce10e11ae1ce) Same on this Version

It fixed mine.

**Comment by asa767** [comment]
> 

Broken again!

After Rebooting the whole server it worked for a short time and then started to return "Message ID invalid".  Soon after it returns nothing.

**Comment by asa767** [comment]
Breaking News!
1-Updated to Rolling Release #[468c4fe](https://github.com/AzuraCast/AzuraCast/commit/468c4fe940d6f94c5f6725b8f77fce10e11ae1ce)
2-Got a full backup
3-Uninstalled Azuracast
4-Installed Azuracast
5-Restored Backup
Now it works! For now.

**Comment by asa767** [comment]
It's broken again. Where can I find the logs of websocket service.

**Comment by BusterNeece** [comment]
Looking into this issue...not sure that the little snippet of nginx logs there is enough information for us to actually figure out what's going on. Would it be possible for anyone experiencing this to post a longer version of their nginx logs? You can view those logs from the Log Viewer page.

**Comment by asa767** [comment]
> Looking into this issue...not sure that the little snippet of nginx logs there is enough information for us to actually figure out what's going on. Would it be possible for anyone experiencing this to post a longer version of their nginx logs? You can view those logs from the Log Viewer page.

Sure;
nginx: worker process: ./debian/modules/nchan/src/store/spool.c:479: spool_fetch_msg: Assertion `spool->msg_status == MSG_INVALID' failed.
nginx: worker process: ./debian/modules/nchan/src/store/spool.c:479: spool_fetch_msg: Assertion `spool->msg_status == MSG_INVALID' failed.
2022/10/30 06:33:00 [alert] 97#97: worker process 156 exited on signal 6 (core dumped)
2022/10/30 06:33:00 [alert] 97#97: worker process 151 exited on signal 6 (core dumped)
nginx: worker process: ./debian/modules/nchan/src/store/spool.c:479: spool_fetch_msg: Assertion `spool->msg_status == MSG_INVALID' failed.
2022/10/30 06:33:02 [alert] 97#97: worker process 152 exited on signal 6 (core dumped)
2022/10/30 06:36:38 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:38:20 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:40:03 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:41:45 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:43:27 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:43:27 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:46:51 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:48:33 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:51:50 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:55:22 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 06:58:47 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:00:29 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:02:43 [error] 154#154: MEMSTORE:03: tried adding WAITING chanhead 000055D6AC5EB2A0 azuracast_nowplaying/radyo_english to chanhead_gc. why?
2022/10/30 07:10:43 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:10:43 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:14:06 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:15:49 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:19:14 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:32:51 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:34:34 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:36:17 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:37:50 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:41:23 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:48:11 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 07:53:35 [error] 154#154: MEMSTORE:03: tried adding WAITING chanhead 000055D6AC5EB2A0 azuracast_nowplaying/radyo_english to chanhead_gc. why?
2022/10/30 07:53:59 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:00:08 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:01:50 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:08:39 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:13:32 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:15:28 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:15:28 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:17:10 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:20:35 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:24:41 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:27:23 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:29:06 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:29:06 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:30:48 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:34:12 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:35:55 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:35:55 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:35:55 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:41:01 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:42:43 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:42:44 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:44:25 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABB61E60 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:47:51 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
nginx: worker process: ./debian/modules/nchan/src/store/spool.c:479: spool_fetch_msg: Assertion `spool->msg_status == MSG_INVALID' failed.
2022/10/30 08:51:46 [alert] 97#97: worker process 154 exited on signal 6 (core dumped)
2022/10/30 08:53:27 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:53:27 [error] 22039#22039: MEMSTORE:03: tried adding WAITING chanhead 000055D6ABB45F40 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:55:10 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:56:52 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:58:34 [error] 22039#22039: MEMSTORE:03: tried adding WAITING chanhead 000055D6ABB45F40 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:58:34 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 08:58:34 [error] 578#578: MEMSTORE:00: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:00:16 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:01:58 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:01:59 [error] 578#578: MEMSTORE:00: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:03:41 [error] 22039#22039: MEMSTORE:03: tried adding WAITING chanhead 000055D6ABB45F40 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:03:41 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:05:23 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:05:23 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:07:05 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:07:05 [error] 578#578: MEMSTORE:00: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:08:47 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:08:48 [error] 578#578: MEMSTORE:00: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:12:12 [error] 578#578: MEMSTORE:00: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:12:12 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:15:37 [error] 153#153: MEMSTORE:02: tried adding WAITING chanhead 000055D6ABA808D0 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:15:38 [error] 157#157: MEMSTORE:05: tried adding WAITING chanhead 000055D6ABBA1B50 azuracast_nowplaying/persian to chanhead_gc. why?
2022/10/30 09:17:19 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:19:01 [error] 578#578: MEMSTORE:00: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?
2022/10/30 09:19:01 [error] 575#575: MEMSTORE:04: tried adding WAITING chanhead 000055D6ABAFE250 azuracast_nowplaying/medrese_radyo to chanhead_gc. why?

**Comment by BusterNeece** [comment]
@asa767 Oh, so it's pretty much just that error over and over.

I'm not sure what's causing that. I looked through nchan's reported issues and only found some from 2018 referencing this, and both were closed without resolution.

I think nchan is right now, by default, requesting 128MB of RAM to handle its internal notifications. That's quite a lot, especially for these purposes, and it seems like if it uses Redis, it doesn't use this same RAM. That may be part of what's causing the problem. I'll look into it some more.

**Comment by asa767** [comment]
> @asa767 Oh, so it's pretty much just that error over and over.
> 
> I'm not sure what's causing that. I looked through nchan's reported issues and only found some from 2018 referencing this, and both were closed without resolution.
> 
> I think nchan is right now, by default, requesting 128MB of RAM to handle its internal notifications. That's quite a lot, especially for these purposes, and it seems like if it uses Redis, it doesn't use this same RAM. That may be part of what's causing the problem. I'll look into it some more.

Does this help?

Redis Service Log

98:C 30 Oct 2022 06:31:45.343 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
98:C 30 Oct 2022 06:31:45.343 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=98, just started
98:C 30 Oct 2022 06:31:45.343 # Configuration loaded
98:M 30 Oct 2022 06:31:45.346 * Running mode=standalone, port=6379.
98:M 30 Oct 2022 06:31:45.346 # Server initialized
98:M 30 Oct 2022 06:31:45.346 # **_**_**WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.**_**_**
98:M 30 Oct 2022 06:31:45.346 * Ready to accept connections
98:M 30 Oct 2022 06:31:45.346 * The server is now ready to accept connections at /run/redis/redis.sock

**Comment by BusterNeece** [comment]
@asa767 I've updated nchan to use Redis again as its backend; let me know if that helps.

**Comment by asa767** [comment]
Changed nothing but Nginx Service Logs:

2022/10/30 12:18:14 [error] 147#147: nchan: Redis node localhost:6379 connection failed: connection timed out
2022/10/30 12:18:14 [error] 143#143: nchan: Redis node localhost:6379 connection failed: connection timed out
2022/10/30 12:18:14 [crit] 147#147: *2 connect() to unix:/var/run/php-fpm-www.sock failed (2: No such file or directory) while connecting to upstream, client: 172.69.199.155, server: localhost, request: "GET /api/frontend/dashboard/stations HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm-www.sock:", host: "admin.medreseradyo.com", referrer: "https://admin.medreseradyo.com/dashboard"
2022/10/30 12:18:15 [error] 146#146: nchan: Redis node localhost:6379 connection failed: connection timed out
2022/10/30 12:18:15 [error] 148#148: nchan: Redis node localhost:6379 connection failed: connection timed out
2022/10/30 12:18:15 [error] 144#144: nchan: Redis node localhost:6379 connection failed: connection timed out
2022/10/30 12:18:16 [error] 145#145: nchan: Redis node localhost:6379 connection failed: connection timed out
2022/10/30 12:18:27 [crit] 147#147: *2 connect() to unix:/var/run/php-fpm-www.sock failed (2: No such file or directory) while connecting to upstream, client: 172.69.199.155, server: localhost, request: "GET /dashboard HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm-www.sock:", host: "admin.medreseradyo.com", referrer: "https://admin.medreseradyo.com/login"
2022/10/30 12:18:28 [crit] 147#147: *2 connect() to unix:/var/run/php-fpm-www.sock failed (2: No such file or directory) while connecting to upstream, client: 172.69.199.155, server: localhost, request: "GET /dashboard HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm-www.sock:", host: "admin.medreseradyo.com", referrer: "https://admin.medreseradyo.com/login"
2022/10/30 12:18:29 [crit] 147#147: *2 connect() to unix:/var/run/php-fpm-www.sock failed (2: No such file or directory) while connecting to upstream, client: 172.69.199.155, server: localhost, request: "GET /dashboard HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm-www.sock:", host: "admin.medreseradyo.com", referrer: "https://admin.medreseradyo.com/login"
2022/10/30 12:18:30 [crit] 147#147: *2 connect() to unix:/var/run/php-fpm-www.sock failed (2: No such file or directory) while connecting to upstream, client: 172.69.199.155, server: localhost, request: "GET /dashboard HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm-www.sock:", host: "admin.medreseradyo.com", referrer: "https://admin.medreseradyo.com/login"
2022/10/30 12:18:31 [crit] 147#147: *2 connect() to unix:/var/run/php-fpm-www.sock failed (2: No such file or directory) while connecting to upstream, client: 172.69.199.155, server: localhost, request: "GET /dashboard HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm-www.sock:", host: "admin.medreseradyo.com", referrer: "https://admin.medreseradyo.com/login"

Azuracast Logs:
[2022-10-30T12:20:23.814580+00:00] AzuraCast.NOTICE: Failed to define an expiration for the "{resource}" lock, someone else acquired the lock. {"resource":{"Symfony\\Component\\Lock\\Key":"lock_nowplaying_medrese_radyo"}} []
[2022-10-30T12:20:23.872161+00:00] AzuraCast.ERROR: Symfony\Component\Lock\Exception\LockConflictedException:  (uncaught exception) at /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php line 179 while running console command `azuracast:sync:nowplaying` {"exception":"[object] (Symfony\\Component\\Lock\\Exception\\LockConflictedException(code: 0):  at /var/azuracast/www/vendor/symfony/lock/Store/RedisStore.php:179)"} []
[2022-10-30T12:20:23.873386+00:00] AzuraCast.WARNING: Console command `azuracast:sync:nowplaying` exited with error code 1. [] []
[2022-10-30T12:23:18.326114+00:00] AzuraCast.NOTICE: Starting new Message Queue worker process. {"runtime":0,"workerName":"app_worker_0"} []

**Comment by asa767** [comment]
Why it's working on azuracast demo (https://demo.azuracast.com/api/live/nowplaying/azuratest_radio) but not on mine. Yesterday I uninstalled and created a new setup of azuracast from zero on the same server, it did not worked either.
Am I forget to update something? Server is Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-62-generic x86_64) on Contabo.

**Comment by BusterNeece** [comment]
@asa767 Oh, you're on the stable channel? Are you updating to the Rolling Release channel? That's where I'm fixing this particular issue.

**Comment by asa767** [comment]
> @asa767 Oh, you're on the stable channel? Are you updating to the Rolling Release channel? That's where I'm fixing this particular issue.

I am on Rolling Release channel and the current version is Rolling Release #a849187 (2022-10-30 11:26).

**Comment by BusterNeece** [comment]
@asa767 I just pushed another update out a few minutes ago, can you let me know if it helps?

**Comment by asa767** [comment]
> @asa767 I just pushed another update out a few minutes ago, can you let me know if it helps?

Updated. It worked a couple of time then stopped. But I found something interesting.
If I test websocked from here: https://www.piesocket.com/websocket-tester?url=wss://admin.medreseradyo.com/api/live/nowplaying/medrese_radyo, it does not stop working. But if I write the link:https://admin.medreseradyo.com/api/live/nowplaying/medrese_radyo at the web browsers address bar and hit enter it works for only a couple of refreshes (I click the refresh button of Chrome) then stop working till restart the docker of azuracast. Some of these refresh hits it returns Message ID invalid.

**Comment by BusterNeece** [comment]
@asa767 What do the logs say now for nginx?

**Comment by asa767** [comment]
> @asa767 What do the logs say now for nginx?

nginx: worker process: ./debian/modules/nchan/src/store/spool.c:479: spool_fetch_msg: Assertion `spool->msg_status == MSG_INVALID' failed.
2022/10/30 16:01:21 [alert] 101#101: worker process 147 exited on signal 6 (core dumped)

**Comment by BusterNeece** [comment]
@asa767 It appears one or more of your listeners may be connecting to the live nowplaying service via EventSource. There's a known issue (slact/nchan#534) over there that has been pending for quite a while that matches the error you reported exactly, and they have a stated workaround that may help with it. I've applied it in the latest Rolling Release version; try updating and see if that helps!

**Comment by asa767** [comment]
There are mobile apps and web sites of mine using connecting to this service via EventSource. 
Also Rolling Release #[72df7d7](https://github.com/AzuraCast/AzuraCast/commit/72df7d77d965a8cbc04a0c8d872bb7e87ee72440) (2022-10-30 17:09) not solved the issue.
nginx: worker process: ./debian/modules/nchan/src/store/spool.c:479: spool_fetch_msg: Assertion `spool->msg_status == MSG_INVALID' failed.
2022/10/30 18:01:35 [alert] 100#100: worker process 150 exited on signal 6 (core dumped)

**Comment by BusterNeece** [comment]
@asa767 Is it possible for you to switch those to either websockets or long polling? It appears EventSource being broken is a known issue, and our only current mitigation is to disable EventSource as one of the subscriber types.

**Comment by asa767** [comment]
> @asa767 Is it possible for you to switch those to either websockets or long polling? It appears EventSource being broken is a known issue, and our only current mitigation is to disable EventSource as one of the subscriber types.

I can publish a new update to the app markets but there still will be some older apps for a while and they are going to brake the service.  Is there any solution to block these EventSource requests at Azuracast server side.

Also these EventSource requests were working on ver0.17.3. They stop working after updating to 0.17.4.

**Comment by BusterNeece** [comment]
@asa767 Yes, we can disable EventSource requests on our end so they shouldn't cause this issue. The latest rolling commit that's deploying should fix this (see above).

The reason we're seeing this error in 0.17.4 and not 0.17.3 is because we updated our Docker image to use Ubuntu 22.04 instead of 20.04, which upgraded the version of nchan used to a newer version, which unfortunately had the side effect of introducing this particular regression.

**Comment by BusterNeece** [comment]
@asa767 You can update now to the latest Rolling and it should disable EventSource both on the server side and in our own client implementation. Sorry for the inconvenience caused to your library; I'll look to see if it's possible for us to use an older version of the library without sacrificing nginx security patches.

**Comment by asa767** [comment]
Updated to latest Rolling Release #[33f7443](https://github.com/AzuraCast/AzuraCast/commit/33f74430a08e68a9e3474b8da69a5c11174bfe17) (2022-10-30 18:20) but still not working.

2022/10/30 19:36:36 [error] 172#172: nchan: Redis node localhost:6379 missing reply after loading Redis Lua script channel_keepalive
2022/10/30 19:36:36 [error] 172#172: nchan: Redis node localhost:6379 connection failed: SCRIPT LOAD failed,
2022/10/30 19:36:36 [error] 171#171: nchan: Redis node localhost:6379 connection failed: connection timed out
2022/10/30 19:36:36 [error] 169#169: nchan: Redis node localhost:6379 connection failed: connection timed out
2022/10/30 19:36:36 [error] 170#170: nchan: Redis node localhost:6379 connection failed: connection timed out
2022/10/30 19:36:36 [error] 172#172: nchan: Redis server redis_server: no reachable masters
2022/10/30 19:36:36 [error] 169#169: nchan: Redis server redis_server: no reachable masters
2022/10/30 19:36:36 [error] 171#171: nchan: Redis server redis_server: no reachable masters
2022/10/30 19:36:36 [error] 170#170: nchan: Redis server redis_server: no reachable masters
nginx: worker process: ./debian/modules/nchan/src/store/spool.c:479: spool_fetch_msg: Assertion `spool->msg_status == MSG_INVALID' failed.
2022/10/30 19:37:31 [alert] 99#99: worker process 164 exited on signal 6 (core dumped)
nginx: worker process: ./debian/modules/nchan/src/store/spool.c:479: spool_fetch_msg: Assertion `spool->msg_status == MSG_INVALID' failed.
2022/10/30 19:37:50 [alert] 99#99: worker process 165 exited on signal 6 (core dumped)

**Comment by BusterNeece** [comment]
@asa767 I'm really at a loss for how to deal with this then. I'm going to have to look into using an older nchan version, or a different library entirely for "push" API updates.

**Comment by asa767** [comment]
> @asa767 I'm really at a loss for how to deal with this then. I'm going to have to look into using an older nchan version, or a different library entirely for "push" API updates.

Thanks a lot for your efforts for this issue and for entire AzuraCast project. Wish I could contribute but I am not good at PHP or any backend code at all.

I am looking forward to see upcoming updates for this Issue Ticket.

**Comment by PeWe79** [comment]
Same here with Docker installation.
My case Call API from wss:// not https://

**Comment by BusterNeece** [comment]
We have updated our live NowPlaying update system to use a new library (Centrifugo), which is more well-supported and reliable and will serve us well moving into the future. See our documentation here for how to update your API calls to use the new service: https://docs.azuracast.com/en/developers/apis/now-playing-data#high-performance-updates
