### ISSUE TITLE
Relay Stream URL not working at all

### ISSUE THREAD

**Issue by matthewunmuted** [AzuraCast/AzuraCast#5934]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f8fd85d 

### What happened?

We have a client who has a main station on another of our AzuraCast servers, and is attempting to relay it to their new station on a different server.

As far as we understand, this is as simple as adding the stream URL into the 'Relay Stream URL' of the mount point edit menu, however all that does is play static through the station.

AutoDJ is enabled, there is no media uploaded, there is only one mount point (default) and the configuration exactly matches the main station - yet, it will not relay the stream. 

We have tried HTTP and HTTPS URL.

**Comment by BusterNeece** [comment]
Should be fixed in latest Rolling that's currently deploying; Icecast requires the port be explicitly specified for a relay, even if it's the default port for http/https (which we normally would filter out, but have to add back in for this scenario).

**Comment by BusterNeece** [comment]
@matthewunmuted You're thinking of the port it's supposed to be proxying (i.e. `/radio/8170`), but I'm talking about the port in the actual URL scheme, i.e. this URL would be `https://halo.streamerr.co:443/...`. Normally this would never be necessary for default ports, and we don't want you to have to enter it like that, so in the latest Rolling we just automatically figure that out.

**Comment by matthewunmuted** [comment]
Hi Buster,

We updated the server to Rolling Release #[1615948], however we are still having issues getting the station to relay this stream:

http://halo.streamerr.co:8170/stream

We have the AutoDJ disabled on the only mount point present on the service, which has that URL entered in the 'Relay Stream URL' field, yet nothing is playing. 

Are we using the correct relay URL? Does the AutoDJ need to be enabled? When it is enabled, the station's uploaded media plays instead of the relayed stream. Any clarification would be very welcome.

**Comment by matthewunmuted** [comment]
The relay stream URL being used is: https://halo.streamerr.co:443/listen/radio/stream

**Comment by BusterNeece** [comment]
@matthewunmuted I looked into this and tested it more locally, and unfortunately it appears I misunderstood the relay feature's limitations...it can only relay a stream if the Icecast/Shoutcast server is at the root of the port, as it would normally be if you directly linked the port number, i.e. `https://your-stream:8080/stream.mp3`. Our nginx port 80/443 proxies don't work with it at all in my tests. Sorry for the confusion there.

**Comment by matthewunmuted** [comment]
Hi Buster,

Many thanks for the information and clarification. All the best.
