### ISSUE TITLE
offline streaming but audio is running

### ISSUE THREAD

**Issue by istahilagi** [AzuraCast/AzuraCast#6005]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.17.3

### What happened?

on the public page it says offline streaming, but the auto dj runs and the song is still heard... and this only applies to one song, after one song finishes playing the radio will stop and have to be reloaded again

### Relevant log output

```shell
[mp3 @ 0x7f2f280312c0] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f2f280312c0] Estimating duration from bitrate, this may be inaccurate
2023/01/09 13:17:46 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/3/liquidsoap/feedback' with body: {
2023/01/09 13:17:46 [lang:3]   "song_id": "b5e26aa3ae7007d041dcff3df0d12009",
2023/01/09 13:17:46 [lang:3]   "playlist_id": "3",
2023/01/09 13:17:46 [lang:3]   "media_id": "68"
2023/01/09 13:17:46 [lang:3] }
2023/01/09 13:17:46 [clock.main:2] We must catchup 7.67 seconds!
2023/01/09 13:17:46 [lang:3] API feedback - Response (200): true
2023/01/09 13:17:47 [clock.main:2] We must catchup 3.32 seconds (we've been late for 100 rounds)!
2023/01/09 13:22:24 [decoder:2] Decoding "/var/azuracast/stations/3/media/DANGDUT ASIK/denny_caknan_-_kartonyono_medot_janji_(official_music_video).mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f2f2413d640] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f2f2413d640] Estimating duration from bitrate, this may be inaccurate
2023/01/09 13:22:25 [next_song:3] Prepared "/var/azuracast/stations/3/media/DANGDUT ASIK/devay_-_hati_siapa_tak_luka.mp3" (RID 59390).
2023/01/09 13:22:25 [cue_next_song:3] Cueing in...
2023/01/09 13:22:25 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/3/liquidsoap/nextsong' with body: 
2023/01/09 13:22:26 [cross_0:3] Analysis: -18.299256dB / -21.074804dB (2.96s / 2.96s)
2023/01/09 13:22:26 [lang:3] API nextsong - Response (200): annotate:title="main mata[1]",artist="baby shima",duration="272.00",song_id="200d62964f68e79ed01ecd32ee9e092d",media_id="76",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="3":media:DANGDUT ASIK/baby_shima_-_main_mata[1].mp3
[mp3 @ 0x7f2f2c0c9500] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f2f2c0227c0] Estimating duration from bitrate, this may be inaccurate
2023/01/09 13:22:33 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/3/liquidsoap/feedback' with body: {
2023/01/09 13:22:33 [lang:3]   "song_id": "6d4cdeb490f35dd7890882695a411e81",
2023/01/09 13:22:33 [lang:3]   "playlist_id": "3",
2023/01/09 13:22:33 [lang:3]   "media_id": "79"
2023/01/09 13:22:33 [lang:3] }
2023/01/09 13:22:33 [clock.main:2] We must catchup 8.29 seconds!
2023/01/09 13:22:34 [lang:3] API feedback - Response (200): true
2023/01/09 13:26:48 [decoder:2] Decoding "/var/azuracast/stations/3/media/DANGDUT ASIK/devay_-_hati_siapa_tak_luka.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f2f242c3040] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f2f242c3040] Estimating duration from bitrate, this may be inaccurate
2023/01/09 13:26:48 [next_song:3] Prepared "/var/azuracast/stations/3/media/DANGDUT ASIK/baby_shima_-_main_mata[1].mp3" (RID 59391).
2023/01/09 13:26:48 [cue_next_song:3] Cueing in...
2023/01/09 13:26:49 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/3/liquidsoap/nextsong' with body: 
2023/01/09 13:26:49 [cross_0:3] Analysis: -25.083485dB / -14.568408dB (2.96s / 2.96s)
2023/01/09 13:26:49 [lang:3] API nextsong - Response (200): annotate:title="ojo mudik",artist="didi kempot",duration="264.00",song_id="233919de38c63a119750086dbffad64d",media_id="80",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",playlist_id="3":media:DANGDUT ASIK/didi_kempot_-_ojo_mudik.mp3
[mp3 @ 0x7f2f2c0c9500] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f2f2c0c9500] Estimating duration from bitrate, this may be inaccurate
2023/01/09 13:26:55 [clock.main:2] We must catchup 6.99 seconds!
2023/01/09 13:26:55 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/3/liquidsoap/feedback' with body: {
2023/01/09 13:26:55 [lang:3]   "song_id": "200d62964f68e79ed01ecd32ee9e092d",
2023/01/09 13:26:55 [lang:3]   "playlist_id": "3",
2023/01/09 13:26:55 [lang:3]   "media_id": "76"
2023/01/09 13:26:55 [lang:3] }
2023/01/09 13:26:56 [lang:3] API feedback - Response (200): true
2023/01/09 13:29:57 [main:3] Shutdown started!
2023/01/09 13:29:57 [main:3] Waiting for main threads to terminate...
2023/01/09 13:29:57 [local_1:3] Closing connection...
2023/01/09 13:29:57 [threads:2] Queue generic queue #1 crashed with exception Sys_error("Condition.wait: Operation not permitted")
2023/01/09 13:29:57 [threads:2] Raised by primitive operation at Duppy.queue.run in file "src/duppy.ml", line 341, characters 6-32
2023/01/09 13:29:57 [threads:2] Called from Duppy.queue in file "src/duppy.ml", line 357, characters 8-12
2023/01/09 13:29:57 [threads:2] Re-raised at Duppy.queue in file "src/duppy.ml", line 361, characters 8-17
2023/01/09 13:29:57 [threads:2] Called from Tutils.create.(fun).process in file "tools/tutils.ml", line 164, characters 12-15
```

**Comment by Chrisx84** [comment]
this is happening to me with the latest rolling release but with all songs and both stations.
Rolling Release #[03f1f58](https://github.com/AzuraCast/AzuraCast/commit/03f1f5840adddf31343154b48f9f999602657bde)

**Comment by sunstep** [comment]
Same here, the station is offline but audio plays when I click the play button.

I am currently on rolling release #6ef72c6

**Comment by BusterNeece** [comment]
@sunstep We discovered one potential cause of this; you can try restarting broadcasting on the affected stations from the "Broadcasting" menu on the left sidebar and that should help.

**Comment by inetactief** [comment]
I have the same problems for stations offline yesterday afther the update.
Today a new update now i have 
#[4c59ad5](https://github.com/AzuraCast/AzuraCast/commit/4c59ad57ecaaf68c465de1d690a0c405a9b1a2e4) (2023-01-18 5:53) 
And it works

Only one station was offline. So i restart his autodj en server and it works again!

**Comment by sunstep** [comment]
Can also confirm that the issue is fixed now, Azuracast automatically updated itself and now the stations work fine. 

Currently, I am on rolling release #2c0456a

**Comment by isAAAc** [comment]
i still have the issue as explained in https://github.com/AzuraCast/AzuraCast/issues/6019
install: docker rolling-release, up to date

**Comment by isAAAc** [comment]
fixed on my side disabling autodj on the station :white_check_mark:

**Comment by BusterNeece** [comment]
We found and have fixed an issue where a station would initially show as Offline after a restart (or initial start), possibly causing confusion, and this is fixed in the latest Rolling Release.
