### ISSUE TITLE
Homepage Redirect URL Errror

### ISSUE THREAD

**Issue by Maxheino** [AzuraCast/AzuraCast#6020]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.6

### What happened?

Hi,

after Update from Version 0.17.3 to 0.17.6 the Homepage Redirect URL ist not working.
Before Update it working fine.  mydomain.de -> mydomain.de/public/mystreamname
After Updating the Browser returns an Error because the Redirect URL is https://**localhost**/public/mystreamname.
If delete the "Homepage Redirect URL", i got the normal Login-Page.

**Comment by BusterNeece** [comment]
This is a known issue that shouldn't affect your streams in any meaningful way and has already been fixed in Rolling Release versions.

**Comment by Maxheino** [comment]
Thank you for your feedback!

However, I have now updated to the latest Rolling Release version, and the error still prevails.
Is there anything else that needs to be done manually to fix the error after the update?

**Comment by BusterNeece** [comment]
@Maxheino Sorry, for some reason my e-mail only reflected the second error you had posted, not the first.

If you manually set the redirect URL back to the proper URL, does it work as intended?

**Comment by BusterNeece** [comment]
@Maxheino No, I mean, if you just correct the redirect URL to just the relative path (i.e. the `/public/xxx`) link, does that work?

**Comment by Maxheino** [comment]
No. then the address appears: https://localhost.de/public/xxxx

**Comment by Maxheino** [comment]
Hello,
 
Can I provide any more information for error analysis?
 

 

Von: Buster Neece ***@***.*** 
Gesendet: Freitag, 13. Januar 2023 22:04
An: AzuraCast/AzuraCast ***@***.***>
Cc: Maxheino ***@***.***>; Author ***@***.***>
Betreff: Re: [AzuraCast/AzuraCast] Homepage Redirect URL Errror (Issue #6020)

 

This is a known issue that shouldn't affect your streams in any meaningful way and has already been fixed in Rolling Release versions.

**Comment by BusterNeece** [comment]
@Maxheino This was fixed in the latest Rolling Release version.
