### ISSUE TITLE
User acess

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#617]
- **Installation Method: Traditional
- **Host OS : Ubuntu 16.04

Hello,

When I set a user to access only one radio station and give him access to some parts of the panel, he still has no access to anything, he only has access when I put all the permissions.

I've already put this in place and it worked.

Thank you

![azuracast_user_login_station](https://user-images.githubusercontent.com/7109309/41346842-c4622b64-6eff-11e8-8345-a5196d7df4c7.jpg)

**Comment by jonikane** [comment]
But in the permissions of the station I do not find: "view station administration", I just see there the option "view station page"

**Comment by SlvrEagle23** [comment]
@jonikane It turns out this was indeed a problem within the code; the incorrect permission was being checked for at the global station administration level. The latest update should fix this.

**Comment by jonikane** [comment]
I still do not see that option there.
Do I need to restart the server?

**Comment by jonikane** [comment]
it's OK now
Thank you
