### ISSUE TITLE
Latest release still serving self-signed SSL certificate. 

### ISSUE THREAD

**Issue by bboyles303** [AzuraCast/AzuraCast#6741]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #57dd7e5 (2023-11-17 22:06)

### What happened?

After updating, a self-signed certificate is being served as opposed to one from LetsEncrypt. This is similar to https://github.com/AzuraCast/AzuraCast/issues/6721 except when attempting to get a new cert via Administration -> System Settings -> Security -> Generate/Renew Certificate I get the following: 
[2023-11-18T01:06:04.439630+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2023-11-18T01:06:04.455457+00:00] AzuraCast.ERROR: ACME Error: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/src/Service/Acme.php:134)"} []

### Relevant log output

```shell
[2023-11-18T01:06:04.439630+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2023-11-18T01:06:04.455457+00:00] AzuraCast.ERROR: ACME Error: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/src/Service/Acme.php:134)"} []
```

**Comment by bboyles303** [comment]
Just an update, still broken/same result in Rolling Release #[771108a] (2023-11-18 0:48)

**Comment by burjuyz** [comment]
`[2023-12-17T08:15:15.069219+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2023-12-17T08:15:15.073993+00:00] AzuraCast.ERROR: ACME Error: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/src/Service/Acme.php:136)"} []
`
I have the same issue and can't update new certificate.
v0.19.3 Stable
How to fix it?

**Comment by BusterNeece** [comment]
@burjuyz This should be fixed in the latest Rolling Release. If you can, can you test to see that it's fixed there, so we can include it in the next stable version?

**Comment by burjuyz** [comment]
I tnink it will work, I did the next steps on last stable:
1 Updated via standart docker mode.
2 manually updated the certificate...

**Comment by fsan2val** [comment]
Hello everyone, happy new year. I have the latest stable version, my certificate already expired on January 1, 2024, I executed the renewal through the azuracast interface but I have this data. I still don't have SSL. How to update in ssl Thank you

**Comment by burjuyz** [comment]
This bug steel persists, there are no automatic updates and mannualy it also revokes.
v0.19.5 Stable 
log is 
[2024-04-18T16:19:08.831894+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2024-04-18T16:19:08.839100+00:00] AzuraCast.ERROR: ACME Error: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/src/Service/Acme.php:136)"} []

**Comment by BusterNeece** [comment]
@burjuyz This was fixed in the latest Rolling Release, but we haven't migrated that into a new stable release yet. For now, if you experience this issue I'd recommend updating to the Rolling Release. We expect to tag a new Stable version soon, but we don't currently have a timeline for it.

**Comment by burjuyz** [comment]
Well noted, thanks for the swift reply

**Comment by CristianEsis** [comment]
Here rolling release still not work:

i did also 
```
./docker.sh update-self
./docker.sh setup-release
```

I choose rolling release

`./docker.sh update then.`


Error:
```

[2024-04-24T09:43:01.252351+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2024-04-24T09:43:01.258182+00:00] AzuraCast.ERROR: ACME Error: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/src/Service/Acme.php:138)"} []

```

**Comment by kikou2022** [comment]
Hello ! Always the same issue for me today after the latest version vith Docker : 
Rolling Release #[b54331e](https://github.com/AzuraCast/AzuraCast/commit/b54331e145e915717db24235da6a7993dd991ec6) (2025-02-07 0:42) • Docker • PHP 8.4



`[2025-02-07T17:03:11.344897+00:00] AzuraCast.DEBUG: ACME: Using directory URL: https://acme-v02.api.letsencrypt.org/directory [] []
[2025-02-07T17:03:14.895562+00:00] AzuraCast.ERROR: ACME Error: Challenge validation failed: 51.254.126.25: Invalid response from https://icecast-vps-ovh2.airvs.site/.well-known/acme-challenge/T-l7VRgpOgP4KEV6FTY-5MXpDYxey-J-W6B1hJQ5kjQ: 404 (urn:ietf:params:acme:error:unauthorized) {"exception":"[object] (skoerfgen\\ACMECert\\ACME_Exception(code: 0): Challenge validation failed: 51.254.126.25: Invalid response from https://icecast-vps-ovh2.airvs.site/.well-known/acme-challenge/T-l7VRgpOgP4KEV6FTY-5MXpDYxey-J-W6B1hJQ5kjQ: 404 (urn:ietf:params:acme:error:unauthorized) at /var/azuracast/www/vendor/skoerfgen/acmecert/src/ACMEv2.php:145)"} []

Thanks for your help @BusterNeece maybe ;-)
`
