### ISSUE TITLE
Title information missing after short tracks

### ISSUE THREAD

**Issue by RM-FM** [AzuraCast/AzuraCast#6778]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.3

### What happened?

Everytime (really each time) when we are playing a jingle, the next song basically is ignored entirely by Azuracast. Next song is playing perfectly fine, but neigher meta data nor Azuracast internal Song History is being updated with that song. From a logging / playlist / API point of view it looks like the song was never played. Our jingles are between 4 and 7 seconds.

I can reproduced it each time no matter whether the Jingle Playlist is set to Jingle Mode or not. Jingle meta data is showing up correctly in non-jingle mode, but still the next track is entitely invisible.

Crossfade duration has no impact on this behaviour. Even if the song before the jingle was faded-out but not actually mixed, the issue persists. As there is a bug related to cue/fade points of value "0" in 0.19.3, we have our custom crossfade function in place setting default values to "0". Please take note that the issue stays the same with the Azuracast native crossfade function in the latest Rolling Release where the cue/fade issue is (partially) fixed.

```
def rm_crossfade(old, new) =
  if new.metadata["jingle_mode"] == "true" then
    let fade.out = fun (s) -> fade.out(type="log", duration=3., s)
    let fade.in = fun (s) -> fade.in(type="log", duration=.0, s)
    sequence([fade.out(old.source),fade.in(new.source)])
  else
    cross.simple(old.source, new.source, fade_in=0., fade_out=0.)
  end
end
radio = cross(minimum=0., duration=0., rm_crossfade, radio)
```

![image](https://github.com/AzuraCast/AzuraCast/assets/40538914/e6eae40f-8f30-408d-bc61-8fb25bd93c3a)

### Relevant log output

```shell
2023/12/05 12:47:27 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/nextsong' with body: 
2023/12/05 12:47:27 [cross:3] Analysis: -15.302096dB / -18.290023dB (0.44s / 0.44s)
2023/12/05 12:47:27 [source.43:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [audio.add.12:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [fade_in.13:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [track_amplify.27:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [on_track.54:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [on_metadata.26:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [on_track.53:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [cross_after.13:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [buffer.26:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [fade_out.13:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [track_amplify.26:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [on_end.13:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [on_track.52:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [on_metadata.25:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [on_track.51:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [cross_before.13:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [buffer.25:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:47:27 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/feedback' with body: {
2023/12/05 12:47:27 [lang:3]   "song_id": "a44626ef3ba7fa60b40299ee2675ec45",
2023/12/05 12:47:27 [lang:3]   "playlist_id": "",
2023/12/05 12:47:27 [lang:3]   "media_id": "9203"
2023/12/05 12:47:27 [lang:3] }
2023/12/05 12:47:27 [lang:3] API nextsong - Response (200): annotate:title="Zuhause (Christmas Time)",artist="Vanessa Mai",duration="205.00",song_id="738e5652f9c25b8e354aa31c73ada880",media_id="11516",liq_cross_duration="3.50",liq_fade_out="3.50",liq_cue_in="0.80",liq_cue_out="202.90",playlist_id="23":media:Vanessa Mai - Zuhause (Christmas Time).mp3
2023/12/05 12:47:27 [lang:3] API feedback - Response (200): true
2023/12/05 12:47:27 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/schlager/media/Vanessa Mai - Zuhause (Christmas Time).mp3": {audio=pcm(stereo)}
2023/12/05 12:47:27 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/schlager/media/Vanessa Mai - Zuhause (Christmas Time).mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 500x500, yuvj444p}
2023/12/05 12:47:27 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/schlager/media/Vanessa Mai - Zuhause (Christmas Time).mp3": {audio=pcm(stereo)}
2023/12/05 12:50:08 [cue_next_song:3] Cueing out...
2023/12/05 12:50:08 [next_song:3] Prepared "/var/azuracast/stations/schlager/media/Vanessa Mai - Zuhause (Christmas Time).mp3" (RID 25).
[mp3float @ 0x7f62f1a40900] Could not update timestamps for skipped samples.
2023/12/05 12:50:08 [cue_next_song:3] Cueing in...
2023/12/05 12:50:08 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/nextsong' with body: 
2023/12/05 12:50:08 [cross:3] Analysis: -13.515341dB / -40.236751dB (0.28s / 0.28s)
2023/12/05 12:50:08 [source.46:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [audio.add.13:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [fade_in.14:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [track_amplify.29:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [on_track.58:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [on_metadata.28:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [on_track.57:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [cross_after.14:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [buffer.28:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [fade_out.14:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [track_amplify.28:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [on_end.14:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [on_track.56:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [on_metadata.27:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [on_track.55:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [cross_before.14:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [buffer.27:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:50:08 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/feedback' with body: {
2023/12/05 12:50:08 [lang:3]   "song_id": "738e5652f9c25b8e354aa31c73ada880",
2023/12/05 12:50:08 [lang:3]   "playlist_id": "23",
2023/12/05 12:50:08 [lang:3]   "media_id": "11516"
2023/12/05 12:50:08 [lang:3] }
2023/12/05 12:50:08 [lang:3] API nextsong - Response (200): annotate:title="Dropin 04",artist="RadioMonster.FM",duration="4.00",song_id="a61199df15d23c3f9a2ad1b52491c2af",media_id="9702",playlist_id="19",jingle_mode="true":media:Dropin 04.mp3
2023/12/05 12:50:08 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/schlager/media/Dropin 04.mp3": {audio=pcm(stereo)}
2023/12/05 12:50:08 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/schlager/media/Dropin 04.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2023/12/05 12:50:08 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/schlager/media/Dropin 04.mp3": {audio=pcm(stereo)}
2023/12/05 12:50:08 [lang:3] API feedback - Response (200): true
2023/12/05 12:53:27 [cue_next_song:3] Cueing out...
2023/12/05 12:53:27 [next_song:3] Prepared "/var/azuracast/stations/schlager/media/Dropin 04.mp3" (RID 26).
[mp3float @ 0x7f62f1ae9400] Could not update timestamps for skipped samples.
2023/12/05 12:53:27 [cue_next_song:3] Cueing in...
2023/12/05 12:53:27 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/nextsong' with body: 
2023/12/05 12:53:27 [cross:3] Analysis: -34.754003dB / -8.932521dB (3.44s / 3.44s)
2023/12/05 12:53:27 [fade_out.15:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [track_amplify.30:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [on_end.15:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [on_track.60:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [on_metadata.29:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [on_track.59:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [cross_before.15:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [buffer.29:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [fade_in.15:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [track_amplify.31:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [on_track.62:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [on_metadata.30:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [on_track.61:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [cross_after.15:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [buffer.30:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:27 [lang:3] API nextsong - Response (200): annotate:title="Ein weißes Boot (2023)",artist="Fantasy",duration="227.00",song_id="4e9421c9808b3c67f9167442c2b13712",media_id="10280",liq_cross_duration="1.90",liq_fade_out="1.90",liq_cue_in="0.70",liq_cue_out="224.40",playlist_id="18":media:Fantasy - Ein weißes Boot (2023).mp3
2023/12/05 12:53:27 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/schlager/media/Fantasy - Ein weißes Boot (2023).mp3": {audio=pcm(stereo)}
2023/12/05 12:53:27 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/schlager/media/Fantasy - Ein weißes Boot (2023).mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 500x500, yuvj444p}
2023/12/05 12:53:27 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/schlager/media/Fantasy - Ein weißes Boot (2023).mp3": {audio=pcm(stereo)}
2023/12/05 12:53:30 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/feedback' with body: {
2023/12/05 12:53:30 [lang:3]   "song_id": "a61199df15d23c3f9a2ad1b52491c2af",
2023/12/05 12:53:30 [lang:3]   "playlist_id": "19",
2023/12/05 12:53:30 [lang:3]   "media_id": "9702"
2023/12/05 12:53:30 [lang:3] }
2023/12/05 12:53:30 [lang:3] API feedback - Response (200): true
[mp3float @ 0x7f62f1ae9400] Could not update timestamps for discarded samples.
2023/12/05 12:53:34 [decoder:2] Decoding "/var/azuracast/stations/schlager/media/Dropin 04.mp3" ended: Ffmpeg_decoder.End_of_file.
2023/12/05 12:53:34 [next_song:3] Prepared "/var/azuracast/stations/schlager/media/Fantasy - Ein weißes Boot (2023).mp3" (RID 27).
[mp3float @ 0x7f62f1a17400] Could not update timestamps for skipped samples.
2023/12/05 12:53:34 [cue_next_song:3] Cueing in...
2023/12/05 12:53:34 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/4/liquidsoap/nextsong' with body: 
2023/12/05 12:53:34 [cross:3] Analysis: -13.537148dB / -34.990741dB (0.00s / 0.02s)
2023/12/05 12:53:34 [source.51:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [audio.add.14:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [fade_in.16:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [track_amplify.33:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [on_track.66:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [on_metadata.32:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [on_track.65:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [cross_after.16:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [buffer.32:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [fade_out.16:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [track_amplify.32:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [on_end.16:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [on_track.64:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [on_metadata.31:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [on_track.63:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [cross_before.16:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [buffer.31:3] Content type is {audio=pcm(stereo)}.
2023/12/05 12:53:34 [metadata_map.3:3] Inserting missing metadata.
2023/12/05 12:53:34 [lang:3] API nextsong - Response (200): annotate:title="Wer Hoffnung hat",artist="Susan Ebrahimi",duration="234.00",song_id="2166dfb0ffef3062e68f03ee4f3cc0d2",media_id="11191",liq_cross_duration="5.90",liq_fade_out="5.90",playlist_id="16":media:Susan Ebrahimi - Wer Hoffnung hat.mp3
2023/12/05 12:53:34 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/schlager/media/Susan Ebrahimi - Wer Hoffnung hat.mp3": {audio=pcm(stereo)}
2023/12/05 12:53:34 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/schlager/media/Susan Ebrahimi - Wer Hoffnung hat.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 500x500, yuvj444p}
2023/12/05 12:53:34 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/schlager/media/Susan Ebrahimi - Wer Hoffnung hat.mp3": {audio=pcm(stereo)}
```

**Comment by Moonbase59** [comment]
I noticed the same when skipping a song and the next up was a jingle: Jingle played, next song played but _without updating_ the "now playing" (neither on profile page nor on web player or API).

**Comment by unudelaradio** [comment]
I noticed that too, earlier today. Sometimes the now playing updates are freezing. Sometimes the refresh is happening on the middle of the song... But today i noticed that the metadata was totally missing, during the hole song. Both in AzuraCast Player and Winamp. Then i checked the Song Playback Timeline in AzuraCast: the title was missing there too.

**Comment by RM-FM** [comment]
@BusterNeece I finally found out, that missing meta data updates are related to where `on_metadata` is placed in the code. It **must** be placed before `cross` to work properly. I tested it with wild cue/fade settings and a very short jingle. It worked perfectly fine each time. Even without any "last <> current artist/title check" it did not fire more than once. Please find my test functions and the results (native, and before crossfade `on_metdata` + `on_track`) as screenshot below.

Until this has been tested properly and can be released with the stable release channel, I create a custom plugin. It will disable the Azuracast native function `metadata_updated` and inject it before the crossfade.

```
def track_updated(m) =

    def f() =

		artist = m["artist"]
		title = m["title"]
		
		if (artist != "" or title != "") then
			
			j = json()

			j.add("artist", artist)
			j.add("title", "#{title} [source.on_track]")	

			_ = azuracast_api_call(
				"feedback",
				json.stringify(j)
			)
			
		end

    end
	
    thread.run(f)
	
end
radio.on_track(track_updated)

def meta_updated(m) =

    def f() =

		artist = m["artist"]
		title = m["title"]
		
		if (artist != "" or title != "") then
			
			j = json()

			j.add("artist", artist)
			j.add("title", "#{title} [source.on_meta]")	

			_ = azuracast_api_call(
				"feedback",
				json.stringify(j)
			)
			
		end

    end
	
    thread.run(f)
	
end
radio.on_metadata(meta_updated)
```

![image](https://github.com/AzuraCast/AzuraCast/assets/40538914/12d0a214-7a5e-4e51-8668-131e4a57ac9a)

**Comment by Moonbase59** [comment]
The link doesn’t work, private Repo?

**Comment by RM-FM** [comment]
> The link doesn’t work, private Repo?

Sorry, should work now! Please consider that Azuracast native Crossfade should be disabled in order to make the template plugin settings work.

**Comment by Moonbase59** [comment]
Thanks for sharing, a nice concept and well done!

Btw, the link above still gets me a GH 404, but the repo is public now: https://github.com/RM-FM/RM-FM-AzuraCastPlugin-LSConfigReplace (one "RM-FM" missing in above)

**Comment by RM-FM** [comment]
@Moonbase59 While the problem with the metadata appears to be solved reliably, I noticed a side effect. Sometimes the crossfade point is ignored on short jingles - next track starts a little too early. This is problematic for us, as we send a short 18Hz signal at the end of each jingle, which indicates a slot for Ad injection server. I'm just looking into this more closely...

**Comment by Moonbase59** [comment]
Interesting, and I’m digressing … Is this some standard? Using 18 kHz for ad injection?

**Comment by RM-FM** [comment]
> Interesting, and I’m digressing … Is this some standard? Using 18 kHz for ad injection?

It's 18Hz but not kHz, actually. I don't think it's a standard but it is used by our ad injection provider as an alternative to meta data triggers. It allows very precise positioning between jingle and start of the next track (as long as the jingle is not unexpectedly faded like now with the meta data mod in place)

**Comment by RM-FM** [comment]
I was able to pinpoint the whole problem with the missing title information to a single cause. It's really all down to cue-out values that are too close to the end of the audio file. The example below shows our shortest jingle - it is 4.1137 seconds long. If I set cue-out 4.0, everything works perfectly with the metadata. But even 4.1 causes the title information of the next song to be missing. It seems that this problem does not occur if metadata_map is called before cross. However, the crossfade is then initiated much too early. Cue-out values on the edge therefore create a problem in both cases, although it does behave differently.

![Bildschirmfoto 2023-12-07 um 19 44 16](https://github.com/AzuraCast/AzuraCast/assets/40538914/2d6ef3e9-241b-4b55-b6ca-0d96d094ba9f)

The root cause should actually be fixed in Liquidsoap itself. But Azuracast can of course easily prevent this from happening by not allowing any values that cannot be handled correctly by Liquidsoap. As far as I know, the cue-out value in Liquidsoap is actually absolute but not relative. I would therefore assume that Azuracast calculates the absolute value (duration - cue out), perhaps with no or wrong rounding?

**Comment by Moonbase59** [comment]
An additional problem might be that with some files you can only guesstimate the actual duration beforehand. This might lead to the decoder running out of frames early. In general, I think, the intrinsics should be handled by LS.

**Comment by RM-FM** [comment]
Update: Title information of next track is also missing if a song with normal (not short as stated in the title) duration runs into the `Ffmpeg_decoder.End_of_file` error.

**Comment by RM-FM** [comment]
@Moonbase59 @BusterNeece
I created a related bug for Liquisoap: https://github.com/savonet/liquidsoap/issues/3610

**Comment by gAlleb** [comment]
@BusterNeece Hi! Just to keep you updated

Following https://github.com/savonet/liquidsoap/issues/3610 issue @toots's in the process of making a commit https://github.com/savonet/liquidsoap/pull/3617 that removes `cue_cut` operator and delegates its functions to file-based operators. 

Probably not much to change in Azuracast when the commit would be ready: just few lines of code in /src/Radio/Backend/Liquidsoap/`ConfigWriter.php`.

**Comment by Moonbase59** [comment]
Thanks for noting @RM-FM & @gAlleb. We indeed have to watch out for this (and re-test) when transitioning to the next Liquidsoap in AzuraCast.

**Comment by BusterNeece** [comment]
Thanks for letting me know; I'm in contact directly with the Liquidsoap folks and we're coordinating things so it won't have any impact on our releases.

**Comment by RM-FM** [comment]
@BusterNeece @Moonbase59 @gAlleb Latest AzuraCast Rolling Release still has the same issue. I actually hoped that the this will be solved with the latest Liquidsoap changes related to `cue_cut`. Unfortunately the behaviour is still the same... Not sure, but such log lines could possibly be a starting point for further analysis?

`[metadata_map.3:3] Inserting missing metadata.`

```
2024/01/19 20:35:57 [lang:3] API nextsong - Response (200): annotate:title="I'm Good (Blue)",artist="David Guetta, Bebe Rexha",duration="175.28",song_id="0abf0522646636fbded83c72804aa063",media_id="10",liq_amplify="0.00dB",liq_cross_duration="1.40",liq_fade_in="0.00",liq_fade_out="1.40",liq_cue_in="0.00",liq_cue_out="174.00",playlist_id="1":media:david_guetta,_bebe_rexha_-_im_good_(blue).mp3
2024/01/19 20:35:57 [on_end.4:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:35:57 [on_track.16:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:35:57 [on_metadata.7:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:35:57 [on_track.15:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:35:57 [cross_before.4:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:35:57 [buffer.7:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:35:57 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radiomonster.fm_test/media/david_guetta,_bebe_rexha_-_im_good_(blue).mp3": {audio=pcm(stereo)}
2024/01/19 20:35:57 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radiomonster.fm_test/media/david_guetta,_bebe_rexha_-_im_good_(blue).mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 500x500, yuvj444p}
2024/01/19 20:35:57 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radiomonster.fm_test/media/david_guetta,_bebe_rexha_-_im_good_(blue).mp3": {audio=pcm(stereo)}
[mp3float @ 0x7ff708079100] Could not update timestamps for discarded samples.
2024/01/19 20:36:01 [decoder:2] Decoding "/var/azuracast/stations/radiomonster.fm_test/media/dropin_04.mp3" ended: Ffmpeg_decoder.End_of_file.
2024/01/19 20:36:01 [next_song:3] Prepared "/var/azuracast/stations/radiomonster.fm_test/media/david_guetta,_bebe_rexha_-_im_good_(blue).mp3" (RID 10).
[mp3float @ 0x7ff70075ea00] Could not update timestamps for skipped samples.
2024/01/19 20:36:01 [cross:3] Analysis: -10.436788dB / -78.801895dB (0.00s / 0.02s)
2024/01/19 20:36:01 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/01/19 20:36:01 [source.19:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [audio.add.5:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [fade_in.5:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [track_amplify.11:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [on_track.22:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [on_metadata.10:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [on_track.21:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [cross_after.5:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [buffer.10:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [fade_out.5:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [track_amplify.10:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [on_end.5:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [on_track.20:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [on_metadata.9:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [on_track.19:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [cross_before.5:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [buffer.9:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:36:01 [metadata_map.3:3] Inserting missing metadata.
2024/01/19 20:36:01 [lang:3] API nextsong - Response (200): annotate:title="Dropin 04",artist="RadioMonster.FM",duration="4.00",song_id="a61199df15d23c3f9a2ad1b52491c2af",media_id="9",liq_cross_duration="0.00",liq_fade_in="0.00",liq_fade_out="0.00",liq_cue_in="0.00",playlist_id="2",jingle_mode="true":media:dropin_04.mp3
2024/01/19 20:36:01 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radiomonster.fm_test/media/dropin_04.mp3": {audio=pcm(stereo)}
2024/01/19 20:36:01 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radiomonster.fm_test/media/dropin_04.mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}
2024/01/19 20:36:01 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radiomonster.fm_test/media/dropin_04.mp3": {audio=pcm(stereo)}
2024/01/19 20:38:54 [next_song:3] Prepared "/var/azuracast/stations/radiomonster.fm_test/media/dropin_04.mp3" (RID 11).
[mp3float @ 0x7ff70075e500] Could not update timestamps for skipped samples.
2024/01/19 20:38:54 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/01/19 20:38:54 [lang:3] API nextsong - Response (200): annotate:title="When We Were Young (The Logical Song)",artist="David Guetta, Kim Petras",duration="147.44",song_id="5f289d53ee08f3aa88e4ec69212d45d1",media_id="12",liq_amplify="0.00dB",liq_cross_duration="3.60",liq_fade_in="0.00",liq_fade_out="3.60",liq_cue_in="0.00",liq_cue_out="144.70",playlist_id="1":media:david_guetta,_kim_petras_-_when_we_were_young_(the_logical_song).mp3
2024/01/19 20:38:54 [cross:3] Analysis: -20.000952dB / -9.524189dB (1.36s / 1.36s)
2024/01/19 20:38:54 [source.22:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [audio.add.6:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [fade_in.6:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [track_amplify.13:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [on_track.26:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [on_metadata.12:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [on_track.25:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [cross_after.6:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [buffer.12:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [fade_out.6:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [track_amplify.12:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [on_end.6:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [on_track.24:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [on_metadata.11:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [on_track.23:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [cross_before.6:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [buffer.11:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:54 [decoder.ffmpeg:3] Requested content-type for "/var/azuracast/stations/radiomonster.fm_test/media/david_guetta,_kim_petras_-_when_we_were_young_(the_logical_song).mp3": {audio=pcm(stereo)}
2024/01/19 20:38:54 [decoder.ffmpeg:3] FFmpeg recognizes "/var/azuracast/stations/radiomonster.fm_test/media/david_guetta,_kim_petras_-_when_we_were_young_(the_logical_song).mp3" as audio: {codec: mp3, 44100Hz, 2 channel(s)}, video: {codec: mjpeg, 500x500, yuvj444p}
2024/01/19 20:38:54 [decoder.ffmpeg:3] Decoded content-type for "/var/azuracast/stations/radiomonster.fm_test/media/david_guetta,_kim_petras_-_when_we_were_young_(the_logical_song).mp3": {audio=pcm(stereo)}
[mp3float @ 0x7ff70075e500] Could not update timestamps for discarded samples.
2024/01/19 20:38:58 [decoder:2] Decoding "/var/azuracast/stations/radiomonster.fm_test/media/dropin_04.mp3" ended: Ffmpeg_decoder.End_of_file.
2024/01/19 20:38:58 [next_song:3] Prepared "/var/azuracast/stations/radiomonster.fm_test/media/david_guetta,_kim_petras_-_when_we_were_young_(the_logical_song).mp3" (RID 12).
2024/01/19 20:38:58 [cross:3] Analysis: -10.527897dB / -77.444366dB (0.00s / 0.02s)
2024/01/19 20:38:58 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2024/01/19 20:38:58 [source.25:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [audio.add.7:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [fade_in.7:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [track_amplify.15:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [on_track.30:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [on_metadata.14:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [on_track.29:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [cross_after.7:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [buffer.14:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [fade_out.7:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [track_amplify.14:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [on_end.7:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [on_track.28:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [on_metadata.13:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [on_track.27:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [cross_before.7:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [buffer.13:3] Content type is {audio=pcm(stereo)}.
2024/01/19 20:38:58 [metadata_map.3:3] Inserting missing metadata.
```

**Comment by RM-FM** [comment]
@BusterNeece @Moonbase59 It seems that now even more meta data updates are missing than before.

**Comment by Moonbase59** [comment]
@RM-FM LS 2.3.0 is currently under heavy debugging/testing, let’s see what our friends from Liquidsoap come up with…

**Comment by RM-FM** [comment]
@BusterNeece @Moonbase59 Toots pushed another optimization that might fix this:
https://github.com/savonet/liquidsoap/issues/3610#issuecomment-1917419897

**Comment by RM-FM** [comment]
@BusterNeece @Moonbase59 @gAlleb I seems that Romain finally found the root cause for all the issues with short crossfades, clicks and missing meta data update. It just sounds smoother than anytime before.
Would be great if we can start testing this fix in Azurecast asap.

**Comment by RM-FM** [comment]
@BusterNeece yet another LS fix: https://github.com/savonet/liquidsoap/commit/d7d0ef0bd35b9ef21f6b4c523b2da20aee0e47f1

**Comment by BusterNeece** [comment]
@RM-FM deploying to rolling.

**Comment by RM-FM** [comment]
@BusterNeece The issue with missing meta data update as well as clicks on some of the crossfades was finally resolved with the latest LS 2.2.x Rolling Release.

**Comment by RM-FM** [comment]
@BusterNeece @Moonbase59 @gAlleb Successfully tested. No more missing meta data / title imformation.

**Comment by Moonbase59** [comment]
Confirm, working here on Rolling Release #[1e2aa03](https://github.com/AzuraCast/AzuraCast/commit/1e2aa033d2c7c266c084d6d37f24e02e106f637d) (2024-02-04 11:46).

**Comment by BusterNeece** [comment]
Excellent! Cheers to the LS team for their continued hard work on this.
