### ISSUE TITLE
issues with branding files

### ISSUE THREAD

**Issue by ofsaleem** [AzuraCast/AzuraCast#6992]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.5 Stable 

### What happened?

upon updating from a previous version my stations background was reset to the default. i went back into the station settings and tried reuploading my old background (also the album art was reset to default so i tried uploading those too) but this process fails somehow. the thumbnail of the uploaded image is broken, and i get a 404 when i try to view the background image. on my station page there is no background and the web console shows a 404.

![image](https://github.com/AzuraCast/AzuraCast/assets/7631554/5676e38e-5730-4df5-85a8-5ad6a9df63f6)

is there a new location expected somewhere for this media? i went into my files and checked, and my old `background.jpg` and `album_art.png` are sitting where they used to be, where azuracast's container sees it at `/var/azuracast/uploads/background.jpg`

it seems to be looking for `[stationurl]/static/uploads/praxisfm/background.1709621340.jpg` so i tried appending those numbers (the epoch date i guess?) to the filename where i had the file and it didn't help.

### Relevant log output

```shell
from browser console:
GET https://radio.zeropraxis.tv/static/uploads/praxisfm/background.1709622410.jpg 404 (Not Found)

in container logs:
azuracast  | nginx stdout | 2024/03/05 07:08:41 [warn] 164#164: *499 a client request body is buffered to a temporary file /tmp/nginx_client/4/2/0000000024, client: 172.29.0.5, server: localhost, request: "POST /api/station/1/custom_assets/background HTTP/1.1", host: "radio.zeropraxis.tv", referrer: "https://radio.zeropraxis.tv/station/1/branding"
```

**Comment by ofsaleem** [comment]
pls no stale :(

**Comment by BusterNeece** [comment]
@ofsaleem Unfortunately without any supporting logs I don't know specifically what's causing your problem in this case.

I'd suspect the file you're trying to upload is just too big and it's occupying too much RAM when the system tries to open it and resize it. You may want to try shrinking the file in a photo editor first, then uploading the smaller version to the web site. (Updating the amount of RAM that PHP can use is also totally possible, but is a more inconvenient process.)

**Comment by ofsaleem** [comment]
i provided the relevant output in those two log locations, im happy to provide the full log if you tell me which locations/files you want
i do not think it's a ram issue as the files are small (the default album art for example is 16kb) and both images worked for months prior

**Comment by BusterNeece** [comment]
@ofsaleem Just out of curiosity, I believe this is fixed in the latest Rolling Release, if you're okay with doing so, could you switch to the Rolling Release and see if that fixes things?

**Comment by smiths73v3** [comment]
@BusterNeece, I am still having this issue with Rolling Release #[1be10a0](https://github.com/AzuraCast/AzuraCast/commit/1be10a04171c1c64d5ab00ff8c3643c38b3d31cd) (2024-06-06 23:07)

**Comment by Vaalyn** [comment]
@smiths73v3 could you upload the file you are using?

I've tried with a .jpg from my disk which worked fine. Maybe it's something file specific not format specific.

**Comment by smiths73v3** [comment]
Does not work:
![AC_DBMeter](https://github.com/AzuraCast/AzuraCast/assets/49772122/2345e9a3-22c3-4ba3-8099-0a4936028119)
Is working:
![circuit_header_tex](https://github.com/AzuraCast/AzuraCast/assets/49772122/0b9005b2-b155-4729-b27f-75ebc91b869a)

**Comment by Vaalyn** [comment]
Seems to be working fine for me, tested the general branding page as well as the station specific one:

<img width="699" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/c3775053-f777-46ab-b304-0987ebc9a2e5">

<img width="848" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/49316fd1-b022-40fb-b614-4746f4d545d1">

<img width="1725" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/6f2b1782-c620-41a8-a7f3-39e0d25405d8">

**Comment by smiths73v3** [comment]
IDK, I had to do a manual update to the latest rolling release, and now it is working. Possibly something old was messing up my configuration. 

This is now working for me.

**Comment by ofsaleem** [comment]
i just updated to 0.20.5 stable and im still experiencing it. after update the branding on my station was reset to the defaults, and i have the same problems when trying to upload custom artwork again. heres the log of the station when i tried to upload stuff

```azuracast  | station_1_backend stdout | 
azuracast  | station_1_backend stdout | 2024/07/17 18:34:29 [next_song:3] Prepared "/var/music/[Soundtracks]/[2004] Katamari Fortissimo Damacy/flac/16 The Season of Cherry Blossom Colors [Katamaritai Jr].flac" (RID 6).
azuracast  | station_1_backend stdout | 2024/07/17 18:34:29 [lang:3] AutoDJ is ready!
azuracast  | station_1_backend stdout | 
azuracast  | nginx stdout | 2024/07/17 22:34:55 [warn] 153#153: *135 a client request body is buffered to a temporary file /tmp/nginx_client/3/0/0000000003, client: 172.29.0.7, server: localhost, request: "POST /api/station/1/custom_assets/album_art HTTP/1.1", host: "radio.zeropraxis.tv", referrer: "https://radio.zeropraxis.tv/station/1/branding"
azuracast  | nginx stdout | 
azuracast  | cron stdout | time="2024-07-17T22:35:00Z" level=info msg=starting iteration=0 job.command="azuracast_cli azuracast:sync:run" job.position=0 job.schedule="0 * * * * * *"
azuracast  | cron stdout | 
azuracast  | cron stdout | time="2024-07-17T22:35:01Z" level=info msg="job succeeded" iteration=0 job.command="azuracast_cli azuracast:sync:run" job.position=0 job.schedule="0 * * * * * *"
azuracast  | cron stdout | 
azuracast  | nginx stdout | 2024/07/17 22:35:08 [warn] 153#153: *140 a client request body is buffered to a temporary file /tmp/nginx_client/4/0/0000000004, client: 172.29.0.7, server: localhost, request: "POST /api/station/1/custom_assets/background HTTP/1.1", host: "radio.zeropraxis.tv", referrer: "https://radio.zeropraxis.tv/station/1/branding"
azuracast  | nginx stdout | ```

**Comment by ofsaleem** [comment]
here's the log from my browser when i upload a file
```background.1721324710.jpg:1 
        
        
       GET https://radio.zeropraxis.tv/static/uploads/praxisfm/background.1721324710.jpg 404 (Not Found)
Image (async)
gu @ vue-BJsHJXy-.js:17
vu @ vue-BJsHJXy-.js:17
F @ vue-BJsHJXy-.js:13
y @ vue-BJsHJXy-.js:13
V @ vue-BJsHJXy-.js:13
N @ vue-BJsHJXy-.js:13
F @ vue-BJsHJXy-.js:13
y @ vue-BJsHJXy-.js:13
V @ vue-BJsHJXy-.js:13
N @ vue-BJsHJXy-.js:13
F @ vue-BJsHJXy-.js:13
y @ vue-BJsHJXy-.js:13
V @ vue-BJsHJXy-.js:13
A @ vue-BJsHJXy-.js:13
run @ vue-BJsHJXy-.js:9
D.f.update @ vue-BJsHJXy-.js:13
Ue @ vue-BJsHJXy-.js:13
Bi @ vue-BJsHJXy-.js:13
Promise.then (async)
ki @ vue-BJsHJXy-.js:13
Xn @ vue-BJsHJXy-.js:13
(anonymous) @ vue-BJsHJXy-.js:13
Gs @ vue-BJsHJXy-.js:9
Ti @ vue-BJsHJXy-.js:9
Rt @ vue-BJsHJXy-.js:9
set value @ vue-BJsHJXy-.js:9
(anonymous) @ CustomAssetForm-DNMgA1FT.js:1
Promise.then (async)
r @ CustomAssetForm-DNMgA1FT.js:1
(anonymous) @ vue-BJsHJXy-.js:13
Ue @ vue-BJsHJXy-.js:13
we @ vue-BJsHJXy-.js:13
t.__weh.t.__weh @ vue-BJsHJXy-.js:13
Fn @ vue-BJsHJXy-.js:13
Bi @ vue-BJsHJXy-.js:13
Promise.then (async)
ki @ vue-BJsHJXy-.js:13
Xn @ vue-BJsHJXy-.js:13
(anonymous) @ vue-BJsHJXy-.js:13
Gs @ vue-BJsHJXy-.js:9
Ti @ vue-BJsHJXy-.js:9
Rt @ vue-BJsHJXy-.js:9
set value @ vue-BJsHJXy-.js:9
Ee @ router-BbRCMRIF.js:5
(anonymous) @ router-BbRCMRIF.js:5
Promise.then (async)
U @ router-BbRCMRIF.js:5
M @ router-BbRCMRIF.js:5
install @ router-BbRCMRIF.js:5
use @ vue-BJsHJXy-.js:13
vn @ router-BbRCMRIF.js:5
(anonymous) @ Stations-Bu0b5QIA.js:2
window.vueComponent @ usePlayerStore-E9aqxeN9.js:7
await in window.vueComponent (async)
(anonymous) @ branding:64
branding:1 Error handling response: TypeError: Cannot read properties of undefined (reading 'isCheckout')
    at chrome-extension://clmkdohmabikagpnhjmgacbclihgmdje/content-script.js:1:5043
branding:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
branding:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
album_art.1721324776.png:1 
        
        
       GET https://radio.zeropraxis.tv/static/uploads/praxisfm/album_art.1721324776.png 404 (Not Found)
Image (async)
gu @ vue-BJsHJXy-.js:17
vu @ vue-BJsHJXy-.js:17
F @ vue-BJsHJXy-.js:13
y @ vue-BJsHJXy-.js:13
V @ vue-BJsHJXy-.js:13
N @ vue-BJsHJXy-.js:13
F @ vue-BJsHJXy-.js:13
y @ vue-BJsHJXy-.js:13
V @ vue-BJsHJXy-.js:13
N @ vue-BJsHJXy-.js:13
F @ vue-BJsHJXy-.js:13
y @ vue-BJsHJXy-.js:13
V @ vue-BJsHJXy-.js:13
A @ vue-BJsHJXy-.js:13
run @ vue-BJsHJXy-.js:9
D.f.update @ vue-BJsHJXy-.js:13
Ue @ vue-BJsHJXy-.js:13
Bi @ vue-BJsHJXy-.js:13
Promise.then (async)
ki @ vue-BJsHJXy-.js:13
Xn @ vue-BJsHJXy-.js:13
(anonymous) @ vue-BJsHJXy-.js:13
Gs @ vue-BJsHJXy-.js:9
Ti @ vue-BJsHJXy-.js:9
Rt @ vue-BJsHJXy-.js:9
set value @ vue-BJsHJXy-.js:9
(anonymous) @ CustomAssetForm-DNMgA1FT.js:1
Promise.then (async)
r @ CustomAssetForm-DNMgA1FT.js:1
(anonymous) @ CustomAssetForm-DNMgA1FT.js:1
Promise.finally (async)
g @ CustomAssetForm-DNMgA1FT.js:1
Ue @ vue-BJsHJXy-.js:13
we @ vue-BJsHJXy-.js:13
bc @ vue-BJsHJXy-.js:13
a @ FormFile-DLgVtGx5.js:1
Ue @ vue-BJsHJXy-.js:13
we @ vue-BJsHJXy-.js:13
n @ vue-BJsHJXy-.js:17
```

**Comment by ofsaleem** [comment]
not stale, still experiencing the issue

**Comment by ofsaleem** [comment]
Not stale, still experiencing the issue last I tried and still have not received an answer on where the files are stored and if that changed in an update so I can just stick the files there myself. I provided logs I could and don't know what else I can provide

**Comment by BusterNeece** [comment]
@ofsaleem When you update, are you updating via `./docker.sh update` or via the web updater?

In the last few stable versions, we've moved system-wide uploads to `/var/azuracast/storage/uploads`, so that we can consolidate several separate Docker volumes into a single one that hosts `/var/azuracast/storage` on new installations.

In order to facilitate that change, we have to update `docker-compose.yml`, which doesn't happen if you use the web updater; in the vast majority of cases, using the web updater is completely fine (and in this case, it actually should be working too, because we do check the old directories looking for those files, but there's apparently something going wrong there), but in this one case it's beneficial to use the `./docker.sh` SSH-based updater in order to pick up that Docker Compose file change.

So the long and short is, if you haven't updated via the SSH updater, I'd recommend doing so and making sure your `docker-compose.yml` file was updated to reflect the new path.

Much of the reason for the delay was because your logs unfortunately don't really provide much extra info in terms of what's going wrong. That's not your fault at all, it's just a tricky issue to solve.
