### ISSUE TITLE
AutoCue Automatic Detection fails to process playlists, blocks DJ's

### ISSUE THREAD

**Issue by kryptonmediagroup** [AzuraCast/AzuraCast#7174]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.20.1 Stable • Docker • PHP 8.3

### What happened?

The update was slower than expected, it took three minutes to do the update, and the restart of the Azuracast services  timed out.
Then when I did  go in and turn that toggle on, it played **one** track, and then played the default Azuracast announcement bumper, and then wouldn't play anything else.  This behavior of playing only one track from my playlists and then transitioning to the Azuracast announcement bumper persisted over five restarts.  It was only when I turned the toggle OFF that normal behavior was restored.

Also, so long as the toggle was "on", DJ's could not connect.  When the toggle was turned "off", the connection issue immediately went away.

**Comment by Moonbase59** [comment]
Wouldn’t know why DJs can’t conncect. This might have to be investigated but I think it shouldn’t be related to autocue.

Startup: Yes. In order to be ready for immediate playout, Liquidsoap decides to process the first two songs of _each_ playlist when starting, in case of fallbacks. If you have many playlists (I have ~70 per station!), that can really hog the CPUs at startup, especially when you have files that are large, long or hard to calculate.

Can’t be helped the way Liquidsoap operates. It _might_ lead to having the fallback file or some jingles playing when a station is restarted (which hopefully isn’t very often!). CPU load will go down and things behave normally after a few minutes. For instance, I have a 4 CPU, 4 GB VM running 4 stations with ~160k songs and ~70 playlists per station. Startup shows a load average of ~8 for 5–7 minutes, then when all is autocued, it goes down to 0.7–0.9 again and stays there in normal operation.

See also https://moonbase59.github.io/autocue/presentation/autocue.html#/initial-startup in the presentation.

The good news: If you store the autocue _tags_ in your files, it will almost be immediately, since autocue can then skip the costly analysis step.

See https://moonbase59.github.io/autocue/presentation/autocue.html#/using-pre-tagged-files-is-fast in the presentation.

**Comment by darellrazk** [comment]
Running the same issue. 
Here are my logs, please help
Liquidsoap config: https://pastebin.com/print/U2pPEaB4
Logs: https://pastebin.com/print/2NPi93RR

**Comment by Vaalyn** [comment]
👋 We've just merged a new Advanced Feature that let's you turn off the generation of `playlist_xyz` definitions in the LS code if they are not explicitly needed in LS. Most of the time they wouldn't be needed there as normally most things are handled by the `request.dynamic`.

This should potentially cut down the number of playlists AutoCue has to prepare on startup dramatically and thus decrease load & startup time if this switch is turned off.

Would you mind trying this out to see how much impact this has in the real world?

<img width="1082" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/f70aa1df-1006-4a6c-98a8-2ec439df76b9">

**Comment by darellrazk** [comment]
The behavior is still the same for me. The station does not start after enabling **autocue**.
![Screenshot 2024-06-10 233250](https://github.com/AzuraCast/AzuraCast/assets/171890474/401f7c66-6a13-4d9a-9233-e908a6ebfd60)
![Screenshot 2024-06-10 233408](https://github.com/AzuraCast/AzuraCast/assets/171890474/37e0b683-c5a5-42a4-b221-bc0417f20e6e)
![Screenshot 2024-06-10 233328](https://github.com/AzuraCast/AzuraCast/assets/171890474/2a568ba5-9241-4296-b8ee-bb9a997a433d)
