### ISSUE TITLE
Titelupdate Shoutcast to AzuraCast

### ISSUE THREAD

**Issue by Aealyn** [AzuraCast/AzuraCast#7320]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#5dc00dd (2024-07-12 7:58)

### What happened?

Hello everyone,

For about 5 days I've had a problem with AzuraCast where the title of the ShoutCast streams is no longer updated in AzuraCast when a DJ or a moderator is connected. With AutoDJ the title update works without any problems.

I've already checked several things and unfortunately I can't get any further. 

AutoDJ --> Songs are displayed correctly in the player, in the ShoutCast Admin and in Azura

DJ / Moderator connected --> Songs are displayed correctly in the player and in the ShoutCast Admin, but with the Azura the last song from the AutoDJ is still there and this for the entire duration until the moderator hands the stream back to the AutoDJ.

Can someone please tell me why this is?

Rolling Release #5dc00dd (2024-07-12 7:58) • Docker • PHP 8.3
![azurastream](https://github.com/user-attachments/assets/bd897387-7bee-44b5-866e-d243ea1d9a11)
![player_title](https://github.com/user-attachments/assets/86b439b9-cda3-494b-bd95-99eac3736486)
![shoutcast](https://github.com/user-attachments/assets/47908397-d9bb-4ff3-9b8c-231c8ec35cde)

### Relevant log output

```shell
2024/07/13 16:00:29 [input_streamer:3] New metadata chunk ? -- Megawatt - Felsafescht.
2024/07/13 16:00:34 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/15/liquidsoap/feedback' with body: {"title":"Megawatt - Felsafescht"}
2024/07/13 16:00:34 [lang:3] API feedback - Response (200): false
```

**Comment by hwalker928** [comment]
Likely related to #7305

**Comment by BusterNeece** [comment]
@Aealyn I suspect this was caused by some minor updates we've done to metadata transmission; I've updated the code to better match how we used to process metadata, which should fix situations like this where all we get are a "title" value.

**Comment by Aealyn** [comment]
Thank you. As soon as the update is available, I will install it and report whether it works as desired again

**Comment by BusterNeece** [comment]
@Aealyn It should be available now.

**Comment by hwalker928** [comment]
Commit https://github.com/AzuraCast/AzuraCast/commit/659c749f2a0f1e6b3937a80e173fbad88a3dfa8e
(It's saying the last played song by the AutoDJ is still live, even though I am live via Icecast)
![duNfOVB62Y](https://github.com/user-attachments/assets/4526837d-8c4a-4b49-9438-76a0a4587214)

Commit https://github.com/AzuraCast/AzuraCast/commit/2ff8c7697f6992f40dc4460e8fc32d4a60729e6c
(Just shows blank metadata, but at least it says I'm the streamer)
![JYbJs8thQW](https://github.com/user-attachments/assets/d9fb3df2-8241-418a-b4b1-36c4619fa4d8)

**Comment by Aealyn** [comment]
> @AealynEs sollte jetzt verfügbar sein.

Thank you, as soon as we no longer have live broadcasts, I will update :) However, my customers are currently broadcasting

**Comment by Aealyn** [comment]
> Commit [659c749](https://github.com/AzuraCast/AzuraCast/commit/659c749f2a0f1e6b3937a80e173fbad88a3dfa8e) (Es besagt, dass das zuletzt vom AutoDJ gespielte Lied noch live ist, obwohl ich über Icecast live bin) ![duNfOVB62Y](https://private-user-images.githubusercontent.com/63236817/348532867-4526837d-8c4a-4b49-9438-76a0a4587214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTE4NTksIm5iZiI6MTcyMDk1MTU1OSwicGF0aCI6Ii82MzIzNjgxNy8zNDg1MzI4NjctNDUyNjgzN2QtOGM0YS00YjQ5LTk0MzgtNzZhMGE0NTg3MjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDEwMDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmY2UwOGFiNjRhM2RhYmU0NzA1NjE4ZjBjYmIxMzBmYzJmMzY1M2M4NWE2MmEwYTg0NmQxYmEyZjMyMGExZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EfOGlmuwDk7InhVrROxzGdCJ8RwgnDSASoAHFCvkq0E)
> 
> Commit [2ff8c76](https://github.com/AzuraCast/AzuraCast/commit/2ff8c7697f6992f40dc4460e8fc32d4a60729e6c) (Zeigt nur leere Metadaten, aber es heißt zumindest, dass ich der Streamer bin) ![JYbJs8thQW](https://private-user-images.githubusercontent.com/63236817/348532797-d9fb3df2-8241-418a-b4b1-36c4619fa4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTE4NTksIm5iZiI6MTcyMDk1MTU1OSwicGF0aCI6Ii82MzIzNjgxNy8zNDg1MzI3OTctZDlmYjNkZjItODI0MS00MThhLWI0YjEtMzZjNDYxOWZhNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDEwMDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3N2QxMTcxNzVhYmU5OTE2ZDRkMmU4ZGIwZmRhZDdhOTVmZTc2NGUyYjhhZGRiOGM1MTJlMDE0YmQ2YjhiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yuy49_rbUJZ8QiYOKvRbSR2vUFcCWZ-rIcq3_ro_IcM)

so still no change? But now no data is being transferred at all? That is not the purpose of the matter either. Title advertisements must be available for the collecting societies in Germany, if technically possible. And in most cases this is easily possible with almost every common broadcast program. The data is transferred somehow, because the right song is in the IceCast / Shoutcast Admin and in the player, just not in the AzuraCast and therefore not in the history

**Comment by BusterNeece** [comment]
@Aealyn That actually _should_ have fixed the issue as far as I can tell. It may merit further investigation, testing, and perhaps more looking at the Liquidsoap logs.

We haven't intended to make any changes to how we report tracks; we're working to resolve this as a bug, not changing anything fundamental in how we collect artist/title data.

**Comment by Aealyn** [comment]
> @AealynSoweit ich das beurteilen kann, _sollte_ das Problem damit eigentlich behoben sein. Es kann weitere Untersuchungen, Tests und vielleicht einen genaueren Blick auf die Liquidsoap-Protokolle wert sein.
> 
> Es ist nicht unsere Absicht, Änderungen an der Art und Weise vorzunehmen, wie wir Titel melden. Wir arbeiten daran, diesen Fehler zu beheben, ohne jedoch grundlegende Änderungen an der Art und Weise vorzunehmen, wie wir Künstler-/Titeldaten erfassen.

I was now referring to Harry W.'s answer, as he seems to have already tested it. 

Unfortunately, I can't test it at the moment because it broadcasts until 10 p.m. And I can't make such updates in live operation.

And if you look at Harry W.'s data, it doesn't look to me like the error has been fixed. (Of course it could be that I'm interpreting it wrong, I don't want to deny that now). Because when it comes to data, it looks as if no meta data is being transferred with Live anymore?

And yes, I know that it's not your intention :) And that you're trying everything to fix the errors as quickly as possible

**Comment by BusterNeece** [comment]
@Aealyn That's my point...Harry's test is not conclusive, it could point to another issue, and it also doesn't include relevant Liquidsoap logs.

I wouldn't write the issue off as unfixed until you update on your installation later today.

**Comment by BusterNeece** [comment]
@hwalker928 Can you post the Liquidsoap log with the updated commit to see what it's saying in the Feedback response? The relevant portion of code on our end should be fixed, but you may be running into a separate issue where the metadata being sent is empty for some reason.

**Comment by hwalker928** [comment]
@BusterNeece It looks like the issue of now playing not updating at all is fixed, but the API is still returning `""` for the metadata on the initial connection.

Liquidsoap logs: https://bin.harryw.link/zuleqirice

**Comment by Aealyn** [comment]
Yes, the meta data is now changed and displayed again for live connections. Thank you for that :)

But, on the first connection, only Live Broadcast is there and not the meta data of the first song that the person plays. Although according to the player this was also transmitted. What could be the reason now?

2024/07/14 22:11:59 [lang:3] API auth - Response (200): true
2024/07/14 22:11:59 [input_streamer:3] New metadata chunk ? -- Intro - Sagira.
2024/07/14 22:12:03 [live_fallback:3] Switch to insert_metadata with transition.
2024/07/14 22:12:03 [metadata_map.3:3] Inserting missing metadata.
2024/07/14 22:12:03 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {"title":"Live Broadcast"}
2024/07/14 22:12:04 [lang:3] API feedback - Response (200): true
2024/07/14 22:13:05 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/auth' with body: { "user": "", "password": "" } (Username und Passwort removed)
2024/07/14 22:13:05 [lang:3] API auth - Response (200): true
2024/07/14 22:13:05 [input_streamer:3] New metadata chunk ? -- Max Giesinger - Zuhause.
2024/07/14 22:13:10 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {"title":"Max Giesinger - Zuhause"}
2024/07/14 22:13:11 [lang:3] API feedback - Response (200): true
2024/07/14 22:16:38 [lang:3] API auth - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/auth' with body: { "user": "carina", "password": "Lalala" }
2024/07/14 22:16:39 [lang:3] API auth - Response (200): true
2024/07/14 22:16:39 [input_streamer:3] New metadata chunk ? -- Rob & Chris - Zeitmaschine - 90s Mix.
2024/07/14 22:16:44 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {"title":"Rob & Chris - Zeitmaschine - 90s Mix"}
2024/07/14 22:16:44 [lang:3] API feedback - Response (200): true


Intro Sagira is transmitted as meta data from the broadcast program, but "live broadcasting" arrives and then the correct meta data only from the second song onwards

**Comment by BusterNeece** [comment]
Pinging @toots on this one again...it seems we still have some cases where the first chunk of metadata isn't making it through to the "feedback" push, despite us having the relevant code in place to set the last valid metadata when transitioning to a live stream.

Here's the LS code we're writing, based on your recommendations:

```
# Live Broadcasting
            live = input.harbor({$harborParams})
            
            last_live_meta = ref([])

            def insert_missing(m) =
                def updates =
                    if m == [] then
                        [("title", "{$liveBroadcastText}"), ("is_live", "true")]
                    else
                        [("is_live", "true")]
                    end
                end
                last_live_meta := [...m, ...updates]
                updates
            end
            live = metadata.map(insert_missing, live)
            
            live = insert_metadata(live)
            def insert_latest_live_metadata() =
              live.insert_metadata(last_live_meta())
            end
            
            def transition_to_live(_, s) =
              insert_latest_live_metadata()
              s
            end
            
            def transition_to_radio(_, s) = s end
            
            radio = fallback(
              id="live_fallback",
              track_sensitive=false,
              replay_metadata=true,
              transitions=[transition_to_live, transition_to_radio],
              [live, radio]
            )
```

But the logs shown by the users above actually show an initial metadata packet being received (and even logged), and then somehow being _lost_ somewhere in the process and not being transferred to subsequent steps.

**Comment by toots** [comment]
@BusterNeece are y'all logging the metadata injection and transition? It'd be nice to see something like this:
```liquidsoap
# Live Broadcasting
            live = input.harbor({$harborParams})
            
            last_live_meta = ref([])

            def insert_missing(m) =
                def updates =
                    if m == [] then
                        [("title", "{$liveBroadcastText}"), ("is_live", "true")]
                    else
                        [("is_live", "true")]
                    end
                end
                last_live_meta := [...m, ...list.assoc.remove("title", updates)]
                updates
            end
            live = metadata.map(insert_missing, live)
            
            live = insert_metadata(live)
            def insert_latest_live_metadata() =
              log("Inserting last live meta: #{last_live_meta()}")
              live.insert_metadata(last_live_meta())
            end
            
            def transition_to_live(_, s) =
              log("executing transition to live")
              insert_latest_live_metadata()
              s
            end
            
            def transition_to_radio(_, s) = s end
            
            radio = fallback(
              id="live_fallback",
              track_sensitive=false,
              replay_metadata=true,
              transitions=[transition_to_live, transition_to_radio],
              [live, radio]
            )
```
Also, does the title double in the metadata? I would filter it out when inserting a new title. See above code.

**Comment by BusterNeece** [comment]
@toots Updated latest rolling release to incorporate the logging updates and to avoid doubling up on "title". I didn't realize it would actually double up on values with the same "keys" as it were.
