### ISSUE TITLE
Album art missing on public widgets

### ISSUE THREAD

**Issue by netbladenl** [AzuraCast/AzuraCast#7721]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#be54088

### What happened?

After the last few updates the album art covers on the public widgets pages are one.
To reproduce /public/yourstation/embed-requests

<img width="235" alt="Image" src="https://github.com/user-attachments/assets/b42ddea4-006e-4fde-b974-228413bf4b1d" />

### Relevant log output

```shell

```

**Comment by unudelaradio** [comment]
I can confirm this.

**Comment by move-IT-online** [comment]
same here

**Comment by Artem89233** [comment]
Rolling Release #[6d7ae1f]

![Image](https://github.com/user-attachments/assets/fed59b14-b896-4b30-93ee-c4671f0981b6)

It also doesn't show the song's cover.

**Comment by BusterNeece** [comment]
Fixed in the latest Rolling Release. Sorry for the trouble!

**Comment by igoiglesias** [comment]
When it will be on the stable release? I'm runing v0.21.0 Stable and still have this problem

**Comment by sonicsilhouette** [comment]
Hi,

This is still a thing in Rolling Release fe6f9c0. The public page will show the artwork correctly but no the widget.

**Comment by BusterNeece** [comment]
Should be fixed in latest Rolling.

**Comment by sonicsilhouette** [comment]
I confirm, it's fixed on my side with release #d41c22d.
