### ISSUE TITLE
Unable to create a sftp user

### ISSUE THREAD

**Issue by silverraindog** [AzuraCast/AzuraCast#8018]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

When trying to add an sftp user. We are getting "Object(App\Entity\SftpUser).password: This value should not be blank. (code c1051bb4-d103-4f74-8988-acbcafc7fdc3)". The ssh public key is blank, although I did add this in and it still produced an error. I have updated to the latest version. We are behind Nginx Proxy Manager but I have also tried directly to azuracast (changed the http port to 9090) and it still gives this error message. I don't see anything in the logs. Any help would be appreciated

### Relevant log output

```shell

```

**Comment by BusterNeece** [comment]
@silverraindog Fixed in the latest Rolling Release. Thank you!

**Comment by silverraindog** [comment]
I have updated to the latest image and this is still an issue

**Comment by silverraindog** [comment]
nevermind, it seems I did not follow the correct update procedure. Once I did docker.sh update-self and update, it started working, thank you for the assistance and quick reply!
