### ISSUE TITLE
The type of the "autodj_bitrate" attribute for class "App\Entity\StationMount" must be one of "int", "null" ("string" given).

### ISSUE THREAD

**Issue by carlojou** [AzuraCast/AzuraCast#8183]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.23.1

### What happened?

Hello,

This error is still occurring on the new stable version (0.23.1) of AzuraCast.

`The type of the "autodj_bitrate" attribute for class "App\Entity\StationMount" must be one of "int", "null" ("string" given).`

Was reported fixed on my old issue but seems to still be happening: https://github.com/AzuraCast/AzuraCast/issues/8121

### Relevant log output

```shell
The type of the "autodj_bitrate" attribute for class "App\Entity\StationMount" must be one of "int", "null" ("string" given).
```

**Comment by BusterNeece** [comment]
@carlojou Is this fixed in the latest Rolling Release? It certainly should be...I can't reproduce it on the latest Rolling.

**Comment by carlojou** [comment]
> [@carlojou](https://github.com/carlojou) Is this fixed in the latest Rolling Release? It certainly should be...I can't reproduce it on the latest Rolling.


Unfortunately not, still getting it on the latest rolling release.

The type of the "autodj_bitrate" attribute for class "App\Entity\StationMount" must be one of "int", "null" ("string" given).

**Comment by BusterNeece** [comment]
@carlojou Yeah, can't reproduce this on rolling no matter what I try.

Are you making a manual API call by chance? Or is this happening inside our web UI? 

If you're doing an API call, you should just convert the values into integers (remove the quotes around them in JSON, for example); if not, what settings are you using to trigger the problem if you're using the web UI?
