### ISSUE TITLE
Initial setup fails, base URL keeps redirecting to setup wizard

### ISSUE THREAD

**Issue by wagwan-piffting-blud** [AzuraCast/AzuraCast#8228]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #9833591 (2025-10-28 18:04)

### What happened?

I am trying to set up Azuracast for the first time. When running the install script, everything goes fine, I am then able to access the "create superuser" page. I then enter my station details, and then a "You must be logged in to do that" banner flashes _very_ briefly, then I get redirected to administration. When visiting the base URL again, I get asked to set up a station... again. And repeat, ad nauseum. I am unable to configure the program fully due to this issue. 

My system:

Linux Ubuntu 24.04.3 LTS
Kernel: Linux 6.8.0-85-generic
Docker: version 28.5.1, build e180ab8

Thanks.

Wags

### Relevant log output

```shell
** Running startup script '/etc/my_init.d/00_disable_mariadb.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/00_disable_redis.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/00_setup_user.sh'...
usermod: no changes
Docker 'azuracast' User UID: 1000
Docker 'azuracast' User GID: 1000
** Startup script complete.
** Running startup script '/etc/my_init.d/01_self_signed_ssl.sh'...
Generating self-signed certificate...
.....+.............+..+.+...+.........+........+............+.+.....+.+.....+....+......+.....+...+.+..+..................+.+...+.................+.+++++++++++++++++++++++++++++++++++++++*........+.+.....+....+...+...+..+..........+...+.....+......+...+.+..+++++++++++++++++++++++++++++++++++++++*....+.....+.+...+.....+......+.+..............+...+............+....+..+.........+......+............+.+..+.............+.....+.........+.......+......+..+...+...+.+......+........+.+.....+....+.....+....+......+.........+..+...+..........+...+.....+...+.+.........+........................+..+......+...+.+......+........++++++
..........+...+....+.....+...+.+..+.......+...+.........+...+............+......+..+.+.....+.+...+........+....+...+..+......+++++++++++++++++++++++++++++++++++++++*.........+.......+......+..+...+++++++++++++++++++++++++++++++++++++++*.+...+.+.....+......+.........+...............+...+.+............+..+.............+..+.+......+..............+............+..........+.....+............+..........+.....+.+..+..........+.....+.........++++++
-----
** Startup script complete.
** Running startup script '/etc/my_init.d/02_install_extra_packages.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/03_persist_dir.sh'...
Creating persist directories...
** Startup script complete.
** Running startup script '/etc/my_init.d/04_mariadb_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/05_centrifugo_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/05_nginx_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/05_setup_db.sh'...
2025-10-31 06:27:26+00:00 [Note] [Entrypoint]: Initial DB setup...
2025-10-31 06:27:26+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2025-10-31 06:27:26+00:00 [Note] [Entrypoint]: Initial DB setup...
2025-10-31 06:27:27+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
** Startup script complete.
** Running startup script '/etc/my_init.d/06_php_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/07_sftpgo_conf.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/08_plugin_mode.sh'...
** Startup script complete.
** Running startup script '/etc/my_init.d/10_clear_temp.sh'...
** Startup script complete.
** Running Supervisord...
2025-10-31 06:27:27,200 WARN No file matches via include "/var/azuracast/stations/*/config/supervisord.conf"
2025-10-31 06:27:27,200 INFO Included extra file "/etc/supervisor/supervisord.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/minimal.conf.d/mariadb.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/minimal.conf.d/redis.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/full.conf.d/centrifugo.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/full.conf.d/cron.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/full.conf.d/nginx.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/full.conf.d/php-fpm.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/full.conf.d/php-nowplaying.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/full.conf.d/php-worker.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/full.conf.d/sftpgo.conf" during parsing
2025-10-31 06:27:27,201 INFO Included extra file "/etc/supervisor/full.conf.d/startup.conf" during parsing
2025-10-31 06:27:27,201 INFO Set uid to user 0 succeeded
2025-10-31 06:27:27,208 INFO RPC interface 'supervisor' initialized
2025-10-31 06:27:27,208 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2025-10-31 06:27:27,208 INFO supervisord started with pid 7
2025-10-31 06:27:28,210 INFO spawned: 'stdout' with pid 114
2025-10-31 06:27:28,211 INFO spawned: 'mariadb' with pid 115
2025-10-31 06:27:28,213 INFO spawned: 'redis' with pid 116
2025-10-31 06:27:28,215 INFO spawned: 'startup' with pid 117

Waiting for cache service (Redis) to become available...
========================================================

 Waiting...
 Services started up and ready!


Waiting for database (MariaDB) to become available...
=====================================================

 Waiting...
 Services started up and ready!

2025-10-31 06:27:29,463 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-10-31 06:27:29,463 INFO success: mariadb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-10-31 06:27:29,463 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-10-31 06:27:29,463 INFO success: startup entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

AzuraCast Initializing...
=========================

Running Database Migrations
---------------------------


Database Migrations
===================


 [OK] Metadata storage synchronized

 [OK] Database is already up to date!


Reload System Data
------------------


 [OK] Local cache flushed.


Refreshing All Stations
-----------------------


 [OK] Unplayed station queues cleared.


Restarting all radio stations...
--------------------------------



 [OK] All stations restarted.

 [OK] App initialization completed successfully.


 [ERROR] Skipping LetsEncrypt; no domain(s) set.

    0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]06:27:30 WARNING   [AzuraCast] Console command `azuracast:acme:get-certificate` exited with error code 1.
redis stdout | 116:M 31 Oct 2025 06:27:28.225 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis stdout |
redis stdout | 116:M 31 Oct 2025 06:27:28.225 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
redis stdout | 116:M 31 Oct 2025 06:27:28.225 * Valkey version=8.1.1, bits=64, commit=00000000, modified=0, pid=116, just started
redis stdout | 116:M 31 Oct 2025 06:27:28.225 * Configuration loaded
redis stdout |
redis stdout | 116:M 31 Oct 2025 06:27:28.226 * monotonic clock: POSIX clock_gettime
redis stdout |
redis stdout | 116:M 31 Oct 2025 06:27:28.226 * Running mode=standalone, port=6379.
redis stdout |
redis stdout | 116:M 31 Oct 2025 06:27:28.231 * Server initialized
redis stdout |
redis stdout | 116:M 31 Oct 2025 06:27:28.231 * Ready to accept connections tcp
redis stdout | 116:M 31 Oct 2025 06:27:28.231 * Ready to accept connections unix
redis stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] Starting MariaDB 11.8.3-MariaDB-deb13 source revision b565b3e7e041c480fd8013e3beec6b99544d6bf8 server_uid 8v5LsP8BBLJXTheWAjiUZ6no9YE= as process 115
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: Compressed tables use zlib 1.3.1
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: Number of transaction pools: 1
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mariadb stdout | 2025-10-31  6:27:28 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Warning] mariadbd: io_uring_queue_init() failed with EPERM: sysctl kernel.io_uring_disabled has the value 2, or 1 and the user of the process is not a member of sysctl kernel.io_uring_group. (see man 2 io_uring_setup).
mariadb stdout |
mariadb stdout | create_uring failed: falling back to libaio
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: Using Linux native AIO
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: innodb_buffer_pool_size_max=128m, innodb_buffer_pool_size=128m
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: End of log at LSN=1389885
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: Opened 3 undo tablespaces
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: log sequence number 1389885; transaction id 808
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mariadb stdout | 2025-10-31  6:27:28 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] Plugin 'wsrep-provider' is disabled.
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] InnoDB: Buffer pool(s) load completed at 251031  6:27:28
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] Server socket created on IP: '0.0.0.0', port: '3306'.
mariadb stdout | 2025-10-31  6:27:28 0 [Note] Server socket created on IP: '::', port: '3306'.
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
mariadb stdout |
mariadb stdout | 2025-10-31  6:27:28 0 [Note] mariadbd: ready for connections.
mariadb stdout | Version: '11.8.3-MariaDB-deb13'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mariadb stdout |
2025-10-31 06:27:30,262 INFO spawned: 'php-fpm' with pid 159
[31-Oct-2025 06:27:30] NOTICE: fpm is running, pid 159
[31-Oct-2025 06:27:30] NOTICE: ready to handle connections
2025-10-31 06:27:31,299 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
php-fpm: started
2025-10-31 06:27:31,424 INFO spawned: 'centrifugo' with pid 161
centrifugo stdout | {"level":"info","path":"/var/azuracast/centrifugo/config.toml","time":"2025-10-31T06:27:31Z","message":"using config file"}
centrifugo stdout |
centrifugo stdout | {"level":"info","time":"2025-10-31T06:27:31Z","message":"maxprocs: leaving gomaxprocs=12: cpu quota undefined"}
centrifugo stdout | {"level":"info","version":"6.4.0","runtime":"go1.25.3","pid":161,"gomaxprocs":12,"engine":"redis","time":"2025-10-31T06:27:31Z","message":"starting Centrifugo"}
centrifugo stdout |
centrifugo stdout | {"level":"info","engine_type":"redis","engine_mode":"standalone","time":"2025-10-31T06:27:31Z","message":"initializing engine"}
centrifugo stdout | {"level":"info","time":"2025-10-31T06:27:31Z","message":"explicit broker not provided, using the one from engine"}
centrifugo stdout | {"level":"info","time":"2025-10-31T06:27:31Z","message":"explicit presence manager not provided, using the one from engine"}
centrifugo stdout |
centrifugo stdout | {"level":"warn","time":"2025-10-31T06:27:31Z","message":"usage of allowed_origins * is discouraged for security reasons, consider setting exact list of origins"}
centrifugo stdout |
centrifugo stdout | {"level":"info","time":"2025-10-31T06:27:31Z","message":"serving uni_websocket, uni_sse, uni_http_stream endpoints on :6020"}
centrifugo stdout |
centrifugo stdout | {"level":"info","time":"2025-10-31T06:27:31Z","message":"serving api, admin endpoints on :6025"}
centrifugo stdout | {"level":"warn","time":"2025-10-31T06:27:31Z","message":"INSECURE HTTP API mode enabled, make sure you understand risks"}
centrifugo stdout | {"level":"warn","time":"2025-10-31T06:27:31Z","message":"INSECURE admin mode enabled, make sure you understand risks"}
centrifugo stdout |
2025-10-31 06:27:32,657 INFO success: centrifugo entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
centrifugo: started
2025-10-31 06:27:34,791 INFO spawned: 'nginx' with pid 177
nginx stdout | 2025/10/31 06:27:34 [warn] 177#177: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/sites-enabled/default.vhost:52
nginx stdout |
2025-10-31 06:27:35,807 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nginx: started

Waiting for web server (nginx) to become available...
=====================================================

 Waiting...
 Services started up and ready!

2025-10-31 06:27:36,283 INFO spawned: 'cron' with pid 198
2025-10-31 06:27:36,284 INFO spawned: 'php-nowplaying' with pid 199
2025-10-31 06:27:36,286 INFO spawned: 'php-worker' with pid 200
2025-10-31 06:27:36,288 INFO spawned: 'sftpgo' with pid 201
cron stdout | time="2025-10-31T06:27:36Z" level=warning msg="process reaping disabled, not pid 1"
cron stdout |
cron stdout | time="2025-10-31T06:27:36Z" level=info msg="read crontab: /etc/cron.d/azuracast"
cron stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.376","sender":"service","message":"starting SFTPGo 2.6.4-386448e6-2024-11-28T06:10:32Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite -unixcrypt +portable, config dir: /var/azuracast/sftpgo, config file: , log max size: 10 log max backups: 5 log max age: 28 log level: debug, log compress: false, log utc time: false, load data from: \"\", grace time: 0 secs"}
sftpgo stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.377","sender":"config","message":"set env vars from file \"/var/azuracast/sftpgo/env.d/sftpd.env\""}
sftpgo stdout |
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.381","sender":"config","message":"config file used: '\"/var/azuracast/sftpgo/sftpgo.json\"', config loaded: {Common:{IdleTimeout:15 UploadMode:2 Actions:{ExecuteOn:[upload pre-delete rename] ExecuteSync:[] Hook:http://localhost:6010/api/internal/sftp-event} SetstatMode:1 RenameMode:0 ResumeMaxSize:0 TempPath:/tmp/sftpgo_temp ProxyProtocol:0 ProxyAllowed:[] ProxySkipped:[] StartupHook: PostConnectHook: PostDisconnectHook: DataRetentionHook: MaxTotalConnections:0 MaxPerHostConnections:20 AllowListStatus:0 AllowSelfConnections:0 DefenderConfig:{Enabled:true Driver:memory BanTime:5 BanTimeIncrement:50 Threshold:15 ScoreInvalid:2 ScoreValid:1 ScoreLimitExceeded:3 ScoreNoAuth:0 ObservationTime:15 EntriesSoftLimit:100 EntriesHardLimit:150 LoginDelay:{Success:0 PasswordFailed:1000}} RateLimitersConfig:[{Average:0 Period:1000 Burst:1 Type:2 Protocols:[SSH FTP DAV HTTP] GenerateDefenderEvents:false EntriesSoftLimit:100 EntriesHardLimit:150}] Umask: ServerVersion: Metadata:{Read:0} EventManager:{EnabledCommands:[]} idleTimeoutAsDuration:0 idleLoginTimeout:0 defender:<nil> allowList:<nil> rateLimitersList:<nil> proxyAllowed:[] proxySkipped:[]} ACME:{Email: KeyType:4096 CertsPath:certs CAEndpoint:https://acme-v02.api.letsencrypt.org/directory Domains:[] RenewDays:30 HTTP01Challenge:{Port:80 WebRoot: ProxyHeader:} TLSALPN01Challenge:{Port:0} accountConfigPath: accountKeyPath: lockPath: tempDir:} SFTPD:{Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] MaxAuthTries:0 HostKeys:[../storage/sftpgo/id_rsa ../storage/sftpgo/id_ecdsa ../storage/sftpgo/id_ed25519] HostCertificates:[] HostKeyAlgorithms:[] KexAlgorithms:[] MinDHGroupExchangeKeySize:2048 Ciphers:[] MACs:[] PublicKeyAlgorithms:[] TrustedUserCAKeys:[] RevokedUserCertsFile: LoginBannerFile: EnabledSSHCommands:[md5sum sha1sum sha256sum cd pwd scp] KeyboardInteractiveAuthentication:true KeyboardInteractiveHook: PasswordAuthentication:true certChecker:<nil> parsedUserCAKeys:[]} FTPD:{Bindings:[{Address: Port:0 ApplyProxyConfig:true TLSMode:0 TLSSessionReuse:0 CertificateFile: CertificateKeyFile: MinTLSVersion:12 ForcePassiveIP: PassiveIPOverrides:[] PassiveHost: ClientAuthType:0 TLSCipherSuites:[] PassiveConnectionsSecurity:0 ActiveConnectionsSecurity:0 IgnoreASCIITransferType:0 Debug:false ciphers:[]}] BannerFile: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] ActiveTransfersPortNon20:true DisableActiveMode:false EnableSite:false HASHSupport:0 CombineSupport:0 PassivePortRange:{Start:50000 End:50100} acmeDomain:} WebDAVD:{Bindings:[{Address: Port:0 EnableHTTPS:false CertificateFile: CertificateKeyFile: MinTLSVersion:12 ClientAuthType:0 TLSCipherSuites:[] Protocols:[] Prefix: ProxyAllowed:[] ClientIPProxyHeader: ClientIPHeaderDepth:0 DisableWWWAuthHeader:false allowHeadersFrom:[]}] CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0 OptionsPassthrough:false OptionsSuccessStatus:0 AllowPrivateNetwork:false} Cache:{Users:{ExpirationTime:0 MaxSize:50} MimeTypes:{Enabled:true MaxSize:1000 CustomMappings:[]}} acmeDomain:} ProviderConf:{Driver:bolt Name:sftpgo.db Host: Port:0 Username: Password: SSLMode:0 DisableSNI:false TargetSessionAttrs: RootCert: ClientCert: ClientKey: ConnectionString: SQLTablesPrefix: TrackQuota:2 PoolSize:0 UsersBaseDir:/var/azuracast/stations Actions:{ExecuteOn:[] ExecuteFor:[] Hook:} ExternalAuthHook:http://localhost:6010/api/internal/sftp-auth ExternalAuthScope:0 PreLoginHook: PostLoginHook: PostLoginScope:0 CheckPasswordHook: CheckPasswordScope:0 UpdateMode:0 PasswordHashing:{BcryptOptions:{Cost:10} Argon2Options:{Memory:65536 Iterations:1 Parallelism:2} Algo:bcrypt} PasswordValidation:{Admins:{MinEntropy:0} Users:{MinEntropy:0}} PasswordCaching:true DelayedQuotaUpdate:0 CreateDefaultAdmin:false NamingRules:1 IsShared:0 Node:{Host: Port:0 Proto:http} BackupsPath:backups} HTTPDConfig:{Bindings:[{Address: Port:0 EnableWebAdmin:true EnableWebClient:true EnableRESTAPI:true EnabledLoginMethods:0 EnableHTTPS:false CertificateFile: CertificateKeyFile: MinTLSVersion:12 ClientAuthType:0 TLSCipherSuites:[] Protocols:[] ProxyAllowed:[] ClientIPProxyHeader: ClientIPHeaderDepth:0 HideLoginURL:0 RenderOpenAPI:true OIDC:{ClientID: ClientSecret: ClientSecretFile: ConfigURL: RedirectBaseURL: UsernameField: RoleField: ImplicitRoles:false Scopes:[openid profile email] CustomFields:[] InsecureSkipSignatureCheck:false Debug:false provider:<nil> verifier:<nil> providerLogoutURL: oauth2Config:<nil>} Security:{Enabled:false AllowedHosts:[] AllowedHostsAreRegex:false HostsProxyHeaders:[] HTTPSRedirect:false HTTPSHost: HTTPSProxyHeaders:[] STSSeconds:0 STSIncludeSubdomains:false STSPreload:false ContentTypeNosniff:false ContentSecurityPolicy: PermissionsPolicy: CrossOriginOpenerPolicy: CacheControl: proxyHeaders:[]} Branding:{WebAdmin:{Name: ShortName: LogoPath: FaviconPath: DisclaimerName: DisclaimerPath: DefaultCSS:[] ExtraCSS:[]} WebClient:{Name: ShortName: LogoPath: FaviconPath: DisclaimerName: DisclaimerPath: DefaultCSS:[] ExtraCSS:[]}} allowHeadersFrom:[]}] TemplatesPath:/usr/share/sftpgo/templates StaticFilesPath:/usr/share/sftpgo/static OpenAPIPath:openapi WebRoot: CertificateFile: CertificateKeyFile: CACertificates:[] CARevocationLists:[] SigningPassphrase: SigningPassphraseFile: TokenValidation:0 MaxUploadFileSize:0 Cors:{AllowedOrigins:[] AllowedMethods:[] AllowedHeaders:[] ExposedHeaders:[] AllowCredentials:false Enabled:false MaxAge:0 OptionsPassthrough:false OptionsSuccessStatus:0 AllowPrivateNetwork:false} Setup:{InstallationCode: InstallationCodeHint:Installation code} HideSupportLink:false acmeDomain:} HTTPConfig:{Timeout:20 RetryWaitMin:2 RetryWaitMax:30 RetryMax:3 CACertificates:[] Certificates:[] SkipTLSVerify:false Headers:[] customTransport:<nil>} CommandConfig:{Timeout:30 Env:[] Commands:[]} KMSConfig:{Secrets:{URL: MasterKeyPath: MasterKeyString: masterKey:}} MFAConfig:{TOTP:[{Name:Default Issuer:SFTPGo Algo:sha1 algo:0}]} TelemetryConfig:{BindPort:0 BindAddress:127.0.0.1 EnableProfiler:false AuthUserFile: CertificateFile: CertificateKeyFile: TLSCipherSuites:[] MinTLSVersion:12 Protocols:[]} PluginsConfig:[] SMTPConfig:{Host: Port:587 From: User: Password: AuthType:0 Encryption:0 Domain: TemplatesPath:templates Debug:0 OAuth2:{Provider:0 Tenant: ClientID: ClientSecret: RefreshToken: mu:<nil> config:<nil> accessToken:<nil>}}}"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.381","sender":"kms","message":"secret provider registered for scheme: \"builtin\", encrypted status: \"AES-256-GCM\""}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.381","sender":"kms","message":"secret provider registered for scheme: \"local\", encrypted status: \"Secretbox\""}
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.381","sender":"plugins","message":"initialize"}
sftpgo stdout |
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.388","sender":"dataprovider_bolt","message":"bolt key store handle created"}
sftpgo stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.422","sender":"dataprovider_bolt","message":"updating database schema version: 28 -> 29"}
sftpgo stdout |
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.425","sender":"dataprovider_bolt","message":"absolute backup path \"/var/azuracast/sftpgo/backups\""}
sftpgo stdout |
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.425","sender":"util","message":"found share data path for name \"templates\": \"/usr/share/sftpgo/templates\""}
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.425","sender":"smtp","message":"loading templates from \"/usr/share/sftpgo/templates/email\""}
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.425","sender":"dataprovider_bolt","message":"delayed quota update loop started, wait time: 0s"}
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.425","sender":"dataprovider_bolt","message":"delayed quota update loop ended, wait time: 0s"}
sftpgo stdout |
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.426","sender":"smtp","message":"activating initial config"}
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.426","sender":"smtp","message":"configuration disabled, email capabilities will not be available"}
sftpgo stdout |
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.426","sender":"eventmanager","message":"loading updated rules"}
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.426","sender":"eventmanager","message":"recently updated event rules loaded: 0"}
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.426","sender":"eventmanager","message":"event rules updated, fs events: 0, provider events: 0, schedules: 0, ip blocked events: 0, certificate events: 0, IDP login events: 0"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.426","sender":"common","message":"scheduled overquota transfers check, schedule \"@every 1m0s\""}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.426","sender":"common","message":"scheduled idle connections check, schedule \"@every 3m0s\""}
sftpgo stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.426","sender":"dataprovider_bolt","message":"using in-memory matching for list type 2, num entries: 0"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.426","sender":"common","message":"defender initialized with config {Enabled:true Driver:memory BanTime:5 BanTimeIncrement:50 Threshold:15 ScoreInvalid:2 ScoreValid:1 ScoreLimitExceeded:3 ScoreNoAuth:0 ObservationTime:15 EntriesSoftLimit:100 EntriesHardLimit:150 LoginDelay:{Success:0 PasswordFailed:1000}}"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.426","sender":"common","message":"using memory transfer checker"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.426","sender":"acme","message":"no domains configured, acme disabled"}
sftpgo stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.427","sender":"service","message":"HTTP server not started, disabled in config file"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.427","sender":"service","message":"FTP server not started, disabled in config file"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.427","sender":"service","message":"WebDAV server not started, disabled in config file"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.427","sender":"service","message":"telemetry server not started, disabled in config file"}
sftpgo stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.427","sender":"service","message":"initializing SFTP server with config {Bindings:[{Address: Port:2022 ApplyProxyConfig:true}] MaxAuthTries:0 HostKeys:[../storage/sftpgo/id_rsa ../storage/sftpgo/id_ecdsa ../storage/sftpgo/id_ed25519] HostCertificates:[] HostKeyAlgorithms:[] KexAlgorithms:[] MinDHGroupExchangeKeySize:2048 Ciphers:[] MACs:[] PublicKeyAlgorithms:[] TrustedUserCAKeys:[] RevokedUserCertsFile: LoginBannerFile: EnabledSSHCommands:[md5sum sha1sum sha256sum cd pwd scp] KeyboardInteractiveAuthentication:true KeyboardInteractiveHook: PasswordAuthentication:true certChecker:<nil> parsedUserCAKeys:[]}"}
sftpgo stdout |
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.427","sender":"sftpd","message":"minimum key size allowed for diffie-ellman-group-exchange: 2048"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.427","sender":"sftpd","message":"Loading private host key \"/var/azuracast/storage/sftpgo/id_rsa\""}
sftpgo stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.428","sender":"sftpd","message":"Host key \"/var/azuracast/storage/sftpgo/id_rsa\" loaded, type \"ssh-rsa\", fingerprint \"SHA256:PRX29m2xz8L3UI4Px5vz4wOFT6bbAb8AGjBMiB9iEWU\", algorithms [rsa-sha2-256 rsa-sha2-512]"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.428","sender":"sftpd","message":"Loading private host key \"/var/azuracast/storage/sftpgo/id_ecdsa\""}
sftpgo stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.440","sender":"sftpd","message":"Host key \"/var/azuracast/storage/sftpgo/id_ecdsa\" loaded, type \"ecdsa-sha2-nistp521\", fingerprint \"SHA256:hvA5PKE7kvrk88V3ucyNBHox+5gfn7dyxh8y+zlfa2c\", algorithms [ecdsa-sha2-nistp521]"}
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.440","sender":"sftpd","message":"Loading private host key \"/var/azuracast/storage/sftpgo/id_ed25519\""}
sftpgo stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.440","sender":"sftpd","message":"Host key \"/var/azuracast/storage/sftpgo/id_ed25519\" loaded, type \"ssh-ed25519\", fingerprint \"SHA256:sXb/cA5oneOUY/O3bMtxqXb8t+SL4H5Z2hhmeAVztkE\", algorithms [ssh-ed25519]"}
sftpgo stdout | {"level":"debug","time":"2025-10-31T06:27:36.440","sender":"sftpd","message":"enabled SSH commands [md5sum sha1sum sha256sum cd pwd scp]"}
sftpgo stdout |
sftpgo stdout | {"level":"info","time":"2025-10-31T06:27:36.441","sender":"sftpd","message":"server listener registered, address: [::]:2022"}
sftpgo stdout |
2025-10-31 06:27:37,442 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-10-31 06:27:37,442 INFO success: php-nowplaying entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-10-31 06:27:37,442 INFO success: php-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-10-31 06:27:37,442 INFO success: sftpgo entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cron: started
php-nowplaying: started
php-worker: started
sftpgo: started
2025-10-31 06:27:37,463 INFO exited: startup (exit status 0; expected)
```

**Comment by laertoliveira** [comment]
It's a bug that I've already reported and so far it hasn't been fixed. The problem is that the storage_locations are not defined. It is necessary to go to Administration Storage Locations and set a storage location: /var/azuracast/stations after doing this when creating the station it is saved in the correct location and you can delete the path you created manually. This bug exists in both the Stable channel and the Rolling Release channel.

**Comment by eberciny** [comment]
This problem still happens to me too. What I did to get around it was to access the panel directly and create the station through the station management page. Now this doesn't happen to me anymore! But the system configuration part, the step after creating the first station, still doesn't save. I used the CLI in the terminal to set the options, but even so, the screen still appears with the configuration values ​​already filled in.

**Comment by AusDavo** [comment]
Yeah, does it to me too.

**Comment by BusterNeece** [comment]
Yikes...my mistake for missing this one for so long, folks.

Definitely a valid issue, definitely something on our end. Quite a small thing, but it would've prevented setup from running normally for basically all new installations in the last few months.

It's fixed in the very latest Rolling Release. Thank you all for your patience and understanding.

**Comment by AusDavo** [comment]
Just wanted to let you know that I ran the update script and now confirm that the issue is resolved. Thank you!

**Comment by armandovias** [comment]
It's happening to me as well. I thought that I was going crazy. I'm using the Stable Release. Thank goodness that I looked this up before I got more frustrated. Thank you again.

**Comment by JesseHoekema** [comment]
Still happening to me on stable. Im running on docker. I also found that recently my playlist contents where gone empty after a reboot i dont know if that has to do with this bug

**Comment by tmrxdev** [comment]
> Still happening to me on stable. Im running on docker. I also found that recently my playlist contents where gone empty after a reboot i dont know if that has to do with this bug

Same with me, also on the latest Stable.

**Comment by JesseHoekema** [comment]
> > Still happening to me on stable. Im running on docker. I also found that recently my playlist contents where gone empty after a reboot i dont know if that has to do with this bug
> 
> Same with me, also on the latest Stable.

Also the playlist issue?

**Comment by tmrxdev** [comment]
> > > Still happening to me on stable. Im running on docker. I also found that recently my playlist contents where gone empty after a reboot i dont know if that has to do with this bug
> > 
> > Same with me, also on the latest Stable.
> 
> Also the playlist issue?

Haven't rebooted yet
