### ISSUE TITLE
PHP Fatal Error while updating

### ISSUE THREAD

**Issue by Sella-GH** [AzuraCast/AzuraCast#8292]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

After downloading the newest docker image the installer created the new container: Container azuracast_installer-installer-run-849d16826a54

Then the errors occurred but the installer went forward and updated to the newest version. It all ran fine but the error was still there so I report it now.

### Relevant log output

```shell
[14-Dec-2025 03:18:54 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Application::add() in /var/azuracast/www/backend/bin/installer:20
Stack trace:
#0 {main}
  thrown in /var/azuracast/www/backend/bin/installer on line 20

Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Console\Application::add() in /var/azuracast/www/backend/bin/installer:20
Stack trace:
#0 {main}
  thrown in /var/azuracast/www/backend/bin/installer on line 20

[+] down 3/3
```

**Comment by BusterNeece** [comment]
@Sella-GH That error was definitely a thing for one or two versions in the middle of the weekend, but should be fixed as of the latest version now. Can you re-update to confirm?

**Comment by Sella-GH** [comment]
@BusterNeece Sorry can't confirm, error still comes up as of now.

```
Container azuracast_installer-installer-run-253016ae4a3d Creating
Container azuracast_installer-installer-run-253016ae4a3d Created
[14-Dec-2025 21:27:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Application::add() in /var/azuracast/www/backend/bin/installer:20
Stack trace:
#0 {main}
  thrown in /var/azuracast/www/backend/bin/installer on line 20

Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Console\Application::add() in /var/azuracast/www/backend/bin/installer:20
Stack trace:
#0 {main}
  thrown in /var/azuracast/www/backend/bin/installer on line 20
```

**Comment by BusterNeece** [comment]
@Sella-GH My mistake. Fixed in one spot, not the other. Pushing fix.

**Comment by Sella-GH** [comment]
@BusterNeece This worked, thanks! Update looks clean as always now. 🙂
